# Code generated by surface-gen; DO NOT EDIT.
# Every catalogued sdk method must exist and be callable on the client.
# Generated from backend/openapi/surfaces.ir.json.
from bird import Bird


def test_surface_conformance() -> None:
    client = Bird(api_key="bk_eu1_surfaceconformance")
    assert callable(client.email.send)
    assert callable(client.email.send_batch)
    assert callable(client.email.get)
    assert callable(client.email.list)
    assert callable(client.webhooks.unwrap)
