# Code generated by surface-gen; DO NOT EDIT.
# Every catalogued sdk method must exist and be callable on the client.
# Generated from backend/openapi/surfaces.ir.json.
from bird import Bird


def test_surface_conformance() -> None:
    client = Bird(api_key="bk_eu1_surfaceconformance")
    assert callable(client.email.send)
    assert callable(client.email.send_batch)
    assert callable(client.email.get)
    assert callable(client.email.list)
    assert callable(client.email_templates.create)
    assert callable(client.email_templates.list)
    assert callable(client.email_templates.get)
    assert callable(client.email_templates.update)
    assert callable(client.email_templates.delete)
    assert callable(client.email_templates.publish)
    assert callable(client.email_templates.list_versions)
    assert callable(client.email_templates.get_version)
    assert callable(client.sms.send)
    assert callable(client.sms.send_batch)
    assert callable(client.sms.get)
    assert callable(client.sms.list)
    assert callable(client.sms_templates.list)
    assert callable(client.sms_templates.get)
    assert callable(client.webhooks.unwrap)
