"""The official Python SDK for the Bird email platform (ADR-0045).

The wire models are generated from the OpenAPI spec into ``bird._generated`` and
never hand-edited; this package is the hand-written, idiomatic layer on top — a
synchronous ``Bird`` client and an asynchronous ``AsyncBird`` client, a typed
exception hierarchy, safe retries, pagination, and webhook verification.
"""

from __future__ import annotations

from bird._client import AsyncBird, Bird
from bird._response import APIResponse
from bird._types import (
    Attachment,
    AudienceContactsAddParams,
    AudienceContactsRemoveParams,
    AudienceCreateParams,
    AudienceListContactsParams,
    AudienceListParams,
    AudienceUpdateParams,
    ContactBatchParams,
    ContactCreateParams,
    ContactListParams,
    ContactPropertyCreateParams,
    ContactPropertyListParams,
    ContactPropertyUpdateParams,
    ContactUpdateParams,
    DomainCreateParams,
    DomainListParams,
    DomainUpdateParams,
    EmailDefaults,
    EmailListParams,
    EmailSendBatchParams,
    EmailSendParams,
    RequestOptions,
    SmsSendParams,
    VerificationCheckParams,
    VerificationCreateParams,
    WhatsappSendParams,
)
from bird._generated import (
    Audience,
    AudienceList,
    AudienceMember,
    AudienceMemberList,
    Contact,
    ContactList,
    ContactProperty,
    ContactPropertyList,
    ContactUpsertResult,
    DNSRecord,
    Domain,
    DomainCapabilities,
    DomainDKIM,
    DomainList,
    EmailMessage,
    EmailMessageBatchResponse,
    SMSMessage,
    SMSMessageBatchResponse,
    SMSTemplate,
    SMSTemplateList,
    Verification,
    VerificationCheckResult,
    WebhookEvent,
    WhatsAppEvent,
    WhatsAppEventList,
    WhatsAppMessage,
    WhatsAppTemplate,
    WhatsAppTemplateList,
)
from bird._event_types import WebhookEventType
from bird.resources.webhooks import GenericWebhookEvent
from bird._exceptions import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    BirdError,
    ErrorDetail,
    ErrorNextAction,
    ErrorType,
    RateLimitError,
    UnmetGate,
    ValidationError,
    WebhookVerificationError,
)
from bird.pagination import AsyncPage, SyncPage
from bird._version import __version__

__all__ = [
    "Bird",
    "AsyncBird",
    "RequestOptions",
    "EmailDefaults",
    "Attachment",
    "EmailSendParams",
    "EmailSendBatchParams",
    "EmailListParams",
    "ContactCreateParams",
    "ContactUpdateParams",
    "ContactListParams",
    "ContactBatchParams",
    "Contact",
    "ContactList",
    "ContactUpsertResult",
    "ContactPropertyCreateParams",
    "ContactPropertyUpdateParams",
    "ContactPropertyListParams",
    "ContactProperty",
    "ContactPropertyList",
    "AudienceCreateParams",
    "AudienceUpdateParams",
    "AudienceListParams",
    "AudienceListContactsParams",
    "AudienceContactsAddParams",
    "AudienceContactsRemoveParams",
    "Audience",
    "AudienceList",
    "AudienceMember",
    "AudienceMemberList",
    "DomainCreateParams",
    "DomainUpdateParams",
    "DomainListParams",
    "Domain",
    "DomainList",
    "DNSRecord",
    "DomainDKIM",
    "DomainCapabilities",
    "APIResponse",
    "SyncPage",
    "AsyncPage",
    "EmailMessage",
    "EmailMessageBatchResponse",
    "SmsSendParams",
    "SMSMessage",
    "SMSMessageBatchResponse",
    "SMSTemplate",
    "SMSTemplateList",
    "WhatsappSendParams",
    "WhatsAppMessage",
    "WhatsAppEvent",
    "WhatsAppEventList",
    "WhatsAppTemplate",
    "WhatsAppTemplateList",
    "VerificationCreateParams",
    "VerificationCheckParams",
    "Verification",
    "VerificationCheckResult",
    "WebhookEvent",
    "GenericWebhookEvent",
    "WebhookEventType",
    "BirdError",
    "APIError",
    "APIStatusError",
    "RateLimitError",
    "ValidationError",
    "APIConnectionError",
    "APITimeoutError",
    "WebhookVerificationError",
    "ErrorDetail",
    "ErrorNextAction",
    "ErrorType",
    "UnmetGate",
    "__version__",
]
