# Code generated by beak gen:event-consts. DO NOT EDIT.
"""Known values of the API's open enums.

Each wire value is an open string: a value added by a newer server is returned
unchanged, so compare against these constants and handle unrecognized values as
a fallback rather than assuming the set is closed.
"""

from __future__ import annotations

from typing import Final


class EmailEventType:
    """Values of EmailEventType known at this SDK version (open enum)."""

    EMAIL_ACCEPTED: Final = "email.accepted"
    EMAIL_BOUNCED: Final = "email.bounced"
    EMAIL_CANCELED: Final = "email.canceled"
    EMAIL_CLICKED: Final = "email.clicked"
    EMAIL_COMPLAINED: Final = "email.complained"
    EMAIL_DEFERRED: Final = "email.deferred"
    EMAIL_DELIVERED: Final = "email.delivered"
    EMAIL_LIST_UNSUBSCRIBED: Final = "email.list_unsubscribed"
    EMAIL_OPENED: Final = "email.opened"
    EMAIL_OUT_OF_BAND_BOUNCE: Final = "email.out_of_band_bounce"
    EMAIL_PROCESSED: Final = "email.processed"
    EMAIL_REJECTED: Final = "email.rejected"
    EMAIL_SCHEDULED: Final = "email.scheduled"
    EMAIL_UNSUBSCRIBED: Final = "email.unsubscribed"


class SMSErrorCode:
    """Values of SMSErrorCode known at this SDK version (open enum)."""

    BLOCKED_BY_CARRIER: Final = "blocked_by_carrier"
    BLOCKED_BY_RECIPIENT: Final = "blocked_by_recipient"
    CONTENT_REJECTED: Final = "content_rejected"
    INSUFFICIENT_BALANCE: Final = "insufficient_balance"
    INVALID_DESTINATION: Final = "invalid_destination"
    LANDLINE_UNREACHABLE: Final = "landline_unreachable"
    PROVIDER_UNAVAILABLE: Final = "provider_unavailable"
    RECIPIENT_OPTED_OUT: Final = "recipient_opted_out"
    SENDER_UNREGISTERED: Final = "sender_unregistered"
    UNKNOWN: Final = "unknown"
    UNREACHABLE: Final = "unreachable"


class VerificationAttemptFailureReason:
    """Values of VerificationAttemptFailureReason known at this SDK version (open enum)."""

    CARRIER_REJECTED: Final = "carrier_rejected"
    CHANNEL_DISABLED: Final = "channel_disabled"
    CHANNEL_UNAVAILABLE: Final = "channel_unavailable"
    HARD_BOUNCE: Final = "hard_bounce"
    SOFT_BOUNCE: Final = "soft_bounce"
    UNDELIVERED: Final = "undelivered"


class VerificationChannel:
    """Values of VerificationChannel known at this SDK version (open enum)."""

    EMAIL: Final = "email"
    SMS: Final = "sms"
    WHATSAPP: Final = "whatsapp"


class VerificationTerminalReason:
    """Values of VerificationTerminalReason known at this SDK version (open enum)."""

    ATTEMPTS_EXHAUSTED: Final = "attempts_exhausted"
    TTL_ELAPSED: Final = "ttl_elapsed"


class WhatsAppErrorCode:
    """Values of WhatsAppErrorCode known at this SDK version (open enum)."""

    INSUFFICIENT_BALANCE: Final = "insufficient_balance"
    INTERNAL_ERROR: Final = "internal_error"
    PRICE_NOT_FOUND: Final = "price_not_found"
    RATE_LIMITED: Final = "rate_limited"
    RECIPIENT_SUPPRESSED: Final = "recipient_suppressed"
    SERVICE_WINDOW_EXPIRED: Final = "service_window_expired"
    UNDELIVERABLE: Final = "undeliverable"


class WhatsAppTemplateCategory:
    """Values of WhatsAppTemplateCategory known at this SDK version (open enum)."""

    AUTHENTICATION: Final = "authentication"
    MARKETING: Final = "marketing"
    UTILITY: Final = "utility"


class WhatsAppTemplateParameterType:
    """Values of WhatsAppTemplateParameterType known at this SDK version (open enum)."""

    DOCUMENT: Final = "document"
    GIF: Final = "gif"
    IMAGE: Final = "image"
    LOCATION: Final = "location"
    TEXT: Final = "text"
    VIDEO: Final = "video"


__all__ = [
    "EmailEventType",
    "SMSErrorCode",
    "VerificationAttemptFailureReason",
    "VerificationChannel",
    "VerificationTerminalReason",
    "WhatsAppErrorCode",
    "WhatsAppTemplateCategory",
    "WhatsAppTemplateParameterType",
]
