# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    AMBChannelSettings,
    AMBChannelSettingsUpdate,
)
from bird._models import to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit


class _AMBEntryPointRequired(TypedDict):
    id: str
    group: str
    intent: str
    body: str


class AMBEntryPoint(_AMBEntryPointRequired, total=False):
    pass


class AmbBusinessAccountsSettingsUpdateParams(TypedDict, total=False):
    """Params for ``client.amb.business_accounts.settings.update``. Every key is optional."""

    entry_points: Sequence[AMBEntryPoint]
    default_locale: str | None
    brand_name: str
    logo_asset_id: str | None


class AmbBusinessAccountsSettings(Resource):
    def get(
        self,
        business_account_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> AMBChannelSettings:
        """Returns the channel settings for your workspace's Apple Messages for Business record: its entry points, default locale, and the brand name and logo shown on the landing page customers use to connect it.

        ```python
        result = client.amb.business_accounts.settings.get('abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            f"/v1/amb/business-accounts/{quote(business_account_id, safe='')}/channel-settings",
            {},
            AMBChannelSettings,
            options,
        )

    def update(
        self,
        business_account_id: str,
        *,
        entry_points: Sequence[AMBEntryPoint] | None = None,
        default_locale: str | None | Omit = omit,
        brand_name: str | None = None,
        logo_asset_id: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> AMBChannelSettings:
        """Changes the channel settings for your workspace's Apple Messages for Business record. Fields you omit are left as they are, except `entry_points`: sending it replaces the entire set, since there is no way to add or remove a single entry point without resending the rest.

        ```python
        result = client.amb.business_accounts.settings.update('abz_01krdgeqcxet5s7t44vh8rt9mg', brand_name='Acme Support', logo_asset_id=None)
        print(result)
        ```
        """
        _body: dict[str, Any] = {}
        if entry_points is not None:
            _body["entry_points"] = entry_points
        if not isinstance(default_locale, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["default_locale"] = default_locale
        if brand_name is not None:
            _body["brand_name"] = brand_name
        if not isinstance(logo_asset_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["logo_asset_id"] = logo_asset_id
        body = to_wire_exclude_unset(AMBChannelSettingsUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/amb/business-accounts/{quote(business_account_id, safe='')}/channel-settings",
            body,
            AMBChannelSettings,
            options,
        )


class AsyncAmbBusinessAccountsSettings(AsyncResource):
    async def get(
        self,
        business_account_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> AMBChannelSettings:
        """Returns the channel settings for your workspace's Apple Messages for Business record: its entry points, default locale, and the brand name and logo shown on the landing page customers use to connect it.

        ```python
        result = await client.amb.business_accounts.settings.get('abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            f"/v1/amb/business-accounts/{quote(business_account_id, safe='')}/channel-settings",
            {},
            AMBChannelSettings,
            options,
        )

    async def update(
        self,
        business_account_id: str,
        *,
        entry_points: Sequence[AMBEntryPoint] | None = None,
        default_locale: str | None | Omit = omit,
        brand_name: str | None = None,
        logo_asset_id: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> AMBChannelSettings:
        """Changes the channel settings for your workspace's Apple Messages for Business record. Fields you omit are left as they are, except `entry_points`: sending it replaces the entire set, since there is no way to add or remove a single entry point without resending the rest.

        ```python
        result = await client.amb.business_accounts.settings.update('abz_01krdgeqcxet5s7t44vh8rt9mg', brand_name='Acme Support', logo_asset_id=None)
        print(result)
        ```
        """
        _body: dict[str, Any] = {}
        if entry_points is not None:
            _body["entry_points"] = entry_points
        if not isinstance(default_locale, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["default_locale"] = default_locale
        if brand_name is not None:
            _body["brand_name"] = brand_name
        if not isinstance(logo_asset_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["logo_asset_id"] = logo_asset_id
        body = to_wire_exclude_unset(AMBChannelSettingsUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/amb/business-accounts/{quote(business_account_id, safe='')}/channel-settings",
            body,
            AMBChannelSettings,
            options,
        )
