# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict

from bird._generated import (
    AMBStatsByBusinessResponse,
    AMBStatsByCategoryResponse,
    AMBStatsByErrorCodeResponse,
    AMBStatsByGroupResponse,
    AMBStatsByIntentResponse,
    AMBStatsByMessageKindResponse,
    AMBStatsByTagResponse,
    AMBStatsResponse,
    AMBStatsSummary,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class AmbStatsByBusinessParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_business``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsByCategoryParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_category``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsDailyParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.daily``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    business_account_id: str
    message_kind: str
    intent: str
    group: str
    category: str
    tag: str


class AmbStatsByErrorCodeParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_error_code``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsByGroupParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_group``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsHourlyParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.hourly``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    business_account_id: str
    message_kind: str
    intent: str
    group: str
    category: str
    tag: str


class AmbStatsByIntentParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_intent``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsByMessageKindParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_message_kind``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsSummaryParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.summary``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    business_account_id: str
    message_kind: str
    intent: str
    group: str
    category: str
    tag: str
    compare: str


class AmbStatsByTagParams(TypedDict, total=False):
    """Query params for ``client.amb.stats.by_tag``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    limit: int


class AmbStatsBase(Resource):
    def by_business(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByBusinessResponse:
        """Returns outbound counts and latency percentiles grouped by business, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = client.amb.stats.by_business(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/businesses",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByBusinessResponse,
            options,
        )

    def by_category(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByCategoryResponse:
        """Returns outbound counts and latency percentiles grouped by message category, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). A send that names no category is grouped under an empty-string category. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = client.amb.stats.by_category(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/categories",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByCategoryResponse,
            options,
        )

    def daily(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsResponse:
        """Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every count in a row is attributed to the day its message was accepted, regardless of when a later event, such as a send failure, arrived.

        ```python
        result = client.amb.stats.daily(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/daily",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
            },
            AMBStatsResponse,
            options,
        )

    def by_error_code(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByErrorCodeResponse:
        """Returns outbound counts and latency percentiles grouped by failure reason, for the requested period. Rows are ranked by `send_failed + rejected` descending and capped at the requested `limit` (default 50, max 200). Only messages carrying a failure reason appear: a `bird:` code is usually a rejection (never charged, never attempted), an `apple:` code a send failure; use the summary for the period's full accepted total.

        ```python
        result = client.amb.stats.by_error_code(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/error-codes",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByErrorCodeResponse,
            options,
        )

    def by_group(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByGroupResponse:
        """Returns outbound counts and latency percentiles grouped by entry-point group, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Groups are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = client.amb.stats.by_group(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/groups",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByGroupResponse,
            options,
        )

    def hourly(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsResponse:
        """Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every count in a row is attributed to the hour its message was accepted, regardless of when a later event, such as a send failure, arrived. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.daily`.

        ```python
        result = client.amb.stats.hourly(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/hourly",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
            },
            AMBStatsResponse,
            options,
        )

    def by_intent(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByIntentResponse:
        """Returns outbound counts and latency percentiles grouped by entry-point intent, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = client.amb.stats.by_intent(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/intents",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByIntentResponse,
            options,
        )

    def by_message_kind(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByMessageKindResponse:
        """Returns outbound counts and latency percentiles grouped by message content kind, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = client.amb.stats.by_message_kind(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/message-kinds",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByMessageKindResponse,
            options,
        )

    def summary(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsSummary:
        """Returns one aggregate row of outbound Apple Messages for Business counts and latency percentiles (`p50`, `p95`, and `p99`) for the requested period. Counts are attributed to the time each message was accepted, so a send failure recorded today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.

        ```python
        result = client.amb.stats.summary(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/summary",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
                "compare": compare,
            },
            AMBStatsSummary,
            options,
        )

    def by_tag(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByTagResponse:
        """Returns outbound counts and latency percentiles grouped by tag (`name` or `name:value`), for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = client.amb.stats.by_tag(limit=2)
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/stats/tags",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByTagResponse,
            options,
        )


class AsyncAmbStatsBase(AsyncResource):
    async def by_business(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByBusinessResponse:
        """Returns outbound counts and latency percentiles grouped by business, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = await client.amb.stats.by_business(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/businesses",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByBusinessResponse,
            options,
        )

    async def by_category(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByCategoryResponse:
        """Returns outbound counts and latency percentiles grouped by message category, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). A send that names no category is grouped under an empty-string category. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = await client.amb.stats.by_category(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/categories",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByCategoryResponse,
            options,
        )

    async def daily(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsResponse:
        """Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every count in a row is attributed to the day its message was accepted, regardless of when a later event, such as a send failure, arrived.

        ```python
        result = await client.amb.stats.daily(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/daily",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
            },
            AMBStatsResponse,
            options,
        )

    async def by_error_code(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByErrorCodeResponse:
        """Returns outbound counts and latency percentiles grouped by failure reason, for the requested period. Rows are ranked by `send_failed + rejected` descending and capped at the requested `limit` (default 50, max 200). Only messages carrying a failure reason appear: a `bird:` code is usually a rejection (never charged, never attempted), an `apple:` code a send failure; use the summary for the period's full accepted total.

        ```python
        result = await client.amb.stats.by_error_code(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/error-codes",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByErrorCodeResponse,
            options,
        )

    async def by_group(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByGroupResponse:
        """Returns outbound counts and latency percentiles grouped by entry-point group, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Groups are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = await client.amb.stats.by_group(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/groups",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByGroupResponse,
            options,
        )

    async def hourly(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsResponse:
        """Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every count in a row is attributed to the hour its message was accepted, regardless of when a later event, such as a send failure, arrived. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.daily`.

        ```python
        result = await client.amb.stats.hourly(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/hourly",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
            },
            AMBStatsResponse,
            options,
        )

    async def by_intent(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByIntentResponse:
        """Returns outbound counts and latency percentiles grouped by entry-point intent, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = await client.amb.stats.by_intent(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/intents",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByIntentResponse,
            options,
        )

    async def by_message_kind(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByMessageKindResponse:
        """Returns outbound counts and latency percentiles grouped by message content kind, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.

        ```python
        result = await client.amb.stats.by_message_kind(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/message-kinds",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByMessageKindResponse,
            options,
        )

    async def summary(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        business_account_id: str | None = None,
        message_kind: str | None = None,
        intent: str | None = None,
        group: str | None = None,
        category: str | None = None,
        tag: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsSummary:
        """Returns one aggregate row of outbound Apple Messages for Business counts and latency percentiles (`p50`, `p95`, and `p99`) for the requested period. Counts are attributed to the time each message was accepted, so a send failure recorded today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.

        ```python
        result = await client.amb.stats.summary(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/summary",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "business_account_id": business_account_id,
                "message_kind": message_kind,
                "intent": intent,
                "group": group,
                "category": category,
                "tag": tag,
                "compare": compare,
            },
            AMBStatsSummary,
            options,
        )

    async def by_tag(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        limit: int | None = None,
        options: RequestOptions | None = None,
    ) -> AMBStatsByTagResponse:
        """Returns outbound counts and latency percentiles grouped by tag (`name` or `name:value`), for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.

        ```python
        result = await client.amb.stats.by_tag(limit=2)
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/stats/tags",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "limit": limit,
            },
            AMBStatsByTagResponse,
            options,
        )
