# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    AMBRoutingRule,
    AMBRoutingRuleCreate,
    AMBRoutingRuleList,
    AMBRoutingRuleUpdate,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit


class AmbRoutingRulesUpdateParams(TypedDict, total=False):
    """Params for ``client.amb.routing_rules.update``. Every key is optional."""

    business_account_id: str
    match_kind: str
    match_intent_id: str
    match_group_id: str
    queue: str
    precedence: int
    is_default: bool


class AmbRoutingRulesListParams(TypedDict, total=False):
    """Query params for ``client.amb.routing_rules.list``. Every key is optional."""

    business_account_id: str


class _AmbRoutingRulesCreateRequired(TypedDict):
    business_account_id: str
    match_kind: str
    queue: str


class AmbRoutingRulesCreateParams(_AmbRoutingRulesCreateRequired, total=False):
    """Params for ``client.amb.routing_rules.create``. ``business_account_id``, ``match_kind``, and ``queue`` are required."""

    match_intent_id: str | None
    match_group_id: str | None
    precedence: int
    is_default: bool


class AmbRoutingRules(Resource):
    def get(
        self,
        routing_rule_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Returns one routing rule by ID.

        ```python
        result = client.amb.routing_rules.get('arr_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}",
            {},
            AMBRoutingRule,
            options,
        )

    def update(
        self,
        routing_rule_id: str,
        *,
        business_account_id: str | None = None,
        match_kind: str | None = None,
        match_intent_id: str | None = None,
        match_group_id: str | None = None,
        queue: str | None = None,
        precedence: int | None = None,
        is_default: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Changes a routing rule's business, match, queue, precedence, or default status. The match changes as a unit: send `match_kind` with the intent and group ids it requires, as on create. Returns a `409` when the update would leave this rule as the default of a business that already has a different default rule.

        ```python
        result = client.amb.routing_rules.update('arr_01krdgeqcxet5s7t44vh8rt9mg', queue='sales', precedence=0, is_default=False)
        print(result)
        ```
        """
        body = to_wire(
            AMBRoutingRuleUpdate,
            {
                "business_account_id": business_account_id,
                "match_kind": match_kind,
                "match_intent_id": match_intent_id,
                "match_group_id": match_group_id,
                "queue": queue,
                "precedence": precedence,
                "is_default": is_default,
            },
        )
        return self._write(
            "PATCH",
            f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}",
            body,
            AMBRoutingRule,
            options,
        )

    def delete(
        self,
        routing_rule_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Deletes a routing rule. A conversation already routed by it keeps its queue; only newly created or reopened conversations stop matching it. Deleting a business's default rule leaves it with none, so unmatched conversations route to an empty queue until you create another.

        ```python
        result = client.amb.routing_rules.delete('arr_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        self._delete(f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}", options)

    def list(
        self,
        *,
        business_account_id: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRuleList:
        """Returns the workspace's Apple Messages for Business routing rules, highest precedence first. Rules run when a conversation is created, when a closed conversation reopens, and when a customer writes to a resolved conversation, matching its group and intent to a queue. A message without a group or intent routes on the conversation's stored values. Later messages while the conversation is open in the inbox retain its queue.

        ```python
        result = client.amb.routing_rules.list(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return self._get(
            "/v1/amb/routing-rules",
            {
                "business_account_id": business_account_id,
            },
            AMBRoutingRuleList,
            options,
        )

    def create(
        self,
        *,
        business_account_id: str,
        match_kind: str,
        match_intent_id: str | None | Omit = omit,
        match_group_id: str | None | Omit = omit,
        queue: str,
        precedence: int | None = None,
        is_default: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Creates a routing rule for one of your Apple Messages for Business brands. Set `is_default` to make it the rule that catches a conversation matching nothing else. A business can have only one default rule, and creating a second while one exists returns a `409`.

        ```python
        result = client.amb.routing_rules.create(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg', match_kind='intent', match_intent_id='support', queue='support', precedence=0, is_default=False, match_group_id=None)
        print(result)
        ```
        """
        _body: dict[str, Any] = {}
        _body["business_account_id"] = business_account_id
        _body["match_kind"] = match_kind
        if not isinstance(match_intent_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["match_intent_id"] = match_intent_id
        if not isinstance(match_group_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["match_group_id"] = match_group_id
        _body["queue"] = queue
        if precedence is not None:
            _body["precedence"] = precedence
        if is_default is not None:
            _body["is_default"] = is_default
        body = to_wire_exclude_unset(AMBRoutingRuleCreate, _body)
        return self._write(
            "POST",
            "/v1/amb/routing-rules",
            body,
            AMBRoutingRule,
            options,
        )


class AsyncAmbRoutingRules(AsyncResource):
    async def get(
        self,
        routing_rule_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Returns one routing rule by ID.

        ```python
        result = await client.amb.routing_rules.get('arr_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}",
            {},
            AMBRoutingRule,
            options,
        )

    async def update(
        self,
        routing_rule_id: str,
        *,
        business_account_id: str | None = None,
        match_kind: str | None = None,
        match_intent_id: str | None = None,
        match_group_id: str | None = None,
        queue: str | None = None,
        precedence: int | None = None,
        is_default: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Changes a routing rule's business, match, queue, precedence, or default status. The match changes as a unit: send `match_kind` with the intent and group ids it requires, as on create. Returns a `409` when the update would leave this rule as the default of a business that already has a different default rule.

        ```python
        result = await client.amb.routing_rules.update('arr_01krdgeqcxet5s7t44vh8rt9mg', queue='sales', precedence=0, is_default=False)
        print(result)
        ```
        """
        body = to_wire(
            AMBRoutingRuleUpdate,
            {
                "business_account_id": business_account_id,
                "match_kind": match_kind,
                "match_intent_id": match_intent_id,
                "match_group_id": match_group_id,
                "queue": queue,
                "precedence": precedence,
                "is_default": is_default,
            },
        )
        return await self._write(
            "PATCH",
            f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}",
            body,
            AMBRoutingRule,
            options,
        )

    async def delete(
        self,
        routing_rule_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Deletes a routing rule. A conversation already routed by it keeps its queue; only newly created or reopened conversations stop matching it. Deleting a business's default rule leaves it with none, so unmatched conversations route to an empty queue until you create another.

        ```python
        result = await client.amb.routing_rules.delete('arr_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        await self._delete(f"/v1/amb/routing-rules/{quote(routing_rule_id, safe='')}", options)

    async def list(
        self,
        *,
        business_account_id: str | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRuleList:
        """Returns the workspace's Apple Messages for Business routing rules, highest precedence first. Rules run when a conversation is created, when a closed conversation reopens, and when a customer writes to a resolved conversation, matching its group and intent to a queue. A message without a group or intent routes on the conversation's stored values. Later messages while the conversation is open in the inbox retain its queue.

        ```python
        result = await client.amb.routing_rules.list(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg')
        print(result)
        ```
        """
        return await self._get(
            "/v1/amb/routing-rules",
            {
                "business_account_id": business_account_id,
            },
            AMBRoutingRuleList,
            options,
        )

    async def create(
        self,
        *,
        business_account_id: str,
        match_kind: str,
        match_intent_id: str | None | Omit = omit,
        match_group_id: str | None | Omit = omit,
        queue: str,
        precedence: int | None = None,
        is_default: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AMBRoutingRule:
        """Creates a routing rule for one of your Apple Messages for Business brands. Set `is_default` to make it the rule that catches a conversation matching nothing else. A business can have only one default rule, and creating a second while one exists returns a `409`.

        ```python
        result = await client.amb.routing_rules.create(business_account_id='abz_01krdgeqcxet5s7t44vh8rt9mg', match_kind='intent', match_intent_id='support', queue='support', precedence=0, is_default=False, match_group_id=None)
        print(result)
        ```
        """
        _body: dict[str, Any] = {}
        _body["business_account_id"] = business_account_id
        _body["match_kind"] = match_kind
        if not isinstance(match_intent_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["match_intent_id"] = match_intent_id
        if not isinstance(match_group_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["match_group_id"] = match_group_id
        _body["queue"] = queue
        if precedence is not None:
            _body["precedence"] = precedence
        if is_default is not None:
            _body["is_default"] = is_default
        body = to_wire_exclude_unset(AMBRoutingRuleCreate, _body)
        return await self._write(
            "POST",
            "/v1/amb/routing-rules",
            body,
            AMBRoutingRule,
            options,
        )
