# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    Audience,
    AudienceContactsAddRequest,
    AudienceContactsRemoveRequest,
    AudienceCreateRequest,
    AudienceMember,
    AudienceUpdateRequest,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class AudienceListParams(TypedDict, total=False):
    """Query params for ``client.audiences.list``. Every key is optional."""

    q: str
    limit: int
    starting_after: str
    ending_before: str


class _AudienceCreateRequired(TypedDict):
    name: str


class AudienceCreateParams(_AudienceCreateRequired, total=False):
    """Params for ``client.audiences.create``. ``name`` is required."""

    description: str
    type: str


class AudienceUpdateParams(TypedDict, total=False):
    """Params for ``client.audiences.update``. Every key is optional."""

    name: str
    description: str | None


class AudienceListContactsParams(TypedDict, total=False):
    """Query params for ``client.audiences.list_contacts``. Every key is optional."""

    q: str
    limit: int
    starting_after: str
    ending_before: str


class _AudienceAddContactsRequired(TypedDict):
    contact_ids: Sequence[str]


class AudienceAddContactsParams(_AudienceAddContactsRequired, total=False):
    """Params for ``client.audiences.add_contacts``. ``contact_ids`` is required."""


class _AudienceRemoveContactsRequired(TypedDict):
    contact_ids: Sequence[str]


class AudienceRemoveContactsParams(_AudienceRemoveContactsRequired, total=False):
    """Params for ``client.audiences.remove_contacts``. ``contact_ids`` is required."""


class Audiences(Resource):
    def list(
        self,
        *,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Audience]:
        """List the workspace's audiences as a cursor page, newest first. Filter by name substring with `q`.

        ```python
        for audience in client.audiences.list():
            print(audience.id, audience.name)
        ```
        """
        query = {
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/audiences", query, Audience, options)

    def get(
        self,
        audience_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Get a single audience by ID: name, description, and type. Members are listed separately with `audiences.list_contacts`.

        ```python
        audience = client.audiences.get("adn_01krdgeqcxet5s7t44vh8rt9mg")
        print(audience.name)
        ```
        """
        return self._get(
            f"/v1/audiences/{quote(audience_id, safe='')}",
            {},
            Audience,
            options,
        )

    def create(
        self,
        *,
        name: str,
        description: str | None = None,
        type: str | None = None,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Create an audience in the workspace. New audiences start empty; add contacts with `audiences.add_contacts` or `contacts.batch`. Only static audiences can be created today.

        ```python
        audience = client.audiences.create(name="Newsletter subscribers")
        print(audience.id, audience.name)
        ```
        """
        body = to_wire(
            AudienceCreateRequest,
            {
                "name": name,
                "description": description,
                "type": type,
            },
        )
        return self._write(
            "POST",
            "/v1/audiences",
            body,
            Audience,
            options,
        )

    def update(
        self,
        audience_id: str,
        *,
        name: str | None = None,
        description: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Update an audience's name or description. Omitted fields are unchanged; a `null` description clears it.

        ```python
        audience = client.audiences.update("adn_01krdgeqcxet5s7t44vh8rt9mg", name="Renamed")
        print(audience.name)
        ```
        """
        _body: dict[str, Any] = {}
        if name is not None:
            _body["name"] = name
        if not isinstance(description, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["description"] = description
        body = to_wire_exclude_unset(AudienceUpdateRequest, _body)
        return self._write(
            "PATCH",
            f"/v1/audiences/{quote(audience_id, safe='')}",
            body,
            Audience,
            options,
        )

    def delete(
        self,
        audience_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete an audience and its memberships; contacts themselves are not deleted. Fails while a broadcast targeting the audience is scheduled, accepted, sending, or canceling.

        ```python
        client.audiences.delete("adn_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/audiences/{quote(audience_id, safe='')}", options)

    def list_contacts(
        self,
        audience_id: str,
        *,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[AudienceMember]:
        """List the contacts in a static audience by ID, as a cursor page ordered by when each contact joined (most recent first). Each entry pairs the contact with its join time.

        ```python
        for member in client.audiences.list_contacts("adn_01krdgeqcxet5s7t44vh8rt9mg"):
            print(member.contact.email, member.joined_at)
        ```
        """
        query = {
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, f"/v1/audiences/{quote(audience_id, safe='')}/contacts", query, AudienceMember, options)

    def add_contacts(
        self,
        audience_id: str,
        *,
        contact_ids: Sequence[str],
        options: RequestOptions | None = None,
    ) -> None:
        """Add up to 1,000 existing contacts to a static audience by ID. Fails entirely if any contact ID does not exist. To add contacts you have not created yet, use `contacts.batch` with `audience_ids` instead: it matches or creates each contact by email address and assigns it to the audience in one call.

        ```python
        client.audiences.add_contacts(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", contact_ids=["con_01krdgeqcxet5s7t44vh8rt9mg"],
        )
        ```
        """
        body = to_wire(
            AudienceContactsAddRequest,
            {
                "contact_ids": contact_ids,
            },
        )
        self._write_none(
            "POST",
            f"/v1/audiences/{quote(audience_id, safe='')}/contacts",
            body,
            options,
        )

    def remove_contacts(
        self,
        audience_id: str,
        *,
        contact_ids: Sequence[str],
        options: RequestOptions | None = None,
    ) -> None:
        """Remove up to 1,000 contacts from a static audience by ID. Fails entirely if any contact ID does not exist; contacts are not deleted.

        ```python
        client.audiences.remove_contacts(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", contact_ids=["con_01krdgeqcxet5s7t44vh8rt9mg"],
        )
        ```
        """
        body = to_wire(
            AudienceContactsRemoveRequest,
            {
                "contact_ids": contact_ids,
            },
        )
        self._write_none(
            "POST",
            f"/v1/audiences/{quote(audience_id, safe='')}/contacts/remove",
            body,
            options,
        )

    def remove_contact(
        self,
        audience_id: str,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one contact's membership from an audience. The contact itself is not deleted and stays a member of any other audiences.

        ```python
        client.audiences.remove_contact(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", "con_01krdgeqcxet5s7t44vh8rt9mg",
        )
        ```
        """
        self._delete(f"/v1/audiences/{quote(audience_id, safe='')}/contacts/{quote(contact_id, safe='')}", options)


class AsyncAudiences(AsyncResource):
    def list(
        self,
        *,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Audience]:
        """List the workspace's audiences as a cursor page, newest first. Filter by name substring with `q`.

        ```python
        async for audience in client.audiences.list():
            print(audience.id, audience.name)
        ```
        """
        query = {
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/audiences", query, Audience, options)

    async def get(
        self,
        audience_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Get a single audience by ID: name, description, and type. Members are listed separately with `audiences.list_contacts`.

        ```python
        audience = await client.audiences.get("adn_01krdgeqcxet5s7t44vh8rt9mg")
        print(audience.name)
        ```
        """
        return await self._get(
            f"/v1/audiences/{quote(audience_id, safe='')}",
            {},
            Audience,
            options,
        )

    async def create(
        self,
        *,
        name: str,
        description: str | None = None,
        type: str | None = None,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Create an audience in the workspace. New audiences start empty; add contacts with `audiences.add_contacts` or `contacts.batch`. Only static audiences can be created today.

        ```python
        audience = await client.audiences.create(name="Newsletter subscribers")
        print(audience.id, audience.name)
        ```
        """
        body = to_wire(
            AudienceCreateRequest,
            {
                "name": name,
                "description": description,
                "type": type,
            },
        )
        return await self._write(
            "POST",
            "/v1/audiences",
            body,
            Audience,
            options,
        )

    async def update(
        self,
        audience_id: str,
        *,
        name: str | None = None,
        description: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> Audience:
        """Update an audience's name or description. Omitted fields are unchanged; a `null` description clears it.

        ```python
        audience = await client.audiences.update("adn_01krdgeqcxet5s7t44vh8rt9mg", name="Renamed")
        print(audience.name)
        ```
        """
        _body: dict[str, Any] = {}
        if name is not None:
            _body["name"] = name
        if not isinstance(description, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["description"] = description
        body = to_wire_exclude_unset(AudienceUpdateRequest, _body)
        return await self._write(
            "PATCH",
            f"/v1/audiences/{quote(audience_id, safe='')}",
            body,
            Audience,
            options,
        )

    async def delete(
        self,
        audience_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete an audience and its memberships; contacts themselves are not deleted. Fails while a broadcast targeting the audience is scheduled, accepted, sending, or canceling.

        ```python
        await client.audiences.delete("adn_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/audiences/{quote(audience_id, safe='')}", options)

    def list_contacts(
        self,
        audience_id: str,
        *,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[AudienceMember]:
        """List the contacts in a static audience by ID, as a cursor page ordered by when each contact joined (most recent first). Each entry pairs the contact with its join time.

        ```python
        async for member in client.audiences.list_contacts("adn_01krdgeqcxet5s7t44vh8rt9mg"):
            print(member.contact.email, member.joined_at)
        ```
        """
        query = {
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, f"/v1/audiences/{quote(audience_id, safe='')}/contacts", query, AudienceMember, options)

    async def add_contacts(
        self,
        audience_id: str,
        *,
        contact_ids: Sequence[str],
        options: RequestOptions | None = None,
    ) -> None:
        """Add up to 1,000 existing contacts to a static audience by ID. Fails entirely if any contact ID does not exist. To add contacts you have not created yet, use `contacts.batch` with `audience_ids` instead: it matches or creates each contact by email address and assigns it to the audience in one call.

        ```python
        await client.audiences.add_contacts(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", contact_ids=["con_01krdgeqcxet5s7t44vh8rt9mg"],
        )
        ```
        """
        body = to_wire(
            AudienceContactsAddRequest,
            {
                "contact_ids": contact_ids,
            },
        )
        await self._write_none(
            "POST",
            f"/v1/audiences/{quote(audience_id, safe='')}/contacts",
            body,
            options,
        )

    async def remove_contacts(
        self,
        audience_id: str,
        *,
        contact_ids: Sequence[str],
        options: RequestOptions | None = None,
    ) -> None:
        """Remove up to 1,000 contacts from a static audience by ID. Fails entirely if any contact ID does not exist; contacts are not deleted.

        ```python
        await client.audiences.remove_contacts(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", contact_ids=["con_01krdgeqcxet5s7t44vh8rt9mg"],
        )
        ```
        """
        body = to_wire(
            AudienceContactsRemoveRequest,
            {
                "contact_ids": contact_ids,
            },
        )
        await self._write_none(
            "POST",
            f"/v1/audiences/{quote(audience_id, safe='')}/contacts/remove",
            body,
            options,
        )

    async def remove_contact(
        self,
        audience_id: str,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one contact's membership from an audience. The contact itself is not deleted and stays a member of any other audiences.

        ```python
        await client.audiences.remove_contact(
            "adn_01krdgeqcxet5s7t44vh8rt9mg", "con_01krdgeqcxet5s7t44vh8rt9mg",
        )
        ```
        """
        await self._delete(f"/v1/audiences/{quote(audience_id, safe='')}/contacts/{quote(contact_id, safe='')}", options)
