# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EmailBroadcast,
    EmailBroadcastClickedLinkList,
    EmailBroadcastCounts,
    EmailBroadcastSendQuota,
    EmailEvent,
    EmailRecipient,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class BroadcastsListParams(TypedDict, total=False):
    """Query params for ``client.broadcasts.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    status: Sequence[str]
    audience_id: str
    tag: str
    q: str
    created_after: str
    created_before: str


class BroadcastsListEventsParams(TypedDict, total=False):
    """Query params for ``client.broadcasts.list_events``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    type: str


class BroadcastsListRecipientsParams(TypedDict, total=False):
    """Query params for ``client.broadcasts.list_recipients``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    to: str


class BroadcastsBase(Resource):
    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        status: Sequence[str] | None = None,
        audience_id: str | None = None,
        tag: str | None = None,
        q: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailBroadcast]:
        """List broadcasts in the workspace, newest first. Filter by lifecycle `status`, `audience_id`, or `tag`, search tag names/values with `q`, or narrow to a window with `created_after`/`created_before`. Use `broadcasts.get` for full detail on one broadcast.

        ```python
        for broadcast in client.broadcasts.list(status=["sent"]):
            print(broadcast.id, broadcast.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "status": status,
            "audience_id": audience_id,
            "tag": tag,
            "q": q,
            "created_after": created_after,
            "created_before": created_before,
        }
        return SyncPage(self._client, "/v1/email/broadcasts", query, EmailBroadcast, options)

    def get(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcast:
        """Fetch one broadcast by its `broadcast_id`, with its audience reference and counters. For the full recipient list use `broadcasts.list_recipients`, and for the delivery timeline use `broadcasts.list_events`.

        ```python
        broadcast = client.broadcasts.get("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(broadcast.status, broadcast.sent_count, broadcast.delivered_count)
        ```
        """
        return self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}",
            {},
            EmailBroadcast,
            options,
        )

    def delete(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently delete a draft broadcast. Only a draft can be deleted. To stop a scheduled or sending broadcast, use `broadcasts.cancel` instead.

        ```python
        client.broadcasts.delete("eb_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}", options)

    def cancel(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcast:
        """Cancel a scheduled, accepted, or sending broadcast. This stops every delivery that has not gone out yet. Recipients already dispatched are not recalled. Calling this again on a broadcast already canceling or canceled returns its current state rather than an error. A draft cannot be canceled, because it was never sent. Delete it with `broadcasts.delete` instead.

        ```python
        broadcast = client.broadcasts.cancel("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(broadcast.status)
        ```
        """
        return self._action(
            "POST",
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/cancel",
            EmailBroadcast,
            options,
        )

    def list_events(
        self,
        broadcast_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        type: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailEvent]:
        """List the per-recipient delivery timeline for a broadcast (sends, opens, clicks, bounces, and so on), oldest first, as a cursor page. Filter by `type`, for example `email.bounced` or `email.opened`.

        ```python
        for event in client.broadcasts.list_events(
            "eb_01krdgeqcxet5s7t44vh8rt9mg", type="email.bounced"
        ):
            print(event.type, event.recipient_id, event.bounce_type)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "type": type,
        }
        return SyncPage(self._client, f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/events", query, EmailEvent, options)

    def list_recipients(
        self,
        broadcast_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        to: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailRecipient]:
        """List the recipients resolved for a broadcast with their per-recipient delivery state, paginated. It shows who a broadcast reached and how far each one got. The list is empty until the broadcast starts sending. Pass `to` to look up one address instead of paging the whole set.

        ```python
        for recipient in client.broadcasts.list_recipients("eb_01krdgeqcxet5s7t44vh8rt9mg"):
            print(recipient.recipient, recipient.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "to": to,
        }
        return SyncPage(self._client, f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/recipients", query, EmailRecipient, options)

    def counts(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastCounts:
        """Preview how many contacts a broadcast can reach before sending. The `total` value includes every contact in the audience. The `addressable` value counts contacts with an email address. The `sendable` value counts contacts that are not suppressed for the broadcast's category and can receive the broadcast. These describe the audience, not delivery, and sending does not change them: to find out what happened to a broadcast that has sent, read its recipients or its events. The broadcast must already have an audience selected.

        ```python
        counts = client.broadcasts.counts("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(counts.total, counts.addressable, counts.sendable)
        ```
        """
        return self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/counts",
            {},
            EmailBroadcastCounts,
            options,
        )

    def list_clicked_links(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastClickedLinkList:
        """List the destination URLs a broadcast's recipients clicked, each with its exact click count, distinct-recipient count, and the link's own name (when the message named it). Grouped over every click event the broadcast has, not a sample; `data` is capped at the 100 most-clicked URLs and `total` is the uncapped count of distinct URLs clicked.

        ```python
        links = client.broadcasts.list_clicked_links("eb_01krdgeqcxet5s7t44vh8rt9mg")
        for link in links.data:
            print(link.url, link.click_count, link.recipient_count)
        ```
        """
        return self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/clicked-links",
            {},
            EmailBroadcastClickedLinkList,
            options,
        )

    def send_quota(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastSendQuota:
        """Check how much of a broadcast will actually send before sending it: `recipients` is how many contacts it would reach now, `allowed` is how many of those the organization's email send allowance covers, and `limited_by` names the allowance that stops the rest. The broadcast must already have an audience selected.

        ```python
        quota = client.broadcasts.send_quota("eb_01krdgeqcxet5s7t44vh8rt9mg")
        if quota.allowed < quota.recipients:
            print(quota.limited_by, "allowance covers only", quota.allowed)
        ```
        """
        return self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/send-quota",
            {},
            EmailBroadcastSendQuota,
            options,
        )


class AsyncBroadcastsBase(AsyncResource):
    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        status: Sequence[str] | None = None,
        audience_id: str | None = None,
        tag: str | None = None,
        q: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailBroadcast]:
        """List broadcasts in the workspace, newest first. Filter by lifecycle `status`, `audience_id`, or `tag`, search tag names/values with `q`, or narrow to a window with `created_after`/`created_before`. Use `broadcasts.get` for full detail on one broadcast.

        ```python
        async for broadcast in client.broadcasts.list(status=["sent"]):
            print(broadcast.id, broadcast.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "status": status,
            "audience_id": audience_id,
            "tag": tag,
            "q": q,
            "created_after": created_after,
            "created_before": created_before,
        }
        return AsyncPage(self._client, "/v1/email/broadcasts", query, EmailBroadcast, options)

    async def get(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcast:
        """Fetch one broadcast by its `broadcast_id`, with its audience reference and counters. For the full recipient list use `broadcasts.list_recipients`, and for the delivery timeline use `broadcasts.list_events`.

        ```python
        broadcast = await client.broadcasts.get("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(broadcast.status, broadcast.sent_count, broadcast.delivered_count)
        ```
        """
        return await self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}",
            {},
            EmailBroadcast,
            options,
        )

    async def delete(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently delete a draft broadcast. Only a draft can be deleted. To stop a scheduled or sending broadcast, use `broadcasts.cancel` instead.

        ```python
        await client.broadcasts.delete("eb_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}", options)

    async def cancel(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcast:
        """Cancel a scheduled, accepted, or sending broadcast. This stops every delivery that has not gone out yet. Recipients already dispatched are not recalled. Calling this again on a broadcast already canceling or canceled returns its current state rather than an error. A draft cannot be canceled, because it was never sent. Delete it with `broadcasts.delete` instead.

        ```python
        broadcast = await client.broadcasts.cancel("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(broadcast.status)
        ```
        """
        return await self._action(
            "POST",
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/cancel",
            EmailBroadcast,
            options,
        )

    def list_events(
        self,
        broadcast_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        type: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailEvent]:
        """List the per-recipient delivery timeline for a broadcast (sends, opens, clicks, bounces, and so on), oldest first, as a cursor page. Filter by `type`, for example `email.bounced` or `email.opened`.

        ```python
        async for event in client.broadcasts.list_events(
            "eb_01krdgeqcxet5s7t44vh8rt9mg", type="email.bounced"
        ):
            print(event.type, event.recipient_id, event.bounce_type)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "type": type,
        }
        return AsyncPage(self._client, f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/events", query, EmailEvent, options)

    def list_recipients(
        self,
        broadcast_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        to: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailRecipient]:
        """List the recipients resolved for a broadcast with their per-recipient delivery state, paginated. It shows who a broadcast reached and how far each one got. The list is empty until the broadcast starts sending. Pass `to` to look up one address instead of paging the whole set.

        ```python
        async for recipient in client.broadcasts.list_recipients("eb_01krdgeqcxet5s7t44vh8rt9mg"):
            print(recipient.recipient, recipient.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "to": to,
        }
        return AsyncPage(self._client, f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/recipients", query, EmailRecipient, options)

    async def counts(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastCounts:
        """Preview how many contacts a broadcast can reach before sending. The `total` value includes every contact in the audience. The `addressable` value counts contacts with an email address. The `sendable` value counts contacts that are not suppressed for the broadcast's category and can receive the broadcast. These describe the audience, not delivery, and sending does not change them: to find out what happened to a broadcast that has sent, read its recipients or its events. The broadcast must already have an audience selected.

        ```python
        counts = await client.broadcasts.counts("eb_01krdgeqcxet5s7t44vh8rt9mg")
        print(counts.total, counts.addressable, counts.sendable)
        ```
        """
        return await self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/counts",
            {},
            EmailBroadcastCounts,
            options,
        )

    async def list_clicked_links(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastClickedLinkList:
        """List the destination URLs a broadcast's recipients clicked, each with its exact click count, distinct-recipient count, and the link's own name (when the message named it). Grouped over every click event the broadcast has, not a sample; `data` is capped at the 100 most-clicked URLs and `total` is the uncapped count of distinct URLs clicked.

        ```python
        links = await client.broadcasts.list_clicked_links("eb_01krdgeqcxet5s7t44vh8rt9mg")
        for link in links.data:
            print(link.url, link.click_count, link.recipient_count)
        ```
        """
        return await self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/clicked-links",
            {},
            EmailBroadcastClickedLinkList,
            options,
        )

    async def send_quota(
        self,
        broadcast_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailBroadcastSendQuota:
        """Check how much of a broadcast will actually send before sending it: `recipients` is how many contacts it would reach now, `allowed` is how many of those the organization's email send allowance covers, and `limited_by` names the allowance that stops the rest. The broadcast must already have an audience selected.

        ```python
        quota = await client.broadcasts.send_quota("eb_01krdgeqcxet5s7t44vh8rt9mg")
        if quota.allowed < quota.recipients:
            print(quota.limited_by, "allowance covers only", quota.allowed)
        ```
        """
        return await self._get(
            f"/v1/email/broadcasts/{quote(broadcast_id, safe='')}/send-quota",
            {},
            EmailBroadcastSendQuota,
            options,
        )
