# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from bird._generated import (
    Contact,
    ContactCreateRequest,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class ContactsBase(Resource):
    def list(
        self,
        *,
        email: str | None = None,
        external_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Contact]:
        """List the workspace's contacts as a cursor page, newest first. Look one up by exact email or external_id, or search by email substring.

        ```python
        for contact in client.contacts.list(q="acme.com"):
            print(contact.id, contact.email)
        ```
        """
        query = {
            "email": email,
            "external_id": external_id,
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/contacts", query, Contact, options)

    def get(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email or external_id with `contacts.list`.

        ```python
        contact = client.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg")
        print(contact.email)
        ```
        """
        return self._get(
            f"/v1/contacts/{contact_id}",
            {},
            Contact,
            options,
        )

    def create(
        self,
        *,
        email: str,
        first_name: str | None = None,
        last_name: str | None = None,
        external_id: str | None = None,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Create a contact by email address in the workspace. Fails with a conflict if the email or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.

        ```python
        contact = client.contacts.create(email="jane@acme.com", first_name="Jane")
        print(contact.id, contact.email)
        ```
        """
        body = to_wire(
            ContactCreateRequest,
            {
                "email": email,
                "first_name": first_name,
                "last_name": last_name,
                "external_id": external_id,
                "data": data,
            },
        )
        return self._write(
            "POST",
            "/v1/contacts",
            body,
            Contact,
            options,
        )

    def delete(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.

        ```python
        client.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/contacts/{contact_id}", options)


class AsyncContactsBase(AsyncResource):
    def list(
        self,
        *,
        email: str | None = None,
        external_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Contact]:
        """List the workspace's contacts as a cursor page, newest first. Look one up by exact email or external_id, or search by email substring.

        ```python
        async for contact in client.contacts.list(q="acme.com"):
            print(contact.id, contact.email)
        ```
        """
        query = {
            "email": email,
            "external_id": external_id,
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/contacts", query, Contact, options)

    async def get(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email or external_id with `contacts.list`.

        ```python
        contact = await client.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg")
        print(contact.email)
        ```
        """
        return await self._get(
            f"/v1/contacts/{contact_id}",
            {},
            Contact,
            options,
        )

    async def create(
        self,
        *,
        email: str,
        first_name: str | None = None,
        last_name: str | None = None,
        external_id: str | None = None,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Create a contact by email address in the workspace. Fails with a conflict if the email or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.

        ```python
        contact = await client.contacts.create(email="jane@acme.com", first_name="Jane")
        print(contact.id, contact.email)
        ```
        """
        body = to_wire(
            ContactCreateRequest,
            {
                "email": email,
                "first_name": first_name,
                "last_name": last_name,
                "external_id": external_id,
                "data": data,
            },
        )
        return await self._write(
            "POST",
            "/v1/contacts",
            body,
            Contact,
            options,
        )

    async def delete(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.

        ```python
        await client.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/contacts/{contact_id}", options)
