# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    Preference,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class ContactsPreferencesListParams(TypedDict, total=False):
    """Query params for ``client.contacts.preferences.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str


class ContactsPreferences(Resource):
    def list(
        self,
        contact_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Preference]:
        """List the recorded messaging preferences for a contact's own handles (their email address and phone number) across every channel, as a cursor page.

        ```python
        for preference in client.contacts.preferences.list("con_01krdgeqcxet5s7t44vh8rt9mg"):
            print(preference.channel, preference.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, f"/v1/contacts/{quote(contact_id, safe='')}/preferences", query, Preference, options)


class AsyncContactsPreferences(AsyncResource):
    def list(
        self,
        contact_id: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Preference]:
        """List the recorded messaging preferences for a contact's own handles (their email address and phone number) across every channel, as a cursor page.

        ```python
        async for preference in client.contacts.preferences.list("con_01krdgeqcxet5s7t44vh8rt9mg"):
            print(preference.channel, preference.status)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, f"/v1/contacts/{quote(contact_id, safe='')}/preferences", query, Preference, options)
