# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict

from bird._generated import (
    Contact,
    ContactCreateRequest,
    ContactUpdateRequest,
    ContactUpsertRequest,
    ContactUpsertResult,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class ContactListParams(TypedDict, total=False):
    """Query params for ``client.contacts.list``. Every key is optional."""

    email: str
    phone: str
    external_id: str
    q: str
    limit: int
    starting_after: str
    ending_before: str
    include_total: bool


class ContactCreateParams(TypedDict, total=False):
    """Params for ``client.contacts.create``. Every key is optional."""

    email: str
    phone: str
    first_name: str
    last_name: str
    external_id: str
    data: Mapping[str, Any]


class ContactUpdateParams(TypedDict, total=False):
    """Params for ``client.contacts.update``. Every key is optional."""

    email: str | None
    phone: str | None
    first_name: str | None
    last_name: str | None
    external_id: str | None
    data: Mapping[str, Any]


class _ContactBatchRequired(TypedDict):
    contacts: Sequence[ContactCreateParams]


class ContactBatchParams(_ContactBatchRequired, total=False):
    """Params for ``client.contacts.batch``. ``contacts`` is required."""

    audience_ids: Sequence[str]
    match_on: str
    data_mode: str


class Contacts(Resource):
    def list(
        self,
        *,
        email: str | None = None,
        phone: str | None = None,
        external_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Contact]:
        """List the workspace's contacts as a cursor page, newest first. Look one up by exact email, phone, or external_id, or search by email, name, or phone substring. Pass include_total for a total count.

        ```python
        for contact in client.contacts.list(q="acme.com"):
            print(contact.id, contact.email)
        ```
        """
        query = {
            "email": email,
            "phone": phone,
            "external_id": external_id,
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return SyncPage(self._client, "/v1/contacts", query, Contact, options)

    def get(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email, phone, or external_id with `contacts.list`.

        ```python
        contact = client.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg")
        print(contact.email)
        ```
        """
        return self._get(
            f"/v1/contacts/{contact_id}",
            {},
            Contact,
            options,
        )

    def create(
        self,
        *,
        email: str | None = None,
        phone: str | None = None,
        first_name: str | None = None,
        last_name: str | None = None,
        external_id: str | None = None,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Create a contact identified by an email address, an E.164 phone number, or both. Fails with a conflict if the email, phone, or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.

        ```python
        contact = client.contacts.create(email="jane@acme.com", first_name="Jane")
        print(contact.id, contact.email)
        ```
        """
        body = to_wire(
            ContactCreateRequest,
            {
                "email": email,
                "phone": phone,
                "first_name": first_name,
                "last_name": last_name,
                "external_id": external_id,
                "data": data,
            },
        )
        return self._write(
            "POST",
            "/v1/contacts",
            body,
            Contact,
            options,
        )

    def update(
        self,
        contact_id: str,
        *,
        email: str | None | Omit = omit,
        phone: str | None | Omit = omit,
        first_name: str | None | Omit = omit,
        last_name: str | None | Omit = omit,
        external_id: str | None | Omit = omit,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Update a contact's name, external_id, email, phone, or custom data. Only supplied fields change; custom data keys are merged, with null removing a key. A contact keeps at least one identifier: clearing both email and phone is rejected.

        ```python
        contact = client.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", first_name="Jane")
        print(contact.first_name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(email, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["email"] = email
        if not isinstance(phone, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["phone"] = phone
        if not isinstance(first_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["first_name"] = first_name
        if not isinstance(last_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["last_name"] = last_name
        if not isinstance(external_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["external_id"] = external_id
        if data is not None:
            _body["data"] = data
        body = to_wire_exclude_unset(ContactUpdateRequest, _body)
        return self._write(
            "PATCH",
            f"/v1/contacts/{contact_id}",
            body,
            Contact,
            options,
        )

    def delete(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.

        ```python
        client.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/contacts/{contact_id}", options)

    def batch(
        self,
        *,
        contacts: Sequence[ContactCreateParams],
        audience_ids: Sequence[str] | None = None,
        match_on: str | None = None,
        data_mode: str | None = None,
        options: RequestOptions | None = None,
    ) -> ContactUpsertResult:
        """Create or update up to 1,000 contacts in one request, each entry matched automatically against every identifier it supplies (email, phone, external_id) or, with match_on, by that one field only, and optionally add them all to one or more audiences. Per-contact results are returned in submission order.

        ```python
        result = client.contacts.batch(contacts=[{"email": "jane@acme.com", "first_name": "Jane"}])
        for item in result.data:
            print(item.entry.email, item.status)
        ```
        """
        body = to_wire(
            ContactUpsertRequest,
            {
                "contacts": contacts,
                "audience_ids": audience_ids,
                "match_on": match_on,
                "data_mode": data_mode,
            },
        )
        return self._write(
            "POST",
            "/v1/contacts/batch",
            body,
            ContactUpsertResult,
            options,
        )


class AsyncContacts(AsyncResource):
    def list(
        self,
        *,
        email: str | None = None,
        phone: str | None = None,
        external_id: str | None = None,
        q: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Contact]:
        """List the workspace's contacts as a cursor page, newest first. Look one up by exact email, phone, or external_id, or search by email, name, or phone substring. Pass include_total for a total count.

        ```python
        async for contact in client.contacts.list(q="acme.com"):
            print(contact.id, contact.email)
        ```
        """
        query = {
            "email": email,
            "phone": phone,
            "external_id": external_id,
            "q": q,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return AsyncPage(self._client, "/v1/contacts", query, Contact, options)

    async def get(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email, phone, or external_id with `contacts.list`.

        ```python
        contact = await client.contacts.get("con_01krdgeqcxet5s7t44vh8rt9mg")
        print(contact.email)
        ```
        """
        return await self._get(
            f"/v1/contacts/{contact_id}",
            {},
            Contact,
            options,
        )

    async def create(
        self,
        *,
        email: str | None = None,
        phone: str | None = None,
        first_name: str | None = None,
        last_name: str | None = None,
        external_id: str | None = None,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Create a contact identified by an email address, an E.164 phone number, or both. Fails with a conflict if the email, phone, or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.

        ```python
        contact = await client.contacts.create(email="jane@acme.com", first_name="Jane")
        print(contact.id, contact.email)
        ```
        """
        body = to_wire(
            ContactCreateRequest,
            {
                "email": email,
                "phone": phone,
                "first_name": first_name,
                "last_name": last_name,
                "external_id": external_id,
                "data": data,
            },
        )
        return await self._write(
            "POST",
            "/v1/contacts",
            body,
            Contact,
            options,
        )

    async def update(
        self,
        contact_id: str,
        *,
        email: str | None | Omit = omit,
        phone: str | None | Omit = omit,
        first_name: str | None | Omit = omit,
        last_name: str | None | Omit = omit,
        external_id: str | None | Omit = omit,
        data: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Contact:
        """Update a contact's name, external_id, email, phone, or custom data. Only supplied fields change; custom data keys are merged, with null removing a key. A contact keeps at least one identifier: clearing both email and phone is rejected.

        ```python
        contact = await client.contacts.update("con_01krdgeqcxet5s7t44vh8rt9mg", first_name="Jane")
        print(contact.first_name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(email, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["email"] = email
        if not isinstance(phone, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["phone"] = phone
        if not isinstance(first_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["first_name"] = first_name
        if not isinstance(last_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["last_name"] = last_name
        if not isinstance(external_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["external_id"] = external_id
        if data is not None:
            _body["data"] = data
        body = to_wire_exclude_unset(ContactUpdateRequest, _body)
        return await self._write(
            "PATCH",
            f"/v1/contacts/{contact_id}",
            body,
            Contact,
            options,
        )

    async def delete(
        self,
        contact_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.

        ```python
        await client.contacts.delete("con_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/contacts/{contact_id}", options)

    async def batch(
        self,
        *,
        contacts: Sequence[ContactCreateParams],
        audience_ids: Sequence[str] | None = None,
        match_on: str | None = None,
        data_mode: str | None = None,
        options: RequestOptions | None = None,
    ) -> ContactUpsertResult:
        """Create or update up to 1,000 contacts in one request, each entry matched automatically against every identifier it supplies (email, phone, external_id) or, with match_on, by that one field only, and optionally add them all to one or more audiences. Per-contact results are returned in submission order.

        ```python
        result = await client.contacts.batch(contacts=[{"email": "jane@acme.com", "first_name": "Jane"}])
        for item in result.data:
            print(item.entry.email, item.status)
        ```
        """
        body = to_wire(
            ContactUpsertRequest,
            {
                "contacts": contacts,
                "audience_ids": audience_ids,
                "match_on": match_on,
                "data_mode": data_mode,
            },
        )
        return await self._write(
            "POST",
            "/v1/contacts/batch",
            body,
            ContactUpsertResult,
            options,
        )
