# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    Domain,
    DomainCreate,
    DomainUpdate,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class _DomainReturnPathConfigRequired(TypedDict):
    name: str


class DomainReturnPathConfig(_DomainReturnPathConfigRequired, total=False):
    pass


class _DomainTrackingConfigRequired(TypedDict):
    name: str


class DomainTrackingConfig(_DomainTrackingConfigRequired, total=False):
    pass


class DomainDKIMConfig(TypedDict, total=False):
    mode: str


class DomainSettings(TypedDict, total=False):
    click_tracking: bool
    open_tracking: bool


class _DomainInboundConfigRequired(TypedDict):
    enabled: bool


class DomainInboundConfig(_DomainInboundConfigRequired, total=False):
    pass


class DomainListParams(TypedDict, total=False):
    """Query params for ``client.domains.list``. Every key is optional."""

    name: str
    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str
    include_total: bool


class _DomainCreateRequired(TypedDict):
    domain: str


class DomainCreateParams(_DomainCreateRequired, total=False):
    """Params for ``client.domains.create``. ``domain`` is required."""

    return_path: DomainReturnPathConfig
    tracking: DomainTrackingConfig
    dkim: DomainDKIMConfig
    settings: DomainSettings


class DomainUpdateParams(TypedDict, total=False):
    """Params for ``client.domains.update``. Every key is optional."""

    settings: DomainSettings
    return_path: DomainReturnPathConfig
    tracking: DomainTrackingConfig | None
    dkim: DomainDKIMConfig
    inbound: DomainInboundConfig


class Domains(Resource):
    def list(
        self,
        *,
        name: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Domain]:
        """List the workspace's sending domains with their verification status, as a cursor page.

        ```python
        for domain in client.domains.list():
            print(domain.id, domain.status)
        ```
        """
        query = {
            "name": name,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return SyncPage(self._client, "/v1/email/domains", query, Domain, options)

    def get(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Fetch one sending domain: verification status and the DNS records with their individual verification states.

        ```python
        domain = client.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg")
        print(domain.domain)
        ```
        """
        return self._get(
            f"/v1/email/domains/{quote(domain_id, safe='')}",
            {},
            Domain,
            options,
        )

    def create(
        self,
        *,
        domain: str,
        return_path: DomainReturnPathConfig | None = None,
        tracking: DomainTrackingConfig | None = None,
        dkim: DomainDKIMConfig | None = None,
        settings: DomainSettings | None = None,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Register a new sending domain and get the DNS records to publish. Verification is a second step: the records go live at the DNS provider, then email_domains_verify confirms them. Propagation takes minutes to hours, so the first verify often still reports unverified and a later one succeeds.

        ```python
        domain = client.domains.create(domain="mail.acme.com")
        print(domain.id, domain.status)
        ```
        """
        body = to_wire(
            DomainCreate,
            {
                "domain": domain,
                "return_path": return_path,
                "tracking": tracking,
                "dkim": dkim,
                "settings": settings,
            },
        )
        return self._write(
            "POST",
            "/v1/email/domains",
            body,
            Domain,
            options,
        )

    def verify(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Trigger a DNS verification check for a sending domain and return the refreshed domain with per-record results. Safe to repeat while waiting for DNS propagation.

        ```python
        domain = client.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg")
        print(domain.status)
        ```
        """
        return self._action(
            "POST",
            f"/v1/email/domains/{quote(domain_id, safe='')}/verify",
            Domain,
            options,
        )

    def update(
        self,
        domain_id: str,
        *,
        settings: DomainSettings | None = None,
        return_path: DomainReturnPathConfig | None = None,
        tracking: DomainTrackingConfig | None | Omit = omit,
        dkim: DomainDKIMConfig | None = None,
        inbound: DomainInboundConfig | None = None,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Update a sending domain's tracking and inbound configuration. Tracking: click_tracking and open_tracking apply immediately to new sends, and the tracking domain can be set, changed, or removed (the name part only, and the sending domain is appended for you). Enabling either toggle with no tracking domain configured returns 409, and removing the tracking domain while either toggle is still on also returns 409. Tracking-domain changes on a verified domain are staged behind DNS verification, so the current config keeps serving until the new records verify. Inbound receiving: inbound.enabled starts or stops receiving mail for the domain. Enabling requires the domain's DKIM to be verified first (a fresh enable on an unverified domain returns 422), and a domain already receiving inbound for another organization returns 422. The MX records to publish are always listed in dns_records regardless, so receiving starts only once inbound.enabled is set, even when those records are already published.

        ```python
        domain = client.domains.update(
            "dom_01krdgeqcxet5s7t44vh8rt9mg",
            settings={"click_tracking": True, "open_tracking": True},
            tracking={"name": "links"},
        )
        print(domain.id)
        ```
        """
        _body: dict[str, Any] = {}
        if settings is not None:
            _body["settings"] = settings
        if return_path is not None:
            _body["return_path"] = return_path
        if not isinstance(tracking, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["tracking"] = tracking
        if dkim is not None:
            _body["dkim"] = dkim
        if inbound is not None:
            _body["inbound"] = inbound
        body = to_wire_exclude_unset(DomainUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/email/domains/{quote(domain_id, safe='')}",
            body,
            Domain,
            options,
        )

    def delete(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a sending domain by id. Revokes its sender authorization: new sends from the domain are rejected afterward, while historical statistics and events for past sends are preserved. Destructive.

        ```python
        client.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/email/domains/{quote(domain_id, safe='')}", options)


class AsyncDomains(AsyncResource):
    def list(
        self,
        *,
        name: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Domain]:
        """List the workspace's sending domains with their verification status, as a cursor page.

        ```python
        async for domain in client.domains.list():
            print(domain.id, domain.status)
        ```
        """
        query = {
            "name": name,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return AsyncPage(self._client, "/v1/email/domains", query, Domain, options)

    async def get(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Fetch one sending domain: verification status and the DNS records with their individual verification states.

        ```python
        domain = await client.domains.get("dom_01krdgeqcxet5s7t44vh8rt9mg")
        print(domain.domain)
        ```
        """
        return await self._get(
            f"/v1/email/domains/{quote(domain_id, safe='')}",
            {},
            Domain,
            options,
        )

    async def create(
        self,
        *,
        domain: str,
        return_path: DomainReturnPathConfig | None = None,
        tracking: DomainTrackingConfig | None = None,
        dkim: DomainDKIMConfig | None = None,
        settings: DomainSettings | None = None,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Register a new sending domain and get the DNS records to publish. Verification is a second step: the records go live at the DNS provider, then email_domains_verify confirms them. Propagation takes minutes to hours, so the first verify often still reports unverified and a later one succeeds.

        ```python
        domain = await client.domains.create(domain="mail.acme.com")
        print(domain.id, domain.status)
        ```
        """
        body = to_wire(
            DomainCreate,
            {
                "domain": domain,
                "return_path": return_path,
                "tracking": tracking,
                "dkim": dkim,
                "settings": settings,
            },
        )
        return await self._write(
            "POST",
            "/v1/email/domains",
            body,
            Domain,
            options,
        )

    async def verify(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Trigger a DNS verification check for a sending domain and return the refreshed domain with per-record results. Safe to repeat while waiting for DNS propagation.

        ```python
        domain = await client.domains.verify("dom_01krdgeqcxet5s7t44vh8rt9mg")
        print(domain.status)
        ```
        """
        return await self._action(
            "POST",
            f"/v1/email/domains/{quote(domain_id, safe='')}/verify",
            Domain,
            options,
        )

    async def update(
        self,
        domain_id: str,
        *,
        settings: DomainSettings | None = None,
        return_path: DomainReturnPathConfig | None = None,
        tracking: DomainTrackingConfig | None | Omit = omit,
        dkim: DomainDKIMConfig | None = None,
        inbound: DomainInboundConfig | None = None,
        options: RequestOptions | None = None,
    ) -> Domain:
        """Update a sending domain's tracking and inbound configuration. Tracking: click_tracking and open_tracking apply immediately to new sends, and the tracking domain can be set, changed, or removed (the name part only, and the sending domain is appended for you). Enabling either toggle with no tracking domain configured returns 409, and removing the tracking domain while either toggle is still on also returns 409. Tracking-domain changes on a verified domain are staged behind DNS verification, so the current config keeps serving until the new records verify. Inbound receiving: inbound.enabled starts or stops receiving mail for the domain. Enabling requires the domain's DKIM to be verified first (a fresh enable on an unverified domain returns 422), and a domain already receiving inbound for another organization returns 422. The MX records to publish are always listed in dns_records regardless, so receiving starts only once inbound.enabled is set, even when those records are already published.

        ```python
        domain = await client.domains.update(
            "dom_01krdgeqcxet5s7t44vh8rt9mg",
            settings={"click_tracking": True, "open_tracking": True},
            tracking={"name": "links"},
        )
        print(domain.id)
        ```
        """
        _body: dict[str, Any] = {}
        if settings is not None:
            _body["settings"] = settings
        if return_path is not None:
            _body["return_path"] = return_path
        if not isinstance(tracking, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["tracking"] = tracking
        if dkim is not None:
            _body["dkim"] = dkim
        if inbound is not None:
            _body["inbound"] = inbound
        body = to_wire_exclude_unset(DomainUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/email/domains/{quote(domain_id, safe='')}",
            body,
            Domain,
            options,
        )

    async def delete(
        self,
        domain_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a sending domain by id. Revokes its sender authorization: new sends from the domain are rejected afterward, while historical statistics and events for past sends are preserved. Destructive.

        ```python
        await client.domains.delete("dom_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/email/domains/{quote(domain_id, safe='')}", options)
