# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict

from bird._generated import (
    EmailInboxInsightsAuthentication,
    EmailInboxInsightsBlocklists,
    EmailInboxInsightsComplaints,
    EmailInboxInsightsPlacement,
    EmailInboxInsightsSpamTraps,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class _EmailInboxInsightsPlacementParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsPlacementParams(_EmailInboxInsightsPlacementParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.placement``. Keys on the base class are required."""

    from_: str
    to: str
    group_by: str
    compare: str
    series_providers: Sequence[str]
    include_ip_details: bool


class _EmailInboxInsightsAuthenticationParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsAuthenticationParams(_EmailInboxInsightsAuthenticationParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.authentication``. Keys on the base class are required."""

    from_: str
    to: str
    compare: str


class _EmailInboxInsightsComplaintsParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsComplaintsParams(_EmailInboxInsightsComplaintsParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.complaints``. Keys on the base class are required."""

    from_: str
    to: str
    group_by: str
    compare: str


class _EmailInboxInsightsSpamTrapsParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsSpamTrapsParams(_EmailInboxInsightsSpamTrapsParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.spam_traps``. Keys on the base class are required."""

    from_: str
    to: str
    compare: str


class _EmailInboxInsightsBlocklistsParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsBlocklistsParams(_EmailInboxInsightsBlocklistsParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.blocklists``. Keys on the base class are required."""

    pass


class EmailInboxInsightsBase(Resource):
    def placement(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        group_by: str | None = None,
        compare: str | None = None,
        series_providers: Sequence[str] | None = None,
        include_ip_details: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsPlacement:
        """Read placement for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Rates are percentages, and section statuses distinguish missing measurements. Deltas require a requested comparison and comparable prior data; absence does not mean stable placement. Provider filters add series lines without filtering the provider table. The response reports domain-wide panel/seed estimates with audience weighting, not delivery counts or a marketing/transactional split; a domain name alone does not identify a stream. Read rate measures reading, not opens. Label freshness from freshness.as_of; missing days and nulls are not zeros. Associations do not establish a cause. This read does not enable monitoring. Individual seed-test results and Google Postmaster connection status are dashboard-only; these aggregates cannot substitute for a particular test or prove placement for every customer. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.placement(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/placement",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "group_by": group_by,
                "compare": compare,
                "series_providers": series_providers,
                "include_ip_details": include_ip_details,
            },
            EmailInboxInsightsPlacement,
            options,
        )

    def authentication(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsAuthentication:
        """Read SPF, DKIM and DMARC results for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Pass rates are percentages. A not_configured section does not establish that DNS records are absent or that authentication failed; the source's coverage must be checked. Read section statuses, sources.latest_data_date and freshness before drawing conclusions. Authentication and placement changes can coincide without establishing cause. This read does not configure authentication or enable monitoring. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.authentication(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/authentication",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "compare": compare,
            },
            EmailInboxInsightsAuthentication,
            options,
        )

    def complaints(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        group_by: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsComplaints:
        """Read the Google Postmaster user-reported spam rate for a verified owned domain. This percentage differs from spam-folder placement and Bird feedback-loop complaints across providers. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period adds the preceding period. The period rate is an unweighted mean of reported days; sparse days are missing observations, not zero complaints. Freshness identifies the last reported day, not a promised update schedule. Correlation with placement cannot identify causative sends. Sections can report not_configured when setup is incomplete; connection status and setup are available in the dashboard, not through this read. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.complaints(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/complaints",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "group_by": group_by,
                "compare": compare,
            },
            EmailInboxInsightsComplaints,
            options,
        )

    def spam_traps(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsSpamTraps:
        """Read spam-trap totals, kinds, networks and sampled hits for a verified owned domain. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period includes the preceding period. hit_rows has its own status and truncated_types; empty rows do not negate a positive total, and row counts cannot reconstruct total hits. A measured zero is valid. Hits alone do not identify the sending campaign or establish why placement changed. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.spam_traps(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/spam-traps",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "compare": compare,
            },
            EmailInboxInsightsSpamTraps,
            options,
        )

    def blocklists(
        self,
        *,
        sending_domain: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsBlocklists:
        """Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means the lookup service supplied no count. Zero and an empty target list do not establish complete coverage. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.blocklists(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/blocklists",
            {
                "sending_domain": sending_domain,
            },
            EmailInboxInsightsBlocklists,
            options,
        )


class AsyncEmailInboxInsightsBase(AsyncResource):
    async def placement(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        group_by: str | None = None,
        compare: str | None = None,
        series_providers: Sequence[str] | None = None,
        include_ip_details: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsPlacement:
        """Read placement for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Rates are percentages, and section statuses distinguish missing measurements. Deltas require a requested comparison and comparable prior data; absence does not mean stable placement. Provider filters add series lines without filtering the provider table. The response reports domain-wide panel/seed estimates with audience weighting, not delivery counts or a marketing/transactional split; a domain name alone does not identify a stream. Read rate measures reading, not opens. Label freshness from freshness.as_of; missing days and nulls are not zeros. Associations do not establish a cause. This read does not enable monitoring. Individual seed-test results and Google Postmaster connection status are dashboard-only; these aggregates cannot substitute for a particular test or prove placement for every customer. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.placement(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/placement",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "group_by": group_by,
                "compare": compare,
                "series_providers": series_providers,
                "include_ip_details": include_ip_details,
            },
            EmailInboxInsightsPlacement,
            options,
        )

    async def authentication(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsAuthentication:
        """Read SPF, DKIM and DMARC results for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Pass rates are percentages. A not_configured section does not establish that DNS records are absent or that authentication failed; the source's coverage must be checked. Read section statuses, sources.latest_data_date and freshness before drawing conclusions. Authentication and placement changes can coincide without establishing cause. This read does not configure authentication or enable monitoring. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.authentication(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/authentication",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "compare": compare,
            },
            EmailInboxInsightsAuthentication,
            options,
        )

    async def complaints(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        group_by: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsComplaints:
        """Read the Google Postmaster user-reported spam rate for a verified owned domain. This percentage differs from spam-folder placement and Bird feedback-loop complaints across providers. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period adds the preceding period. The period rate is an unweighted mean of reported days; sparse days are missing observations, not zero complaints. Freshness identifies the last reported day, not a promised update schedule. Correlation with placement cannot identify causative sends. Sections can report not_configured when setup is incomplete; connection status and setup are available in the dashboard, not through this read. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.complaints(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/complaints",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "group_by": group_by,
                "compare": compare,
            },
            EmailInboxInsightsComplaints,
            options,
        )

    async def spam_traps(
        self,
        *,
        sending_domain: str | None = None,
        from_: str | None = None,
        to: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsSpamTraps:
        """Read spam-trap totals, kinds, networks and sampled hits for a verified owned domain. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period includes the preceding period. hit_rows has its own status and truncated_types; empty rows do not negate a positive total, and row counts cannot reconstruct total hits. A measured zero is valid. Hits alone do not identify the sending campaign or establish why placement changed. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.spam_traps(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/spam-traps",
            {
                "sending_domain": sending_domain,
                "from": from_,
                "to": to,
                "compare": compare,
            },
            EmailInboxInsightsSpamTraps,
            options,
        )

    async def blocklists(
        self,
        *,
        sending_domain: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsBlocklists:
        """Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means the lookup service supplied no count. Zero and an empty target list do not establish complete coverage. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.blocklists(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/blocklists",
            {
                "sending_domain": sending_domain,
            },
            EmailInboxInsightsBlocklists,
            options,
        )
