# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypedDict

from bird._generated import (
    EmailThread,
    EmailThreadUpdateRequest,
)
from bird._models import to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class EmailLabelsUpdate(TypedDict, total=False):
    add: Sequence[str]
    remove: Sequence[str]


class EmailThreadsListParams(TypedDict, total=False):
    """Query params for ``client.email.threads.list``. Every key is optional."""

    mailbox_id: str
    contact_id: str
    label: Sequence[str]
    has_unread: bool
    participant: str
    subject: str
    after: str
    before: str
    limit: int
    starting_after: str
    ending_before: str


class EmailThreadsUpdateParams(TypedDict, total=False):
    """Params for ``client.email.threads.update``. Every key is optional."""

    labels: EmailLabelsUpdate
    contact_id: str | None


class EmailThreadsDeleteParams(TypedDict, total=False):
    """Query params for ``client.email.threads.delete``. Every key is optional."""

    permanent: bool


class EmailThreads(Resource):
    def list(
        self,
        *,
        mailbox_id: str | None = None,
        contact_id: str | None = None,
        label: Sequence[str] | None = None,
        has_unread: bool | None = None,
        participant: str | None = None,
        subject: str | None = None,
        after: str | None = None,
        before: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailThread]:
        """List mailbox conversations as a cursor page, most recently active first. `label` selects the view — inbox (default), archive, spam, blocked, or a custom label. Filter by mailbox, contact, participant address, or subject substring.

        ```python
        for thread in client.email.threads.list(mailbox_id="mbx_01krdgeqcxet5s7t44vh8rt9mg"):
            print(thread.id, thread.subject)
        ```
        """
        query = {
            "mailbox_id": mailbox_id,
            "contact_id": contact_id,
            "label": label,
            "has_unread": has_unread,
            "participant": participant,
            "subject": subject,
            "after": after,
            "before": before,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/email/threads", query, EmailThread, options)

    def get(
        self,
        thread_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailThread:
        """Get one conversation: participants, counts, labels, read state. Fetch its messages with the thread messages endpoint.

        ```python
        thread = client.email.threads.get("thr_01krdgeqcxet5s7t44vh8rt9mg")
        print(thread.subject)
        ```
        """
        return self._get(
            f"/v1/email/threads/{thread_id}",
            {},
            EmailThread,
            options,
        )

    def update(
        self,
        thread_id: str,
        *,
        labels: EmailLabelsUpdate | None = None,
        contact_id: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> EmailThread:
        """Add or remove labels on a conversation — adding `spam` files it as spam, adding `archive` clears it out of the inbox, adding `inbox` brings it back — or link/unlink a contact.

        ```python
        thread = client.email.threads.update(
            "thr_01krdgeqcxet5s7t44vh8rt9mg", labels={"add": ["archive"]}
        )
        print(thread.id)
        ```
        """
        _body: dict[str, Any] = {}
        if labels is not None:
            _body["labels"] = labels
        if not isinstance(contact_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["contact_id"] = contact_id
        body = to_wire_exclude_unset(EmailThreadUpdateRequest, _body)
        return self._write(
            "PATCH",
            f"/v1/email/threads/{thread_id}",
            body,
            EmailThread,
            options,
        )

    def delete(
        self,
        thread_id: str,
        *,
        permanent: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Move a conversation and all its messages to trash (purged after 30 days), or delete permanently with ?permanent=true.

        ```python
        client.email.threads.delete("thr_01krdgeqcxet5s7t44vh8rt9mg", permanent=True)
        ```
        """
        self._delete(
            f"/v1/email/threads/{thread_id}",
            options,
            {
                "permanent": permanent,
            },
        )


class AsyncEmailThreads(AsyncResource):
    def list(
        self,
        *,
        mailbox_id: str | None = None,
        contact_id: str | None = None,
        label: Sequence[str] | None = None,
        has_unread: bool | None = None,
        participant: str | None = None,
        subject: str | None = None,
        after: str | None = None,
        before: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailThread]:
        """List mailbox conversations as a cursor page, most recently active first. `label` selects the view — inbox (default), archive, spam, blocked, or a custom label. Filter by mailbox, contact, participant address, or subject substring.

        ```python
        async for thread in client.email.threads.list(mailbox_id="mbx_01krdgeqcxet5s7t44vh8rt9mg"):
            print(thread.id, thread.subject)
        ```
        """
        query = {
            "mailbox_id": mailbox_id,
            "contact_id": contact_id,
            "label": label,
            "has_unread": has_unread,
            "participant": participant,
            "subject": subject,
            "after": after,
            "before": before,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/email/threads", query, EmailThread, options)

    async def get(
        self,
        thread_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailThread:
        """Get one conversation: participants, counts, labels, read state. Fetch its messages with the thread messages endpoint.

        ```python
        thread = await client.email.threads.get("thr_01krdgeqcxet5s7t44vh8rt9mg")
        print(thread.subject)
        ```
        """
        return await self._get(
            f"/v1/email/threads/{thread_id}",
            {},
            EmailThread,
            options,
        )

    async def update(
        self,
        thread_id: str,
        *,
        labels: EmailLabelsUpdate | None = None,
        contact_id: str | None | Omit = omit,
        options: RequestOptions | None = None,
    ) -> EmailThread:
        """Add or remove labels on a conversation — adding `spam` files it as spam, adding `archive` clears it out of the inbox, adding `inbox` brings it back — or link/unlink a contact.

        ```python
        thread = await client.email.threads.update(
            "thr_01krdgeqcxet5s7t44vh8rt9mg", labels={"add": ["archive"]}
        )
        print(thread.id)
        ```
        """
        _body: dict[str, Any] = {}
        if labels is not None:
            _body["labels"] = labels
        if not isinstance(contact_id, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["contact_id"] = contact_id
        body = to_wire_exclude_unset(EmailThreadUpdateRequest, _body)
        return await self._write(
            "PATCH",
            f"/v1/email/threads/{thread_id}",
            body,
            EmailThread,
            options,
        )

    async def delete(
        self,
        thread_id: str,
        *,
        permanent: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Move a conversation and all its messages to trash (purged after 30 days), or delete permanently with ?permanent=true.

        ```python
        await client.email.threads.delete("thr_01krdgeqcxet5s7t44vh8rt9mg", permanent=True)
        ```
        """
        await self._delete(
            f"/v1/email/threads/{thread_id}",
            options,
            {
                "permanent": permanent,
            },
        )
