# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    EmailTemplateLanguage,
    EmailTemplateLanguageList,
    EmailTemplateLanguageSaved,
    EmailTemplateLanguageUpdate,
    EmailTemplateLanguageUpsert,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit


class _EmailTemplatesVersionsLanguagesSetRequired(TypedDict):
    subject: str


class EmailTemplatesVersionsLanguagesSetParams(_EmailTemplatesVersionsLanguagesSetRequired, total=False):
    """Params for ``client.email.templates.versions.languages.set``. ``subject`` is required."""

    preview_text: str
    html: str
    text: str
    revision: int


class EmailTemplatesVersionsLanguagesUpdateParams(TypedDict, total=False):
    """Params for ``client.email.templates.versions.languages.update``. Every key is optional."""

    subject: str
    preview_text: str | None
    html: str
    text: str | None
    revision: int


class EmailTemplatesVersionsLanguages(Resource):
    def list(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageList:
        """List the languages a template version holds, with each language's revision and fingerprint but not its content."""
        return self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages",
            {},
            EmailTemplateLanguageList,
            options,
        )

    def get(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguage:
        """Read one language's subject and bodies from a template version. The response carries `compatibility`: what the stored HTML uses that mail clients remove, ignore, or render inconsistently, and `compatibility_severity` reducing it to `problem`, `warning`, or `none`."""
        return self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            {},
            EmailTemplateLanguage,
            options,
        )

    def set(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        subject: str,
        preview_text: str | None = None,
        html: str | None = None,
        text: str | None = None,
        revision: int | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageSaved:
        """Save one language's full content on a template's draft, creating the language if the draft does not have it yet. The response carries `compatibility`: what the saved HTML uses that mail clients remove, ignore, or render inconsistently, each finding naming the pattern, its line and column, and what to use instead. Advisory: the language is saved either way, and `compatibility_severity` of `problem` means part of the content does nothing at all in the clients the finding names."""
        body = to_wire(
            EmailTemplateLanguageUpsert,
            {
                "subject": subject,
                "preview_text": preview_text,
                "html": html,
                "text": text,
                "revision": revision,
            },
        )
        return self._write(
            "PUT",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            body,
            EmailTemplateLanguageSaved,
            options,
        )

    def update(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        subject: str | None = None,
        preview_text: str | None | Omit = omit,
        html: str | None = None,
        text: str | None | Omit = omit,
        revision: int | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageSaved:
        """Change some fields of one language on a template's draft, leaving the rest as they are. The response carries `compatibility` for the language as saved, the same advisory report the full save returns."""
        _body: dict[str, Any] = {}
        if subject is not None:
            _body["subject"] = subject
        if not isinstance(preview_text, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["preview_text"] = preview_text
        if html is not None:
            _body["html"] = html
        if not isinstance(text, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["text"] = text
        if revision is not None:
            _body["revision"] = revision
        body = to_wire_exclude_unset(EmailTemplateLanguageUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            body,
            EmailTemplateLanguageSaved,
            options,
        )

    def delete(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one language from a template's draft. The current default cannot be removed on its own; update the template to point the default at a different language first, then remove the old one."""
        self._delete(f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}", options)


class AsyncEmailTemplatesVersionsLanguages(AsyncResource):
    async def list(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageList:
        """List the languages a template version holds, with each language's revision and fingerprint but not its content."""
        return await self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages",
            {},
            EmailTemplateLanguageList,
            options,
        )

    async def get(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguage:
        """Read one language's subject and bodies from a template version. The response carries `compatibility`: what the stored HTML uses that mail clients remove, ignore, or render inconsistently, and `compatibility_severity` reducing it to `problem`, `warning`, or `none`."""
        return await self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            {},
            EmailTemplateLanguage,
            options,
        )

    async def set(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        subject: str,
        preview_text: str | None = None,
        html: str | None = None,
        text: str | None = None,
        revision: int | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageSaved:
        """Save one language's full content on a template's draft, creating the language if the draft does not have it yet. The response carries `compatibility`: what the saved HTML uses that mail clients remove, ignore, or render inconsistently, each finding naming the pattern, its line and column, and what to use instead. Advisory: the language is saved either way, and `compatibility_severity` of `problem` means part of the content does nothing at all in the clients the finding names."""
        body = to_wire(
            EmailTemplateLanguageUpsert,
            {
                "subject": subject,
                "preview_text": preview_text,
                "html": html,
                "text": text,
                "revision": revision,
            },
        )
        return await self._write(
            "PUT",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            body,
            EmailTemplateLanguageSaved,
            options,
        )

    async def update(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        subject: str | None = None,
        preview_text: str | None | Omit = omit,
        html: str | None = None,
        text: str | None | Omit = omit,
        revision: int | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateLanguageSaved:
        """Change some fields of one language on a template's draft, leaving the rest as they are. The response carries `compatibility` for the language as saved, the same advisory report the full save returns."""
        _body: dict[str, Any] = {}
        if subject is not None:
            _body["subject"] = subject
        if not isinstance(preview_text, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["preview_text"] = preview_text
        if html is not None:
            _body["html"] = html
        if not isinstance(text, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["text"] = text
        if revision is not None:
            _body["revision"] = revision
        body = to_wire_exclude_unset(EmailTemplateLanguageUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}",
            body,
            EmailTemplateLanguageSaved,
            options,
        )

    async def delete(
        self,
        template_ref: str,
        version_id: str,
        language: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one language from a template's draft. The current default cannot be removed on its own; update the template to point the default at a different language first, then remove the old one."""
        await self._delete(f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/languages/{quote(language, safe='')}", options)
