# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EmailInboxInsightsDomain,
    EmailInboxInsightsDomainUpdate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class EmailInboxInsightsDomainsListParams(TypedDict, total=False):
    """Query params for ``client.email.inbox_insights.domains.list``. Every key is optional."""

    sending_domain: str
    search: str
    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str


class _EmailInboxInsightsDomainsUpdateRequired(TypedDict):
    monitored: bool


class EmailInboxInsightsDomainsUpdateParams(_EmailInboxInsightsDomainsUpdateRequired, total=False):
    """Params for ``client.email.inbox_insights.domains.update``. ``monitored`` is required."""


class EmailInboxInsightsDomains(Resource):
    def list(
        self,
        *,
        sending_domain: str | None = None,
        search: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailInboxInsightsDomain]:
        """List verified sending domains owned by the workspace and their monitoring settings. Follow next_cursor with starting_after, keeping filters and ordering. A monitored value records the workspace setting; it does not establish that vendor measurements exist. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        for domain in client.email.inbox_insights.domains.list(limit=25):
            print(domain.domain, domain.monitored)
        ```
        """
        query = {
            "sending_domain": sending_domain,
            "search": search,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/email/inbox-insights/domains", query, EmailInboxInsightsDomain, options)

    def update(
        self,
        sending_domain: str,
        *,
        monitored: bool,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsDomain:
        """Set monitored explicitly to true or false for a verified domain owned by the workspace. Enabling enrolls the domain with eDataSource and saves the workspace preference. Disabling removes only that preference; vendor enrollment and measurement history remain. Reports still require verified ownership and are not gated by this preference. Repeating the same value is safe. Reuse an idempotency key when retrying the same change. API-key and service-account calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.domains.update(sending_domain, monitored=False)
        print(report.monitored)
        ```
        """
        body = to_wire(
            EmailInboxInsightsDomainUpdate,
            {
                "monitored": monitored,
            },
        )
        return self._write(
            "PATCH",
            f"/v1/email/inbox-insights/domains/{quote(sending_domain, safe='')}",
            body,
            EmailInboxInsightsDomain,
            options,
        )


class AsyncEmailInboxInsightsDomains(AsyncResource):
    def list(
        self,
        *,
        sending_domain: str | None = None,
        search: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailInboxInsightsDomain]:
        """List verified sending domains owned by the workspace and their monitoring settings. Follow next_cursor with starting_after, keeping filters and ordering. A monitored value records the workspace setting; it does not establish that vendor measurements exist. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        async for domain in client.email.inbox_insights.domains.list(limit=25):
            print(domain.domain, domain.monitored)
        ```
        """
        query = {
            "sending_domain": sending_domain,
            "search": search,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/email/inbox-insights/domains", query, EmailInboxInsightsDomain, options)

    async def update(
        self,
        sending_domain: str,
        *,
        monitored: bool,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsDomain:
        """Set monitored explicitly to true or false for a verified domain owned by the workspace. Enabling enrolls the domain with eDataSource and saves the workspace preference. Disabling removes only that preference; vendor enrollment and measurement history remain. Reports still require verified ownership and are not gated by this preference. Repeating the same value is safe. Reuse an idempotency key when retrying the same change. API-key and service-account calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.domains.update(sending_domain, monitored=False)
        print(report.monitored)
        ```
        """
        body = to_wire(
            EmailInboxInsightsDomainUpdate,
            {
                "monitored": monitored,
            },
        )
        return await self._write(
            "PATCH",
            f"/v1/email/inbox-insights/domains/{quote(sending_domain, safe='')}",
            body,
            EmailInboxInsightsDomain,
            options,
        )
