# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict

from bird._generated import (
    EmailCompetitiveVolumeSeries,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class EmailCompetitiveVolumeSeriesParams(TypedDict, total=False):
    """Query params for ``client.email.competitive.volume_series``. Every key is optional."""

    range: int
    brand_ids: Sequence[str]


class EmailCompetitiveBase(Resource):
    def volume_series(
        self,
        *,
        range: int | None = None,
        brand_ids: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> EmailCompetitiveVolumeSeries:
        """Accepts up to 20 distinct watchlist entry IDs from `email.competitive.watchlist.get`. Omitting brand_ids requests the workspace's own line. Competitor lines retain the requested order after the workspace line, when present. Each line's source distinguishes estimated panel volume from the workspace's accepted sends. Returns daily series without pagination. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        watchlist = client.email.competitive.watchlist.get(range=30)
        entry = next((row for row in watchlist.data if row.name == "Everlane" and row.watchlist_brand_id), None)
        if entry is None or entry.watchlist_brand_id is None:
            raise ValueError("Add Everlane to the watchlist first")
        watchlist_brand_id = entry.watchlist_brand_id
        report = client.email.competitive.volume_series(range=30, brand_ids=[watchlist_brand_id])
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/competitive/volume-series",
            {
                "range": range,
                "brand_ids": None if not brand_ids else ",".join(brand_ids),
            },
            EmailCompetitiveVolumeSeries,
            options,
        )


class AsyncEmailCompetitiveBase(AsyncResource):
    async def volume_series(
        self,
        *,
        range: int | None = None,
        brand_ids: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> EmailCompetitiveVolumeSeries:
        """Accepts up to 20 distinct watchlist entry IDs from `email.competitive.watchlist.get`. Omitting brand_ids requests the workspace's own line. Competitor lines retain the requested order after the workspace line, when present. Each line's source distinguishes estimated panel volume from the workspace's accepted sends. Returns daily series without pagination. API-key calls require Insights preview access for your organization.

        ```python
        # Requires Insights preview access for the organization.
        watchlist = await client.email.competitive.watchlist.get(range=30)
        entry = next((row for row in watchlist.data if row.name == "Everlane" and row.watchlist_brand_id), None)
        if entry is None or entry.watchlist_brand_id is None:
            raise ValueError("Add Everlane to the watchlist first")
        watchlist_brand_id = entry.watchlist_brand_id
        report = await client.email.competitive.volume_series(range=30, brand_ids=[watchlist_brand_id])
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/competitive/volume-series",
            {
                "range": range,
                "brand_ids": None if not brand_ids else ",".join(brand_ids),
            },
            EmailCompetitiveVolumeSeries,
            options,
        )
