# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EmailTemplate,
    EmailTemplateRollback,
    EmailTemplateSubmit,
    EmailTemplateSubmitResult,
    EmailTemplateVersion,
    EmailTemplateVersionSummary,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class EmailTemplatesVersionsListParams(TypedDict, total=False):
    """Query params for ``client.email.templates.versions.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str


class EmailTemplatesVersionsSubmitParams(TypedDict, total=False):
    """Params for ``client.email.templates.versions.submit``. Every key is optional."""

    validate_only: bool
    expected_revision: int
    languages: Sequence[str]


class _EmailTemplatesVersionsRollbackRequired(TypedDict):
    revision: int


class EmailTemplatesVersionsRollbackParams(_EmailTemplatesVersionsRollbackRequired, total=False):
    """Params for ``client.email.templates.versions.rollback``. ``revision`` is required."""


class EmailTemplatesVersionsBase(Resource):
    def list(
        self,
        template_ref: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailTemplateVersionSummary]:
        """List every version of a template (the draft plus all published versions), newest first."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, f"/v1/email/templates/{quote(template_ref, safe='')}/versions", query, EmailTemplateVersionSummary, options)

    def get(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateVersion:
        """Read one version of a template: its lifecycle metadata (`status`, `version_number`, `published_at`), the content it froze in every language, and the `variables` that content expects at send time."""
        return self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}",
            {},
            EmailTemplateVersion,
            options,
        )

    def delete(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Throw away the draft's unsaved changes, resetting its content to what is currently published."""
        self._delete(f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}", options)

    def submit(
        self,
        template_ref: str,
        version_id: str,
        *,
        validate_only: bool | None = None,
        expected_revision: int | None = None,
        languages: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateSubmitResult:
        """Freeze a complete draft as the new immutable live version. Every language needs a subject and body, and the default language must be present. Submission is all or nothing and reports every language error. Set `validate_only: true` to check without publishing, or pass `expected_revision` to reject a concurrent edit. An unchanged draft is rejected. The response also carries `compatibility` across every language, each finding naming the language it is in: what the HTML uses that mail clients remove, ignore, or render inconsistently. Advisory and separate from `errors`, so a finding never fails a submit."""
        body = to_wire(
            EmailTemplateSubmit,
            {
                "validate_only": validate_only,
                "expected_revision": expected_revision,
                "languages": languages,
            },
        )
        return self._write(
            "POST",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/submit",
            body,
            EmailTemplateSubmitResult,
            options,
        )

    def rollback(
        self,
        template_ref: str,
        version_id: str,
        *,
        revision: int,
        options: RequestOptions | None = None,
    ) -> EmailTemplate:
        """Make an earlier published version live again and reset the draft to its content, so editing continues from it. The change is immediate, creates no new version, and leaves version history unchanged. The request must include the draft `revision` last read. The draft's current content is replaced. Only published versions can be rolled back to."""
        body = to_wire(
            EmailTemplateRollback,
            {
                "revision": revision,
            },
        )
        return self._write(
            "POST",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/rollback",
            body,
            EmailTemplate,
            options,
        )


class AsyncEmailTemplatesVersionsBase(AsyncResource):
    def list(
        self,
        template_ref: str,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailTemplateVersionSummary]:
        """List every version of a template (the draft plus all published versions), newest first."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, f"/v1/email/templates/{quote(template_ref, safe='')}/versions", query, EmailTemplateVersionSummary, options)

    async def get(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailTemplateVersion:
        """Read one version of a template: its lifecycle metadata (`status`, `version_number`, `published_at`), the content it froze in every language, and the `variables` that content expects at send time."""
        return await self._get(
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}",
            {},
            EmailTemplateVersion,
            options,
        )

    async def delete(
        self,
        template_ref: str,
        version_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Throw away the draft's unsaved changes, resetting its content to what is currently published."""
        await self._delete(f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}", options)

    async def submit(
        self,
        template_ref: str,
        version_id: str,
        *,
        validate_only: bool | None = None,
        expected_revision: int | None = None,
        languages: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> EmailTemplateSubmitResult:
        """Freeze a complete draft as the new immutable live version. Every language needs a subject and body, and the default language must be present. Submission is all or nothing and reports every language error. Set `validate_only: true` to check without publishing, or pass `expected_revision` to reject a concurrent edit. An unchanged draft is rejected. The response also carries `compatibility` across every language, each finding naming the language it is in: what the HTML uses that mail clients remove, ignore, or render inconsistently. Advisory and separate from `errors`, so a finding never fails a submit."""
        body = to_wire(
            EmailTemplateSubmit,
            {
                "validate_only": validate_only,
                "expected_revision": expected_revision,
                "languages": languages,
            },
        )
        return await self._write(
            "POST",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/submit",
            body,
            EmailTemplateSubmitResult,
            options,
        )

    async def rollback(
        self,
        template_ref: str,
        version_id: str,
        *,
        revision: int,
        options: RequestOptions | None = None,
    ) -> EmailTemplate:
        """Make an earlier published version live again and reset the draft to its content, so editing continues from it. The change is immediate, creates no new version, and leaves version history unchanged. The request must include the draft `revision` last read. The draft's current content is replaced. Only published versions can be rolled back to."""
        body = to_wire(
            EmailTemplateRollback,
            {
                "revision": revision,
            },
        )
        return await self._write(
            "POST",
            f"/v1/email/templates/{quote(template_ref, safe='')}/versions/{quote(version_id, safe='')}/rollback",
            body,
            EmailTemplate,
            options,
        )
