# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict

from bird._generated import (
    EmailInboxInsightsSeedTestConfiguration,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class _EmailInboxInsightsSeedTestsConfigurationGetParamsRequired(TypedDict):
    sending_domain: str


class EmailInboxInsightsSeedTestsConfigurationGetParams(_EmailInboxInsightsSeedTestsConfigurationGetParamsRequired, total=False):
    """Query params for ``client.email.inbox_insights.seed_tests.configuration.get``. Keys on the base class are required."""

    pass


class EmailInboxInsightsSeedTestsConfiguration(Resource):
    def get(
        self,
        *,
        sending_domain: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsSeedTestConfiguration:
        """Read available seed pools, regions and engagement profiles for an owned sending domain before `email.inbox_insights.seed_tests.create`. Use only available pools and preserve region strings exactly. Scoped API keys, OAuth and service accounts require organization preview access.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = client.email.inbox_insights.seed_tests.configuration.get(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return self._get(
            "/v1/email/inbox-insights/seed-tests/configuration",
            {
                "sending_domain": sending_domain,
            },
            EmailInboxInsightsSeedTestConfiguration,
            options,
        )


class AsyncEmailInboxInsightsSeedTestsConfiguration(AsyncResource):
    async def get(
        self,
        *,
        sending_domain: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailInboxInsightsSeedTestConfiguration:
        """Read available seed pools, regions and engagement profiles for an owned sending domain before `email.inbox_insights.seed_tests.create`. Use only available pools and preserve region strings exactly. Scoped API keys, OAuth and service accounts require organization preview access.

        ```python
        # Requires Insights preview access for the organization.
        sending_domain = None
        async for domain in client.email.inbox_insights.domains.list(search="mail.example.com"):
            if domain.domain == "mail.example.com":
                sending_domain = domain.domain
                break
        if sending_domain is None:
            raise ValueError("Verify mail.example.com in this workspace first")
        report = await client.email.inbox_insights.seed_tests.configuration.get(sending_domain=sending_domain)
        print(report.model_dump_json())
        ```
        """
        return await self._get(
            "/v1/email/inbox-insights/seed-tests/configuration",
            {
                "sending_domain": sending_domain,
            },
            EmailInboxInsightsSeedTestConfiguration,
            options,
        )
