# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EmailHealth,
    EmailMessage,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class EmailListParams(TypedDict, total=False):
    """Query params for ``client.email.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    created_after: str
    created_before: str
    status: str
    tag: Sequence[str]
    category: str
    to: str
    from_: str


class EmailHealthParams(TypedDict, total=False):
    """Query params for ``client.email.health``. Every key is optional."""

    from_: str
    to: str


class EmailBase(Resource):
    def get(
        self,
        message_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailMessage:
        """Fetch one email message by `id`, with aggregate delivery status and per-state recipient counts. The message body (`html`, `text`) is not returned. Per-recipient delivery statuses and the event log are separate sub-resources: `GET /v1/email/messages/{message_id}/recipients` and `GET /v1/email/messages/{message_id}/events`.

        ```python
        message = client.email.get("em_abc123")
        print(message.id, message.status, message.delivered_count)
        ```
        """
        return self._get(
            f"/v1/email/messages/{quote(message_id, safe='')}",
            {},
            EmailMessage,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: str | None = None,
        tag: Sequence[str] | None = None,
        category: str | None = None,
        to: str | None = None,
        from_: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EmailMessage]:
        """List sent email messages, newest first, as a cursor page (`{data, next_cursor, …}`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by creation time with the half-open range `created_after` (inclusive) and `created_before` (exclusive). For a single UTC day, `created_after` is that day at 00:00:00Z and `created_before` is the next day at 00:00:00Z.

        ```python
        for message in client.email.list(status="delivered"):
            print(message.id)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "tag": tag,
            "category": category,
            "to": to,
            "from": from_,
        }
        return SyncPage(self._client, "/v1/email/messages", query, EmailMessage, options)

    def cancel(
        self,
        message_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Cancel a scheduled email before it sends. Only works while the message's `status` is still `scheduled`. Once it starts sending, or was already canceled, the call returns a conflict error. Canceling does not return consumed scheduled-send quota.

        ```python
        client.email.cancel("em_abc123")
        ```
        """
        self._action_none(
            "POST",
            f"/v1/email/messages/{quote(message_id, safe='')}/cancel",
            options,
        )

    def health(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailHealth:
        """Deliverability verdict for one window: an overall `healthy`, `watching`, or `throttled` status, plus signals for delivery, opens, bounces, and complaints. Each signal carries its rate and verdict. Delivery, bounce, and complaint signals include the thresholds that set their verdicts; open rate has no risk thresholds. Reports risk only and never pauses sending. Window defaults to the 7 days before today (UTC), maximum 365 days. For the counts and rates behind the verdict use `email.stats.summary`.

        ```python
        health = client.email.health(from_="2026-05-01", to="2026-05-31")
        print(health.status)
        for signal in health.signals:
            print(signal.metric, signal.value, signal.status)
        ```
        """
        return self._get(
            "/v1/email/health",
            {
                "from": from_,
                "to": to,
            },
            EmailHealth,
            options,
        )


class AsyncEmailBase(AsyncResource):
    async def get(
        self,
        message_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailMessage:
        """Fetch one email message by `id`, with aggregate delivery status and per-state recipient counts. The message body (`html`, `text`) is not returned. Per-recipient delivery statuses and the event log are separate sub-resources: `GET /v1/email/messages/{message_id}/recipients` and `GET /v1/email/messages/{message_id}/events`.

        ```python
        message = await client.email.get("em_abc123")
        print(message.id, message.status, message.delivered_count)
        ```
        """
        return await self._get(
            f"/v1/email/messages/{quote(message_id, safe='')}",
            {},
            EmailMessage,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: str | None = None,
        tag: Sequence[str] | None = None,
        category: str | None = None,
        to: str | None = None,
        from_: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EmailMessage]:
        """List sent email messages, newest first, as a cursor page (`{data, next_cursor, …}`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by creation time with the half-open range `created_after` (inclusive) and `created_before` (exclusive). For a single UTC day, `created_after` is that day at 00:00:00Z and `created_before` is the next day at 00:00:00Z.

        ```python
        async for message in client.email.list(status="delivered"):
            print(message.id)
        ```
        """
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "tag": tag,
            "category": category,
            "to": to,
            "from": from_,
        }
        return AsyncPage(self._client, "/v1/email/messages", query, EmailMessage, options)

    async def cancel(
        self,
        message_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Cancel a scheduled email before it sends. Only works while the message's `status` is still `scheduled`. Once it starts sending, or was already canceled, the call returns a conflict error. Canceling does not return consumed scheduled-send quota.

        ```python
        await client.email.cancel("em_abc123")
        ```
        """
        await self._action_none(
            "POST",
            f"/v1/email/messages/{quote(message_id, safe='')}/cancel",
            options,
        )

    async def health(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        options: RequestOptions | None = None,
    ) -> EmailHealth:
        """Deliverability verdict for one window: an overall `healthy`, `watching`, or `throttled` status, plus signals for delivery, opens, bounces, and complaints. Each signal carries its rate and verdict. Delivery, bounce, and complaint signals include the thresholds that set their verdicts; open rate has no risk thresholds. Reports risk only and never pauses sending. Window defaults to the 7 days before today (UTC), maximum 365 days. For the counts and rates behind the verdict use `email.stats.summary`.

        ```python
        health = await client.email.health(from_="2026-05-01", to="2026-05-31")
        print(health.status)
        for signal in health.signals:
            print(signal.metric, signal.value, signal.status)
        ```
        """
        return await self._get(
            "/v1/email/health",
            {
                "from": from_,
                "to": to,
            },
            EmailHealth,
            options,
        )
