# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EsimPackage,
    EsimPackageList,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class EsimPackagesDeleteParams(TypedDict, total=False):
    """Query params for ``client.esim.packages.delete``. Every key is optional."""

    acknowledge_balance_forfeit: bool


class EsimPackages(Resource):
    def list(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimPackageList:
        """Returns the eSIM's data packages with per-zone balances, validity, and status, newest first and in full: an eSIM holds at most package_limit concurrent packages. Balances update as mobile networks report usage; `balance.as_of` tells you how fresh they are."""
        return self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages",
            {},
            EsimPackageList,
            options,
        )

    def get(
        self,
        esim_id: str,
        package_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimPackage:
        """Returns one data package with its balance, validity, speed class, and status."""
        return self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages/{quote(package_id, safe='')}",
            {},
            EsimPackage,
            options,
        )

    def delete(
        self,
        esim_id: str,
        package_id: str,
        *,
        acknowledge_balance_forfeit: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove a data package from an eSIM, freeing room under its package_limit. DESTRUCTIVE: any remaining balance is forfeited and removal itself never credits anything back; requires acknowledge_balance_forfeit=true when balance remains."""
        self._delete(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages/{quote(package_id, safe='')}",
            options,
            {
                "acknowledge_balance_forfeit": acknowledge_balance_forfeit,
            },
        )


class AsyncEsimPackages(AsyncResource):
    async def list(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimPackageList:
        """Returns the eSIM's data packages with per-zone balances, validity, and status, newest first and in full: an eSIM holds at most package_limit concurrent packages. Balances update as mobile networks report usage; `balance.as_of` tells you how fresh they are."""
        return await self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages",
            {},
            EsimPackageList,
            options,
        )

    async def get(
        self,
        esim_id: str,
        package_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimPackage:
        """Returns one data package with its balance, validity, speed class, and status."""
        return await self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages/{quote(package_id, safe='')}",
            {},
            EsimPackage,
            options,
        )

    async def delete(
        self,
        esim_id: str,
        package_id: str,
        *,
        acknowledge_balance_forfeit: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove a data package from an eSIM, freeing room under its package_limit. DESTRUCTIVE: any remaining balance is forfeited and removal itself never credits anything back; requires acknowledge_balance_forfeit=true when balance remains."""
        await self._delete(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/packages/{quote(package_id, safe='')}",
            options,
            {
                "acknowledge_balance_forfeit": acknowledge_balance_forfeit,
            },
        )
