# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    Esim,
    EsimCompatibleOfferList,
    EsimSummary,
    EsimUpdate,
)
from bird._models import to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class _TagRequired(TypedDict):
    name: str
    value: str


class Tag(_TagRequired, total=False):
    pass


class EsimListParams(TypedDict, total=False):
    """Query params for ``client.esim.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    subscriber_id: str
    created_after: str
    created_before: str
    status: Sequence[str]
    iccid: str
    mode: str
    tag: Sequence[str]
    iccid_prefix: str
    display_name: str
    phone_number: str


class EsimUpdateParams(TypedDict, total=False):
    """Params for ``client.esim.update``. Every key is optional."""

    display_name: str | None
    tags: Sequence[Tag]
    metadata: Mapping[str, Any]


class EsimReleaseParams(TypedDict, total=False):
    """Query params for ``client.esim.release``. Every key is optional."""

    acknowledge_balance_forfeit: bool


class EsimCompatibleOffersParams(TypedDict, total=False):
    """Query params for ``client.esim.compatible_offers``. Every key is optional."""

    recurring_only: bool


class EsimBase(Resource):
    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        subscriber_id: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: Sequence[str] | None = None,
        iccid: str | None = None,
        mode: str | None = None,
        tag: Sequence[str] | None = None,
        iccid_prefix: str | None = None,
        display_name: str | None = None,
        phone_number: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EsimSummary]:
        """List the workspace's eSIMs, newest first, as a cursor page ({data, next_cursor, ...}). Filter by status, iccid, or tag, or search by iccid_prefix, display_name, or phone_number. Each row is a compact summary; fetch a single eSIM for its packages and balances."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "subscriber_id": subscriber_id,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "iccid": iccid,
            "mode": mode,
            "tag": tag,
            "iccid_prefix": iccid_prefix,
            "display_name": display_name,
            "phone_number": phone_number,
        }
        return SyncPage(self._client, "/v1/esim/sims", query, EsimSummary, options)

    def get(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Get one eSIM with its lifecycle status, installation state, current data packages and balances, service-period timestamps, and last network attachment."""
        return self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            {},
            Esim,
            options,
        )

    def update(
        self,
        esim_id: str,
        *,
        display_name: str | None | Omit = omit,
        tags: Sequence[Tag] | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Updates the eSIM's display name, tags, or metadata. Lifecycle and connectivity are managed through the dedicated endpoints."""
        _body: dict[str, Any] = {}
        if not isinstance(display_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["display_name"] = display_name
        if tags is not None:
            _body["tags"] = tags
        if metadata is not None:
            _body["metadata"] = metadata
        body = to_wire_exclude_unset(EsimUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            body,
            Esim,
            options,
        )

    def release(
        self,
        esim_id: str,
        *,
        acknowledge_balance_forfeit: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently release an eSIM. Irreversible: it can never be installed or used again, remaining package balances are forfeited, and release never credits anything back. Use release when responding to fraud or closing out a trip; to pause service temporarily use suspend instead."""
        self._delete(
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            options,
            {
                "acknowledge_balance_forfeit": acknowledge_balance_forfeit,
            },
        )

    def suspend(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Suspend an eSIM's data service (reversible; validity keeps running). Confirmed by the esim.suspended event. Use resume to restore service."""
        return self._action(
            "POST",
            f"/v1/esim/sims/{quote(esim_id, safe='')}/suspend",
            Esim,
            options,
        )

    def resume(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Resume a suspended eSIM so it can use data again. Confirmed by the esim.resumed event."""
        return self._action(
            "POST",
            f"/v1/esim/sims/{quote(esim_id, safe='')}/resume",
            Esim,
            options,
        )

    def compatible_offers(
        self,
        esim_id: str,
        *,
        recurring_only: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EsimCompatibleOfferList:
        """List the offers that can be ordered as a top-up for this specific eSIM right now. Use this before creating a top-up order: the general offer catalog is not the answer, because a top-up must be servable by the eSIM's own mobile network and fit its package_limit."""
        return self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/compatible-offers",
            {
                "recurring_only": recurring_only,
            },
            EsimCompatibleOfferList,
            options,
        )


class AsyncEsimBase(AsyncResource):
    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        subscriber_id: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: Sequence[str] | None = None,
        iccid: str | None = None,
        mode: str | None = None,
        tag: Sequence[str] | None = None,
        iccid_prefix: str | None = None,
        display_name: str | None = None,
        phone_number: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EsimSummary]:
        """List the workspace's eSIMs, newest first, as a cursor page ({data, next_cursor, ...}). Filter by status, iccid, or tag, or search by iccid_prefix, display_name, or phone_number. Each row is a compact summary; fetch a single eSIM for its packages and balances."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "subscriber_id": subscriber_id,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "iccid": iccid,
            "mode": mode,
            "tag": tag,
            "iccid_prefix": iccid_prefix,
            "display_name": display_name,
            "phone_number": phone_number,
        }
        return AsyncPage(self._client, "/v1/esim/sims", query, EsimSummary, options)

    async def get(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Get one eSIM with its lifecycle status, installation state, current data packages and balances, service-period timestamps, and last network attachment."""
        return await self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            {},
            Esim,
            options,
        )

    async def update(
        self,
        esim_id: str,
        *,
        display_name: str | None | Omit = omit,
        tags: Sequence[Tag] | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Updates the eSIM's display name, tags, or metadata. Lifecycle and connectivity are managed through the dedicated endpoints."""
        _body: dict[str, Any] = {}
        if not isinstance(display_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["display_name"] = display_name
        if tags is not None:
            _body["tags"] = tags
        if metadata is not None:
            _body["metadata"] = metadata
        body = to_wire_exclude_unset(EsimUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            body,
            Esim,
            options,
        )

    async def release(
        self,
        esim_id: str,
        *,
        acknowledge_balance_forfeit: bool | None = None,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently release an eSIM. Irreversible: it can never be installed or used again, remaining package balances are forfeited, and release never credits anything back. Use release when responding to fraud or closing out a trip; to pause service temporarily use suspend instead."""
        await self._delete(
            f"/v1/esim/sims/{quote(esim_id, safe='')}",
            options,
            {
                "acknowledge_balance_forfeit": acknowledge_balance_forfeit,
            },
        )

    async def suspend(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Suspend an eSIM's data service (reversible; validity keeps running). Confirmed by the esim.suspended event. Use resume to restore service."""
        return await self._action(
            "POST",
            f"/v1/esim/sims/{quote(esim_id, safe='')}/suspend",
            Esim,
            options,
        )

    async def resume(
        self,
        esim_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Esim:
        """Resume a suspended eSIM so it can use data again. Confirmed by the esim.resumed event."""
        return await self._action(
            "POST",
            f"/v1/esim/sims/{quote(esim_id, safe='')}/resume",
            Esim,
            options,
        )

    async def compatible_offers(
        self,
        esim_id: str,
        *,
        recurring_only: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EsimCompatibleOfferList:
        """List the offers that can be ordered as a top-up for this specific eSIM right now. Use this before creating a top-up order: the general offer catalog is not the answer, because a top-up must be servable by the eSIM's own mobile network and fit its package_limit."""
        return await self._get(
            f"/v1/esim/sims/{quote(esim_id, safe='')}/compatible-offers",
            {
                "recurring_only": recurring_only,
            },
            EsimCompatibleOfferList,
            options,
        )
