# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    EsimOrder,
    EsimOrderCreate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class _MoneyRequired(TypedDict):
    amount: str
    currency_code: str


class Money(_MoneyRequired, total=False):
    pass


class _EsimOrderRecurrenceRequired(TypedDict):
    recurrence_revision: int
    accepted_price: Money


class EsimOrderRecurrence(_EsimOrderRecurrenceRequired, total=False):
    pass


class _TagRequired(TypedDict):
    name: str
    value: str


class Tag(_TagRequired, total=False):
    pass


class _EsimOrdersCreateRequired(TypedDict):
    offer_id: str


class EsimOrdersCreateParams(_EsimOrdersCreateRequired, total=False):
    """Params for ``client.esim.orders.create``. ``offer_id`` is required."""

    esim_id: str
    subscriber_id: str
    offer_revision: int
    recurrence: EsimOrderRecurrence
    expected_price: Money
    display_name: str
    tags: Sequence[Tag]
    metadata: Mapping[str, Any]
    acknowledge_shortened_validity: bool


class EsimOrdersListParams(TypedDict, total=False):
    """Query params for ``client.esim.orders.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    created_after: str
    created_before: str
    status: Sequence[str]
    esim_id: str
    mode: str
    completed_after: str
    completed_before: str


class EsimOrders(Resource):
    def create(
        self,
        *,
        offer_id: str,
        esim_id: str | None = None,
        subscriber_id: str | None = None,
        offer_revision: int | None = None,
        recurrence: EsimOrderRecurrence | None = None,
        expected_price: Money | None = None,
        display_name: str | None = None,
        tags: Sequence[Tag] | None = None,
        metadata: Mapping[str, Any] | None = None,
        acknowledge_shortened_validity: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Purchase an eSIM data package. Without esim_id a new eSIM is provisioned with the package; with esim_id the package is added to that eSIM. The order locks the offer's price at creation. Inspect status even on HTTP 201: the order can be completed or failed. On HTTP 202, poll until completed or failed. Omit delivery; after completion use `esim.credentials.deliver` to send install credentials to the traveler."""
        body = to_wire(
            EsimOrderCreate,
            {
                "offer_id": offer_id,
                "esim_id": esim_id,
                "subscriber_id": subscriber_id,
                "offer_revision": offer_revision,
                "recurrence": recurrence,
                "expected_price": expected_price,
                "display_name": display_name,
                "tags": tags,
                "metadata": metadata,
                "acknowledge_shortened_validity": acknowledge_shortened_validity,
            },
        )
        return self._write(
            "POST",
            "/v1/esim/orders",
            body,
            EsimOrder,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: Sequence[str] | None = None,
        esim_id: str | None = None,
        mode: str | None = None,
        completed_after: str | None = None,
        completed_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EsimOrder]:
        """Returns the workspace's orders as a cursor-paginated list, newest first. Filter by `status` to find in-flight or failed purchases, by `esim_id` for one eSIM's purchase history, or by `mode` to separate test purchases from real ones. Test orders are listed alongside real ones by default, each carrying its own `mode`."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "esim_id": esim_id,
            "mode": mode,
            "completed_after": completed_after,
            "completed_before": completed_before,
        }
        return SyncPage(self._client, "/v1/esim/orders", query, EsimOrder, options)

    def get(
        self,
        order_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Returns one order. Poll until `status` is `completed` or `failed`; a completed order names the eSIM and package it produced."""
        return self._get(
            f"/v1/esim/orders/{quote(order_id, safe='')}",
            {},
            EsimOrder,
            options,
        )

    def cancel(
        self,
        order_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Cancel an order waiting for funds. Inspect the returned status: an unfunded order fails with failure_code canceled; an initial recurring order whose payment was recovered continues delivery with future renewal stopped. One-time orders already funded return a conflict."""
        return self._action(
            "POST",
            f"/v1/esim/orders/{quote(order_id, safe='')}/cancel",
            EsimOrder,
            options,
        )


class AsyncEsimOrders(AsyncResource):
    async def create(
        self,
        *,
        offer_id: str,
        esim_id: str | None = None,
        subscriber_id: str | None = None,
        offer_revision: int | None = None,
        recurrence: EsimOrderRecurrence | None = None,
        expected_price: Money | None = None,
        display_name: str | None = None,
        tags: Sequence[Tag] | None = None,
        metadata: Mapping[str, Any] | None = None,
        acknowledge_shortened_validity: bool | None = None,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Purchase an eSIM data package. Without esim_id a new eSIM is provisioned with the package; with esim_id the package is added to that eSIM. The order locks the offer's price at creation. Inspect status even on HTTP 201: the order can be completed or failed. On HTTP 202, poll until completed or failed. Omit delivery; after completion use `esim.credentials.deliver` to send install credentials to the traveler."""
        body = to_wire(
            EsimOrderCreate,
            {
                "offer_id": offer_id,
                "esim_id": esim_id,
                "subscriber_id": subscriber_id,
                "offer_revision": offer_revision,
                "recurrence": recurrence,
                "expected_price": expected_price,
                "display_name": display_name,
                "tags": tags,
                "metadata": metadata,
                "acknowledge_shortened_validity": acknowledge_shortened_validity,
            },
        )
        return await self._write(
            "POST",
            "/v1/esim/orders",
            body,
            EsimOrder,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        created_after: str | None = None,
        created_before: str | None = None,
        status: Sequence[str] | None = None,
        esim_id: str | None = None,
        mode: str | None = None,
        completed_after: str | None = None,
        completed_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EsimOrder]:
        """Returns the workspace's orders as a cursor-paginated list, newest first. Filter by `status` to find in-flight or failed purchases, by `esim_id` for one eSIM's purchase history, or by `mode` to separate test purchases from real ones. Test orders are listed alongside real ones by default, each carrying its own `mode`."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "created_after": created_after,
            "created_before": created_before,
            "status": status,
            "esim_id": esim_id,
            "mode": mode,
            "completed_after": completed_after,
            "completed_before": completed_before,
        }
        return AsyncPage(self._client, "/v1/esim/orders", query, EsimOrder, options)

    async def get(
        self,
        order_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Returns one order. Poll until `status` is `completed` or `failed`; a completed order names the eSIM and package it produced."""
        return await self._get(
            f"/v1/esim/orders/{quote(order_id, safe='')}",
            {},
            EsimOrder,
            options,
        )

    async def cancel(
        self,
        order_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimOrder:
        """Cancel an order waiting for funds. Inspect the returned status: an unfunded order fails with failure_code canceled; an initial recurring order whose payment was recovered continues delivery with future renewal stopped. One-time orders already funded return a conflict."""
        return await self._action(
            "POST",
            f"/v1/esim/orders/{quote(order_id, safe='')}/cancel",
            EsimOrder,
            options,
        )
