# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    EsimSubscriber,
    EsimSubscriberCreate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class _EsimSubscribersCreateRequired(TypedDict):
    contact_id: str


class EsimSubscribersCreateParams(_EsimSubscribersCreateRequired, total=False):
    """Params for ``client.esim.subscribers.create``. ``contact_id`` is required."""


class EsimSubscribersListParams(TypedDict, total=False):
    """Query params for ``client.esim.subscribers.list``. Every key is optional."""

    limit: int
    starting_after: str
    ending_before: str
    contact_id: str


class EsimSubscribers(Resource):
    def create(
        self,
        *,
        contact_id: str,
        options: RequestOptions | None = None,
    ) -> EsimSubscriber:
        """Create or return a subscriber for a workspace contact. Requires email_marketing read and esim write. Does not buy or assign an eSIM. The association blocks contact deletion and cannot currently be removed, including after the service ends."""
        body = to_wire(
            EsimSubscriberCreate,
            {
                "contact_id": contact_id,
            },
        )
        return self._write(
            "POST",
            "/v1/esim/subscribers",
            body,
            EsimSubscriber,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        contact_id: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[EsimSubscriber]:
        """Returns person references in this workspace, newest first. Filter by contact_id to find an existing subscriber."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "contact_id": contact_id,
        }
        return SyncPage(self._client, "/v1/esim/subscribers", query, EsimSubscriber, options)

    def get(
        self,
        subscriber_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimSubscriber:
        """Returns the contact reference for a subscriber in this workspace. Contact details remain available through Contacts with its separate permissions."""
        return self._get(
            f"/v1/esim/subscribers/{quote(subscriber_id, safe='')}",
            {},
            EsimSubscriber,
            options,
        )


class AsyncEsimSubscribers(AsyncResource):
    async def create(
        self,
        *,
        contact_id: str,
        options: RequestOptions | None = None,
    ) -> EsimSubscriber:
        """Create or return a subscriber for a workspace contact. Requires email_marketing read and esim write. Does not buy or assign an eSIM. The association blocks contact deletion and cannot currently be removed, including after the service ends."""
        body = to_wire(
            EsimSubscriberCreate,
            {
                "contact_id": contact_id,
            },
        )
        return await self._write(
            "POST",
            "/v1/esim/subscribers",
            body,
            EsimSubscriber,
            options,
        )

    def list(
        self,
        *,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        contact_id: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[EsimSubscriber]:
        """Returns person references in this workspace, newest first. Filter by contact_id to find an existing subscriber."""
        query = {
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "contact_id": contact_id,
        }
        return AsyncPage(self._client, "/v1/esim/subscribers", query, EsimSubscriber, options)

    async def get(
        self,
        subscriber_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EsimSubscriber:
        """Returns the contact reference for a subscriber in this workspace. Contact details remain available through Contacts with its separate permissions."""
        return await self._get(
            f"/v1/esim/subscribers/{quote(subscriber_id, safe='')}",
            {},
            EsimSubscriber,
            options,
        )
