# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict

from bird._generated import (
    EmailLookup,
    EmailLookupBatchRequest,
    EmailLookupBatchResponse,
    EmailLookupRequest,
    PhoneNumberLookup,
    PhoneNumberLookupRequest,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class _LookupPhoneNumberRequired(TypedDict):
    phone_number: str


class LookupPhoneNumberParams(_LookupPhoneNumberRequired, total=False):
    """Params for ``client.lookup.phone_number``. ``phone_number`` is required."""

    type: Sequence[str]


class _LookupEmailRequired(TypedDict):
    email: str


class LookupEmailParams(_LookupEmailRequired, total=False):
    """Params for ``client.lookup.email``. ``email`` is required."""


class _LookupEmailBatchRequired(TypedDict):
    emails: Sequence[str]


class LookupEmailBatchParams(_LookupEmailBatchRequired, total=False):
    """Params for ``client.lookup.email_batch``. ``emails`` is required."""


class Lookup(Resource):
    def phone_number(
        self,
        *,
        phone_number: str,
        type: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> PhoneNumberLookup:
        """Create a lookup for a phone number's networks, porting state, country, and line type. Pass `type` to request separately billed `classification`, `porting`, `presence`, `roaming`, `sim_swap`, or `score` blocks. Each block reports its own status, and only blocks with an `ok` status add a charge; the lookup does not contact the number.

        ```python
        answer = client.lookup.phone_number(
            phone_number="+31612345678", type=["classification", "score"]
        )
        print(answer.country_code, answer.line_type)
        # Only a block whose status is ok carries a value, and only that one is billed.
        if answer.score is not None and answer.score.status == "ok":
            print(answer.score.value)
        ```
        """
        body = to_wire(
            PhoneNumberLookupRequest,
            {
                "phone_number": phone_number,
                "type": type,
            },
        )
        return self._write(
            "POST",
            "/v1/lookup/phone-number",
            body,
            PhoneNumberLookup,
            options,
        )

    def email(
        self,
        *,
        email: str,
        options: RequestOptions | None = None,
    ) -> EmailLookup:
        """Create a deliverability lookup for one email address. Returns `result`, `delivery_confidence`, address `flags`, an assessment `reason`, and `did_you_mean` when a correction is available. Treat unknown `result` and `reason` values as valid additions and use `delivery_confidence` as the fallback; each completed lookup incurs the same charge.

        ```python
        answer = client.lookup.email(email="aisha.khan@example.com")
        # result is an open vocabulary; delivery_confidence is always comparable.
        print(answer.result, answer.delivery_confidence)
        ```
        """
        body = to_wire(
            EmailLookupRequest,
            {
                "email": email,
            },
        )
        return self._write(
            "POST",
            "/v1/lookup/email",
            body,
            EmailLookup,
            options,
        )

    def email_batch(
        self,
        *,
        emails: Sequence[str],
        options: RequestOptions | None = None,
    ) -> EmailLookupBatchResponse:
        """Assess up to 1,000 email addresses in one request. Results preserve input order and duplicates; malformed addresses receive individual assessments. Each answered entry is billed. Use a separate idempotency key per batch and reuse it for retries. Requests are limited to 128 KiB; responses over 256 KiB cannot be replayed and a retry can incur another charge.

        ```python
        answer = client.lookup.email_batch(emails=["aisha.khan@example.com", "not-an-email"])
        for item in answer.data:
            print(item.email, item.result)
        ```
        """
        body = to_wire(
            EmailLookupBatchRequest,
            {
                "emails": emails,
            },
        )
        return self._write(
            "POST",
            "/v1/lookup/email/batch",
            body,
            EmailLookupBatchResponse,
            options,
        )


class AsyncLookup(AsyncResource):
    async def phone_number(
        self,
        *,
        phone_number: str,
        type: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> PhoneNumberLookup:
        """Create a lookup for a phone number's networks, porting state, country, and line type. Pass `type` to request separately billed `classification`, `porting`, `presence`, `roaming`, `sim_swap`, or `score` blocks. Each block reports its own status, and only blocks with an `ok` status add a charge; the lookup does not contact the number.

        ```python
        answer = await client.lookup.phone_number(
            phone_number="+31612345678", type=["classification", "score"]
        )
        print(answer.country_code, answer.line_type)
        # Only a block whose status is ok carries a value, and only that one is billed.
        if answer.score is not None and answer.score.status == "ok":
            print(answer.score.value)
        ```
        """
        body = to_wire(
            PhoneNumberLookupRequest,
            {
                "phone_number": phone_number,
                "type": type,
            },
        )
        return await self._write(
            "POST",
            "/v1/lookup/phone-number",
            body,
            PhoneNumberLookup,
            options,
        )

    async def email(
        self,
        *,
        email: str,
        options: RequestOptions | None = None,
    ) -> EmailLookup:
        """Create a deliverability lookup for one email address. Returns `result`, `delivery_confidence`, address `flags`, an assessment `reason`, and `did_you_mean` when a correction is available. Treat unknown `result` and `reason` values as valid additions and use `delivery_confidence` as the fallback; each completed lookup incurs the same charge.

        ```python
        answer = await client.lookup.email(email="aisha.khan@example.com")
        # result is an open vocabulary; delivery_confidence is always comparable.
        print(answer.result, answer.delivery_confidence)
        ```
        """
        body = to_wire(
            EmailLookupRequest,
            {
                "email": email,
            },
        )
        return await self._write(
            "POST",
            "/v1/lookup/email",
            body,
            EmailLookup,
            options,
        )

    async def email_batch(
        self,
        *,
        emails: Sequence[str],
        options: RequestOptions | None = None,
    ) -> EmailLookupBatchResponse:
        """Assess up to 1,000 email addresses in one request. Results preserve input order and duplicates; malformed addresses receive individual assessments. Each answered entry is billed. Use a separate idempotency key per batch and reuse it for retries. Requests are limited to 128 KiB; responses over 256 KiB cannot be replayed and a retry can incur another charge.

        ```python
        answer = await client.lookup.email_batch(emails=["aisha.khan@example.com", "not-an-email"])
        for item in answer.data:
            print(item.email, item.result)
        ```
        """
        body = to_wire(
            EmailLookupBatchRequest,
            {
                "emails": emails,
            },
        )
        return await self._write(
            "POST",
            "/v1/lookup/email/batch",
            body,
            EmailLookupBatchResponse,
            options,
        )
