# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypedDict

from bird._generated import (
    EmailMailboxLabelList,
    Mailbox,
    MailboxCreate,
    MailboxStatsResponse,
    MailboxUpdate,
)
from bird._models import to_wire, to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class MailboxListParams(TypedDict, total=False):
    """Query params for ``client.mailbox.list``. Every key is optional."""

    address: str
    q: str
    state: str
    domain: str
    include_deleted: bool
    limit: int
    starting_after: str
    ending_before: str


class MailboxCreateParams(TypedDict, total=False):
    """Params for ``client.mailbox.create``. Every key is optional."""

    local_part: str
    domain: str
    display_name: str
    default_reply_to: str
    receive_policy: str
    retention_tier: str
    metadata: Mapping[str, Any]


class MailboxUpdateParams(TypedDict, total=False):
    """Params for ``client.mailbox.update``. Every key is optional."""

    display_name: str | None
    default_reply_to: str | None
    receive_policy: str
    retention_tier: str
    metadata: Mapping[str, Any]


class MailboxStatsParams(TypedDict, total=False):
    """Query params for ``client.mailbox.stats``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    granularity: str


class MailboxBase(Resource):
    def list(
        self,
        *,
        address: str | None = None,
        q: str | None = None,
        state: str | None = None,
        domain: str | None = None,
        include_deleted: bool | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Mailbox]:
        """List the workspace's mailboxes as a cursor page, newest first. Search addresses and display names with q, or filter by exact address, state, or domain.

        ```python
        for mailbox in client.mailbox.list():
            print(mailbox.id, mailbox.address)
        ```
        """
        query = {
            "address": address,
            "q": q,
            "state": state,
            "domain": domain,
            "include_deleted": include_deleted,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/email/mailboxes", query, Mailbox, options)

    def create(
        self,
        *,
        local_part: str | None = None,
        domain: str | None = None,
        display_name: str | None = None,
        default_reply_to: str | None = None,
        receive_policy: str | None = None,
        retention_tier: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Create a mailbox — a durable agent identity that owns an email address, groups mail into threads, and remembers conversations for its retention tier.

        ```python
        mailbox = client.mailbox.create(display_name="Acme Support")
        print(mailbox.id)
        ```
        """
        body = to_wire(
            MailboxCreate,
            {
                "local_part": local_part,
                "domain": domain,
                "display_name": display_name,
                "default_reply_to": default_reply_to,
                "receive_policy": receive_policy,
                "retention_tier": retention_tier,
                "metadata": metadata,
            },
        )
        return self._write(
            "POST",
            "/v1/email/mailboxes",
            body,
            Mailbox,
            options,
        )

    def get(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """
        ```python
        mailbox = client.mailbox.get("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.address)
        ```
        """
        return self._get(
            f"/v1/email/mailboxes/{mailbox_id}",
            {},
            Mailbox,
            options,
        )

    def update(
        self,
        mailbox_id: str,
        *,
        display_name: str | None | Omit = omit,
        default_reply_to: str | None | Omit = omit,
        receive_policy: str | None = None,
        retention_tier: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        confirm: bool | None = None,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Update a mailbox's display name, reply-to, receive policy, retention tier, contact, or metadata. Lowering the retention tier onto remembered messages older than the new horizon requires confirm=true.

        ```python
        mailbox = client.mailbox.update(
            "mbx_01krdgeqcxet5s7t44vh8rt9mg", display_name="Billing"
        )
        print(mailbox.display_name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(display_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["display_name"] = display_name
        if not isinstance(default_reply_to, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["default_reply_to"] = default_reply_to
        if receive_policy is not None:
            _body["receive_policy"] = receive_policy
        if retention_tier is not None:
            _body["retention_tier"] = retention_tier
        if metadata is not None:
            _body["metadata"] = metadata
        body = to_wire_exclude_unset(MailboxUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/email/mailboxes/{mailbox_id}",
            body,
            Mailbox,
            options,
            {
                "confirm": confirm,
            },
        )

    def delete(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a mailbox. The address stops receiving immediately and is quarantined; the mailbox and its remembered messages stay restorable for 30 days via the restore endpoint, then are permanently deleted.

        ```python
        client.mailbox.delete("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/email/mailboxes/{mailbox_id}", options)

    def restore(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Restore a mailbox deleted less than 30 days ago: the address starts receiving again and the remembered messages are back. Past the window the mailbox is permanently deleted and returns 404; a mailbox that is not deleted returns 409.

        ```python
        mailbox = client.mailbox.restore("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.id)
        ```
        """
        return self._action(
            "POST",
            f"/v1/email/mailboxes/{mailbox_id}/restore",
            Mailbox,
            options,
        )

    def resume(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Reactivate a suspended mailbox so it can send and receive again and its threads become visible. Fails if your plan does not have room for another active mailbox (or another custom inbox.ai handle); delete an active mailbox or upgrade first. A mailbox that is not suspended returns 409.

        ```python
        mailbox = client.mailbox.resume("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.state)
        ```
        """
        return self._action(
            "POST",
            f"/v1/email/mailboxes/{mailbox_id}/resume",
            Mailbox,
            options,
        )

    def stats(
        self,
        mailbox_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        granularity: str | None = None,
        options: RequestOptions | None = None,
    ) -> MailboxStatsResponse:
        """
        ```python
        stats = client.mailbox.stats("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(stats.summary)
        ```
        """
        return self._get(
            f"/v1/email/mailboxes/{mailbox_id}/stats",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "granularity": granularity,
            },
            MailboxStatsResponse,
            options,
        )

    def labels(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailMailboxLabelList:
        """List the labels available in a mailbox: the built-in system labels (inbox, archive, spam, blocked, sent, trash, unread) plus every custom label in use.

        ```python
        labels = client.mailbox.labels("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        for label in labels.data:
            print(label.name)
        ```
        """
        return self._get(
            f"/v1/email/mailboxes/{mailbox_id}/labels",
            {},
            EmailMailboxLabelList,
            options,
        )


class AsyncMailboxBase(AsyncResource):
    def list(
        self,
        *,
        address: str | None = None,
        q: str | None = None,
        state: str | None = None,
        domain: str | None = None,
        include_deleted: bool | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Mailbox]:
        """List the workspace's mailboxes as a cursor page, newest first. Search addresses and display names with q, or filter by exact address, state, or domain.

        ```python
        async for mailbox in client.mailbox.list():
            print(mailbox.id, mailbox.address)
        ```
        """
        query = {
            "address": address,
            "q": q,
            "state": state,
            "domain": domain,
            "include_deleted": include_deleted,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/email/mailboxes", query, Mailbox, options)

    async def create(
        self,
        *,
        local_part: str | None = None,
        domain: str | None = None,
        display_name: str | None = None,
        default_reply_to: str | None = None,
        receive_policy: str | None = None,
        retention_tier: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Create a mailbox — a durable agent identity that owns an email address, groups mail into threads, and remembers conversations for its retention tier.

        ```python
        mailbox = await client.mailbox.create(display_name="Acme Support")
        print(mailbox.id)
        ```
        """
        body = to_wire(
            MailboxCreate,
            {
                "local_part": local_part,
                "domain": domain,
                "display_name": display_name,
                "default_reply_to": default_reply_to,
                "receive_policy": receive_policy,
                "retention_tier": retention_tier,
                "metadata": metadata,
            },
        )
        return await self._write(
            "POST",
            "/v1/email/mailboxes",
            body,
            Mailbox,
            options,
        )

    async def get(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """
        ```python
        mailbox = await client.mailbox.get("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.address)
        ```
        """
        return await self._get(
            f"/v1/email/mailboxes/{mailbox_id}",
            {},
            Mailbox,
            options,
        )

    async def update(
        self,
        mailbox_id: str,
        *,
        display_name: str | None | Omit = omit,
        default_reply_to: str | None | Omit = omit,
        receive_policy: str | None = None,
        retention_tier: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        confirm: bool | None = None,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Update a mailbox's display name, reply-to, receive policy, retention tier, contact, or metadata. Lowering the retention tier onto remembered messages older than the new horizon requires confirm=true.

        ```python
        mailbox = await client.mailbox.update(
            "mbx_01krdgeqcxet5s7t44vh8rt9mg", display_name="Billing"
        )
        print(mailbox.display_name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(display_name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["display_name"] = display_name
        if not isinstance(default_reply_to, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["default_reply_to"] = default_reply_to
        if receive_policy is not None:
            _body["receive_policy"] = receive_policy
        if retention_tier is not None:
            _body["retention_tier"] = retention_tier
        if metadata is not None:
            _body["metadata"] = metadata
        body = to_wire_exclude_unset(MailboxUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/email/mailboxes/{mailbox_id}",
            body,
            Mailbox,
            options,
            {
                "confirm": confirm,
            },
        )

    async def delete(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a mailbox. The address stops receiving immediately and is quarantined; the mailbox and its remembered messages stay restorable for 30 days via the restore endpoint, then are permanently deleted.

        ```python
        await client.mailbox.delete("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/email/mailboxes/{mailbox_id}", options)

    async def restore(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Restore a mailbox deleted less than 30 days ago: the address starts receiving again and the remembered messages are back. Past the window the mailbox is permanently deleted and returns 404; a mailbox that is not deleted returns 409.

        ```python
        mailbox = await client.mailbox.restore("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.id)
        ```
        """
        return await self._action(
            "POST",
            f"/v1/email/mailboxes/{mailbox_id}/restore",
            Mailbox,
            options,
        )

    async def resume(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Mailbox:
        """Reactivate a suspended mailbox so it can send and receive again and its threads become visible. Fails if your plan does not have room for another active mailbox (or another custom inbox.ai handle); delete an active mailbox or upgrade first. A mailbox that is not suspended returns 409.

        ```python
        mailbox = await client.mailbox.resume("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(mailbox.state)
        ```
        """
        return await self._action(
            "POST",
            f"/v1/email/mailboxes/{mailbox_id}/resume",
            Mailbox,
            options,
        )

    async def stats(
        self,
        mailbox_id: str,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        granularity: str | None = None,
        options: RequestOptions | None = None,
    ) -> MailboxStatsResponse:
        """
        ```python
        stats = await client.mailbox.stats("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        print(stats.summary)
        ```
        """
        return await self._get(
            f"/v1/email/mailboxes/{mailbox_id}/stats",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "granularity": granularity,
            },
            MailboxStatsResponse,
            options,
        )

    async def labels(
        self,
        mailbox_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> EmailMailboxLabelList:
        """List the labels available in a mailbox: the built-in system labels (inbox, archive, spam, blocked, sent, trash, unread) plus every custom label in use.

        ```python
        labels = await client.mailbox.labels("mbx_01krdgeqcxet5s7t44vh8rt9mg")
        for label in labels.data:
            print(label.name)
        ```
        """
        return await self._get(
            f"/v1/email/mailboxes/{mailbox_id}/labels",
            {},
            EmailMailboxLabelList,
            options,
        )
