# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, TypedDict

from bird._generated import (
    RealtimeBatchPublish,
    RealtimeBatchPublishResult,
    RealtimePublish,
    RealtimePublishResult,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class _RealtimeBatchEventRequired(TypedDict):
    event: str
    channel: str


class RealtimeBatchEvent(_RealtimeBatchEventRequired, total=False):
    data: Any
    exclude_connection_id: str
    include: Sequence[str]


class _RealtimePublishRequired(TypedDict):
    event: str
    channels: Sequence[str]


class RealtimePublishParams(_RealtimePublishRequired, total=False):
    """Params for ``client.realtime.publish``. ``event`` and ``channels`` are required."""

    data: Any
    exclude_connection_id: str
    include: Sequence[str]


class _RealtimePublishBatchRequired(TypedDict):
    events: Sequence[RealtimeBatchEvent]


class RealtimePublishBatchParams(_RealtimePublishBatchRequired, total=False):
    """Params for ``client.realtime.publish_batch``. ``events`` is required."""


class RealtimeBase(Resource):
    def publish(
        self,
        realtime_app_id: str,
        *,
        event: str,
        channels: Sequence[str],
        data: Any | None = None,
        exclude_connection_id: str | None = None,
        include: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> RealtimePublishResult:
        """
        ```python
        result = client.realtime.publish(
            "rap_01krdgeqcxet5s7t44vh8rt9mg",
            event="order.updated",
            channels=["orders", "presence-lobby"],
            data={"order_id": "ord_123", "status": "shipped"},
        )
        print(result.data)
        ```
        """
        body = to_wire(
            RealtimePublish,
            {
                "event": event,
                "channels": channels,
                "data": data,
                "exclude_connection_id": exclude_connection_id,
                "include": include,
            },
        )
        return self._write(
            "POST",
            f"/v1/realtime/apps/{realtime_app_id}/events",
            body,
            RealtimePublishResult,
            options,
            schemes=("RealtimeKey", "RealtimeSecret",),
        )

    def publish_batch(
        self,
        realtime_app_id: str,
        *,
        events: Sequence[RealtimeBatchEvent],
        options: RequestOptions | None = None,
    ) -> RealtimeBatchPublishResult:
        """
        ```python
        client.realtime.publish_batch(
            "rap_01krdgeqcxet5s7t44vh8rt9mg",
            events=[
                {"event": "order.created", "channel": "orders", "data": {"id": 1}},
                {"event": "order.updated", "channel": "orders", "data": {"id": 2}},
            ],
        )
        ```
        """
        body = to_wire(
            RealtimeBatchPublish,
            {
                "events": events,
            },
        )
        return self._write(
            "POST",
            f"/v1/realtime/apps/{realtime_app_id}/batch-events",
            body,
            RealtimeBatchPublishResult,
            options,
            schemes=("RealtimeKey", "RealtimeSecret",),
        )


class AsyncRealtimeBase(AsyncResource):
    async def publish(
        self,
        realtime_app_id: str,
        *,
        event: str,
        channels: Sequence[str],
        data: Any | None = None,
        exclude_connection_id: str | None = None,
        include: Sequence[str] | None = None,
        options: RequestOptions | None = None,
    ) -> RealtimePublishResult:
        """
        ```python
        result = await client.realtime.publish(
            "rap_01krdgeqcxet5s7t44vh8rt9mg",
            event="order.updated",
            channels=["orders", "presence-lobby"],
            data={"order_id": "ord_123", "status": "shipped"},
        )
        print(result.data)
        ```
        """
        body = to_wire(
            RealtimePublish,
            {
                "event": event,
                "channels": channels,
                "data": data,
                "exclude_connection_id": exclude_connection_id,
                "include": include,
            },
        )
        return await self._write(
            "POST",
            f"/v1/realtime/apps/{realtime_app_id}/events",
            body,
            RealtimePublishResult,
            options,
            schemes=("RealtimeKey", "RealtimeSecret",),
        )

    async def publish_batch(
        self,
        realtime_app_id: str,
        *,
        events: Sequence[RealtimeBatchEvent],
        options: RequestOptions | None = None,
    ) -> RealtimeBatchPublishResult:
        """
        ```python
        await client.realtime.publish_batch(
            "rap_01krdgeqcxet5s7t44vh8rt9mg",
            events=[
                {"event": "order.created", "channel": "orders", "data": {"id": 1}},
                {"event": "order.updated", "channel": "orders", "data": {"id": 2}},
            ],
        )
        ```
        """
        body = to_wire(
            RealtimeBatchPublish,
            {
                "events": events,
            },
        )
        return await self._write(
            "POST",
            f"/v1/realtime/apps/{realtime_app_id}/batch-events",
            body,
            RealtimeBatchPublishResult,
            options,
            schemes=("RealtimeKey", "RealtimeSecret",),
        )
