# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    SMSTemplate,
    SMSTemplateList,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class SmsTemplateListParams(TypedDict, total=False):
    """Query params for ``client.sms_templates.list``. Every key is optional."""

    scope: str
    category: str
    language: str


class SmsTemplates(Resource):
    def list(
        self,
        *,
        scope: str | None = None,
        category: str | None = None,
        language: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSTemplateList:
        """List the SMS templates available to your workspace, including Bird's built-in templates. Filter by scope, category, or language. The catalogue is small and returned in full; this list is not paginated. Use sms_templates_get to read one template's variables before sending with it.

        ```python
        templates = client.sms_templates.list(scope="system")
        for template in templates.data:
            print(template.id, template.name)
        ```
        """
        return self._get(
            "/v1/sms/templates",
            {
                "scope": scope,
                "category": category,
                "language": language,
            },
            SMSTemplateList,
            options,
        )

    def get(
        self,
        template_ref: str,
        *,
        options: RequestOptions | None = None,
    ) -> SMSTemplate:
        """Get one SMS template by its name or id, including its body and the variables it expects. Fetch it before sms_send to see which parameter keys a template send requires.

        ```python
        template = client.sms_templates.get("bird_otp_verification")
        print(template.body, template.variables)
        ```
        """
        return self._get(
            f"/v1/sms/templates/{quote(template_ref, safe='')}",
            {},
            SMSTemplate,
            options,
        )


class AsyncSmsTemplates(AsyncResource):
    async def list(
        self,
        *,
        scope: str | None = None,
        category: str | None = None,
        language: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSTemplateList:
        """List the SMS templates available to your workspace, including Bird's built-in templates. Filter by scope, category, or language. The catalogue is small and returned in full; this list is not paginated. Use sms_templates_get to read one template's variables before sending with it.

        ```python
        templates = await client.sms_templates.list(scope="system")
        for template in templates.data:
            print(template.id, template.name)
        ```
        """
        return await self._get(
            "/v1/sms/templates",
            {
                "scope": scope,
                "category": category,
                "language": language,
            },
            SMSTemplateList,
            options,
        )

    async def get(
        self,
        template_ref: str,
        *,
        options: RequestOptions | None = None,
    ) -> SMSTemplate:
        """Get one SMS template by its name or id, including its body and the variables it expects. Fetch it before sms_send to see which parameter keys a template send requires.

        ```python
        template = await client.sms_templates.get("bird_otp_verification")
        print(template.body, template.variables)
        ```
        """
        return await self._get(
            f"/v1/sms/templates/{quote(template_ref, safe='')}",
            {},
            SMSTemplate,
            options,
        )
