# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict

from bird._generated import (
    SMSStatsByCarrierResponse,
    SMSStatsByCategoryResponse,
    SMSStatsByCountryResponse,
    SMSStatsByErrorCodeResponse,
    SMSStatsByOriginatorResponse,
    SMSStatsByStatusResponse,
    SMSStatsByTagResponse,
    SMSStatsResponse,
    SMSStatsSummary,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class SmsStatsSummaryParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.summary``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    originator: str
    country: str
    category: str
    carrier: str
    compare: str


class SmsStatsDailyParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.daily``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    originator: str
    country: str
    category: str
    carrier: str


class SmsStatsHourlyParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.hourly``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    originator: str
    country: str
    category: str
    carrier: str


class SmsStatsByCountryParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_country``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsByCarrierParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_carrier``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsByCategoryParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_category``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsByOriginatorParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_originator``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsByStatusParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_status``. Every key is optional."""

    from_: str
    to: str
    timezone: str


class SmsStatsByErrorCodeParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_error_code``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsByTagParams(TypedDict, total=False):
    """Query params for ``client.sms.stats.by_tag``. Every key is optional."""

    from_: str
    to: str
    timezone: str
    sort: str
    limit: int
    include_trend: bool
    trend_grain: str


class SmsStatsBase(Resource):
    def summary(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsSummary:
        """Aggregate SMS KPIs for one period: accepted, sent, delivered, undelivered, failed, rejected and expired counts, the derived delivery and failure rates, and latency percentiles. The `from` and `to` values are both YYYY-MM-DD days or both RFC 3339 instants (hour grain). Add `compare=previous_period` for deltas against the preceding window. For a per-day or per-hour series use `sms.stats.daily` or `sms.stats.hourly`.

        ```python
        summary = client.sms.stats.summary(from_="2026-05-01", to="2026-05-31")
        print(summary.delivery, summary.latency)
        ```
        """
        return self._get(
            "/v1/sms/stats/summary",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
                "compare": compare,
            },
            SMSStatsSummary,
            options,
        )

    def daily(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsResponse:
        """One row of SMS lifecycle counts per calendar day, for charts and trend lines. The window is at most 365 days; set `timezone` to get local calendar days instead of UTC. Rates and latency percentiles are whole-window figures, so read those from `sms.stats.summary`.

        ```python
        stats = client.sms.stats.daily(from_="2026-05-01", to="2026-05-31")
        for point in stats.data or []:
            print(point.bucket, point.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/daily",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
            },
            SMSStatsResponse,
            options,
        )

    def hourly(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsResponse:
        """One row of SMS lifecycle counts per hour, for inspecting send rate and deliverability inside a single day. The window is at most 30 days (720 rows) and both bounds round down to the hour. For longer ranges use `sms.stats.daily`.

        ```python
        stats = client.sms.stats.hourly(from_="2026-05-30T00:00:00Z", to="2026-05-31T00:00:00Z")
        for point in stats.data or []:
            print(point.bucket, point.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/hourly",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
            },
            SMSStatsResponse,
            options,
        )

    def by_country(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCountryResponse:
        """SMS delivery and latency stats grouped by destination country, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to find where delivery is worst before drilling into `sms.stats.by_error_code`.

        ```python
        stats = client.sms.stats.by_country(from_="2026-05-01", to="2026-05-31", sort="delivery_rate")
        for row in stats.data or []:
            print(row.country, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/countries",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCountryResponse,
            options,
        )

    def by_carrier(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCarrierResponse:
        """SMS delivery and latency stats grouped by the carrier that handled the message, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare delivery performance across carriers.

        ```python
        stats = client.sms.stats.by_carrier(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.carrier, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/carriers",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCarrierResponse,
            options,
        )

    def by_category(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCategoryResponse:
        """SMS delivery and latency stats grouped by the category you sent under, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200).

        ```python
        stats = client.sms.stats.by_category(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.category, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/categories",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCategoryResponse,
            options,
        )

    def by_originator(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByOriginatorResponse:
        """SMS delivery and latency stats grouped by originator, the sender address messages went out from, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare how your senders perform.

        ```python
        stats = client.sms.stats.by_originator(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.originator, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/originators",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByOriginatorResponse,
            options,
        )

    def by_status(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByStatusResponse:
        """How many messages ended the period in each lifecycle status: accepted, sent, delivered, undelivered, failed, rejected, expired, ordered by count. The "where did my messages end up" view, suitable for a status-distribution chart.

        ```python
        stats = client.sms.stats.by_status(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.status, row.count)
        ```
        """
        return self._get(
            "/v1/sms/stats/statuses",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
            },
            SMSStatsByStatusResponse,
            options,
        )

    def by_error_code(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByErrorCodeResponse:
        """SMS stats grouped by our normalized failure reason, which answers which reasons are driving your failures. The grouping key is the same value as the `error_code` filter on `sms.list`, so a row joins straight to the messages behind it. Ranked by the `sort` metric (default `failed`) and capped by `limit`.

        ```python
        stats = client.sms.stats.by_error_code(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            # The same value as the error_code filter on client.sms.list.
            print(row.error_code, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/error-codes",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByErrorCodeResponse,
            options,
        )

    def by_tag(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByTagResponse:
        """SMS delivery and latency stats grouped by tag (`name:value`), ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total.

        ```python
        stats = client.sms.stats.by_tag(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            # A message carrying several tags counts once under each, so rows do not
            # sum to the period total.
            print(row.tag, row.delivery)
        ```
        """
        return self._get(
            "/v1/sms/stats/tags",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByTagResponse,
            options,
        )


class AsyncSmsStatsBase(AsyncResource):
    async def summary(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        compare: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsSummary:
        """Aggregate SMS KPIs for one period: accepted, sent, delivered, undelivered, failed, rejected and expired counts, the derived delivery and failure rates, and latency percentiles. The `from` and `to` values are both YYYY-MM-DD days or both RFC 3339 instants (hour grain). Add `compare=previous_period` for deltas against the preceding window. For a per-day or per-hour series use `sms.stats.daily` or `sms.stats.hourly`.

        ```python
        summary = await client.sms.stats.summary(from_="2026-05-01", to="2026-05-31")
        print(summary.delivery, summary.latency)
        ```
        """
        return await self._get(
            "/v1/sms/stats/summary",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
                "compare": compare,
            },
            SMSStatsSummary,
            options,
        )

    async def daily(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsResponse:
        """One row of SMS lifecycle counts per calendar day, for charts and trend lines. The window is at most 365 days; set `timezone` to get local calendar days instead of UTC. Rates and latency percentiles are whole-window figures, so read those from `sms.stats.summary`.

        ```python
        stats = await client.sms.stats.daily(from_="2026-05-01", to="2026-05-31")
        for point in stats.data or []:
            print(point.bucket, point.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/daily",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
            },
            SMSStatsResponse,
            options,
        )

    async def hourly(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        originator: str | None = None,
        country: str | None = None,
        category: str | None = None,
        carrier: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsResponse:
        """One row of SMS lifecycle counts per hour, for inspecting send rate and deliverability inside a single day. The window is at most 30 days (720 rows) and both bounds round down to the hour. For longer ranges use `sms.stats.daily`.

        ```python
        stats = await client.sms.stats.hourly(from_="2026-05-30T00:00:00Z", to="2026-05-31T00:00:00Z")
        for point in stats.data or []:
            print(point.bucket, point.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/hourly",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "originator": originator,
                "country": country,
                "category": category,
                "carrier": carrier,
            },
            SMSStatsResponse,
            options,
        )

    async def by_country(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCountryResponse:
        """SMS delivery and latency stats grouped by destination country, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to find where delivery is worst before drilling into `sms.stats.by_error_code`.

        ```python
        stats = await client.sms.stats.by_country(from_="2026-05-01", to="2026-05-31", sort="delivery_rate")
        for row in stats.data or []:
            print(row.country, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/countries",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCountryResponse,
            options,
        )

    async def by_carrier(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCarrierResponse:
        """SMS delivery and latency stats grouped by the carrier that handled the message, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare delivery performance across carriers.

        ```python
        stats = await client.sms.stats.by_carrier(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.carrier, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/carriers",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCarrierResponse,
            options,
        )

    async def by_category(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByCategoryResponse:
        """SMS delivery and latency stats grouped by the category you sent under, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200).

        ```python
        stats = await client.sms.stats.by_category(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.category, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/categories",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByCategoryResponse,
            options,
        )

    async def by_originator(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByOriginatorResponse:
        """SMS delivery and latency stats grouped by originator, the sender address messages went out from, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare how your senders perform.

        ```python
        stats = await client.sms.stats.by_originator(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.originator, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/originators",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByOriginatorResponse,
            options,
        )

    async def by_status(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByStatusResponse:
        """How many messages ended the period in each lifecycle status: accepted, sent, delivered, undelivered, failed, rejected, expired, ordered by count. The "where did my messages end up" view, suitable for a status-distribution chart.

        ```python
        stats = await client.sms.stats.by_status(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            print(row.status, row.count)
        ```
        """
        return await self._get(
            "/v1/sms/stats/statuses",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
            },
            SMSStatsByStatusResponse,
            options,
        )

    async def by_error_code(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByErrorCodeResponse:
        """SMS stats grouped by our normalized failure reason, which answers which reasons are driving your failures. The grouping key is the same value as the `error_code` filter on `sms.list`, so a row joins straight to the messages behind it. Ranked by the `sort` metric (default `failed`) and capped by `limit`.

        ```python
        stats = await client.sms.stats.by_error_code(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            # The same value as the error_code filter on client.sms.list.
            print(row.error_code, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/error-codes",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByErrorCodeResponse,
            options,
        )

    async def by_tag(
        self,
        *,
        from_: str | None = None,
        to: str | None = None,
        timezone: str | None = None,
        sort: str | None = None,
        limit: int | None = None,
        include_trend: bool | None = None,
        trend_grain: str | None = None,
        options: RequestOptions | None = None,
    ) -> SMSStatsByTagResponse:
        """SMS delivery and latency stats grouped by tag (`name:value`), ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total.

        ```python
        stats = await client.sms.stats.by_tag(from_="2026-05-01", to="2026-05-31")
        for row in stats.data or []:
            # A message carrying several tags counts once under each, so rows do not
            # sum to the period total.
            print(row.tag, row.delivery)
        ```
        """
        return await self._get(
            "/v1/sms/stats/tags",
            {
                "from": from_,
                "to": to,
                "timezone": timezone,
                "sort": sort,
                "limit": limit,
                "include_trend": include_trend,
                "trend_grain": trend_grain,
            },
            SMSStatsByTagResponse,
            options,
        )
