# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    Suppression,
    SuppressionCreate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class SuppressionsListParams(TypedDict, total=False):
    """Query params for ``client.suppressions.list``. Every key is optional."""

    email: str
    reason: str
    scope_type: str
    limit: int
    starting_after: str
    ending_before: str


class _SuppressionsAddRequired(TypedDict):
    email: str


class SuppressionsAddParams(_SuppressionsAddRequired, total=False):
    """Params for ``client.suppressions.add``. ``email`` is required."""


class Suppressions(Resource):
    def list(
        self,
        *,
        email: str | None = None,
        reason: str | None = None,
        scope_type: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[Suppression]:
        """List the workspace's email suppressions as a cursor page. A suppression blocks delivery to an address. The `email` parameter filters by prefix, so compare the complete addresses you get back before treating one as a match.

        ```python
        for suppression in client.suppressions.list():
            print(suppression.email, suppression.reason)
        ```
        """
        query = {
            "email": email,
            "reason": reason,
            "scope_type": scope_type,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/email/suppressions", query, Suppression, options)

    def get(
        self,
        suppression_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Suppression:
        """Fetch one suppression record by its ID: the address, why it's suppressed, how the record originated, and which categories it blocks. Use `suppressions.list` with `email` when you only know the address. Compare complete addresses across all cursor pages because that filter matches by prefix.

        ```python
        suppression = client.suppressions.get("sup_abc123")
        print(suppression.reason, suppression.applies_to)
        ```
        """
        return self._get(
            f"/v1/email/suppressions/{quote(suppression_id, safe='')}",
            {},
            Suppression,
            options,
        )

    def add(
        self,
        *,
        email: str,
        options: RequestOptions | None = None,
    ) -> Suppression:
        """Add an email address to the workspace suppression list to stop delivery to it. The record is created with reason `manual`, which blocks every message category, transactional mail included. Adding is idempotent, so an address that already carries a manual suppression comes back unchanged.

        ```python
        # Adding is idempotent, so an address that already carries a manual
        # suppression returns the existing record.
        suppression = client.suppressions.add(email="blocked@example.com")
        print(suppression.id)
        ```
        """
        body = to_wire(
            SuppressionCreate,
            {
                "email": email,
            },
        )
        return self._write(
            "POST",
            "/v1/email/suppressions",
            body,
            Suppression,
            options,
        )

    def remove(
        self,
        suppression_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one suppression record by ID. Check for other blocking records before resuming delivery. Removing a block without cause can harm sender reputation. An API key cannot remove a `complaint` record; use the dashboard for that record.

        ```python
        # An API key cannot remove a `complaint` record; those come off in the dashboard.
        client.suppressions.remove("sup_abc123")
        ```
        """
        self._delete(f"/v1/email/suppressions/{quote(suppression_id, safe='')}", options)


class AsyncSuppressions(AsyncResource):
    def list(
        self,
        *,
        email: str | None = None,
        reason: str | None = None,
        scope_type: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[Suppression]:
        """List the workspace's email suppressions as a cursor page. A suppression blocks delivery to an address. The `email` parameter filters by prefix, so compare the complete addresses you get back before treating one as a match.

        ```python
        async for suppression in client.suppressions.list():
            print(suppression.email, suppression.reason)
        ```
        """
        query = {
            "email": email,
            "reason": reason,
            "scope_type": scope_type,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/email/suppressions", query, Suppression, options)

    async def get(
        self,
        suppression_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> Suppression:
        """Fetch one suppression record by its ID: the address, why it's suppressed, how the record originated, and which categories it blocks. Use `suppressions.list` with `email` when you only know the address. Compare complete addresses across all cursor pages because that filter matches by prefix.

        ```python
        suppression = await client.suppressions.get("sup_abc123")
        print(suppression.reason, suppression.applies_to)
        ```
        """
        return await self._get(
            f"/v1/email/suppressions/{quote(suppression_id, safe='')}",
            {},
            Suppression,
            options,
        )

    async def add(
        self,
        *,
        email: str,
        options: RequestOptions | None = None,
    ) -> Suppression:
        """Add an email address to the workspace suppression list to stop delivery to it. The record is created with reason `manual`, which blocks every message category, transactional mail included. Adding is idempotent, so an address that already carries a manual suppression comes back unchanged.

        ```python
        # Adding is idempotent, so an address that already carries a manual
        # suppression returns the existing record.
        suppression = await client.suppressions.add(email="blocked@example.com")
        print(suppression.id)
        ```
        """
        body = to_wire(
            SuppressionCreate,
            {
                "email": email,
            },
        )
        return await self._write(
            "POST",
            "/v1/email/suppressions",
            body,
            Suppression,
            options,
        )

    async def remove(
        self,
        suppression_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Remove one suppression record by ID. Check for other blocking records before resuming delivery. Removing a block without cause can harm sender reputation. An API key cannot remove a `complaint` record; use the dashboard for that record.

        ```python
        # An API key cannot remove a `complaint` record; those come off in the dashboard.
        await client.suppressions.remove("sup_abc123")
        ```
        """
        await self._delete(f"/v1/email/suppressions/{quote(suppression_id, safe='')}", options)
