# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict

from bird._generated import (
    Verification,
    VerificationCheckRequest,
    VerificationCheckResult,
    VerificationCreateRequest,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class VerificationTo(TypedDict, total=False):
    email_address: str
    phone_number: str


class VerificationOptions(TypedDict, total=False):
    code_length: int
    channels: Sequence[str]


class _VerifyVerificationsCreateRequired(TypedDict):
    to: VerificationTo


class VerifyVerificationsCreateParams(_VerifyVerificationsCreateRequired, total=False):
    """Params for ``client.verify.verifications.create``. ``to`` is required."""

    options_: VerificationOptions
    metadata: Mapping[str, Any]


class _VerifyVerificationsCheckRequired(TypedDict):
    to: VerificationTo
    code: str


class VerifyVerificationsCheckParams(_VerifyVerificationsCheckRequired, total=False):
    """Params for ``client.verify.verifications.check``. ``to`` and ``code`` are required."""


class VerifyVerifications(Resource):
    def create(
        self,
        *,
        to: VerificationTo,
        options_: VerificationOptions | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Verification:
        """Start a verification: generate a one-time passcode and send it to the recipient in `to` (a phone number over SMS, an email address over email, or both; with both, it is sent over one channel and fails over to the other, not to both at once). Calling again for the same recipient reuses the in-progress verification and sends a fresh code after the resend cooldown; it does not start a second one, so use this both to send and to resend. The passcode is never returned; submit what the recipient enters with verify_verifications_check. SMS delivery draws on the workspace's SMS balance.

        ```python
        verification = client.verify.verifications.create(to={"phone_number": "+15551234567"})
        print(verification.id, verification.status)
        ```
        """
        body = to_wire(
            VerificationCreateRequest,
            {
                "to": to,
                "options": options_,
                "metadata": metadata,
            },
        )
        return self._write(
            "POST",
            "/v1/verify/verifications",
            body,
            Verification,
            options,
        )

    def check(
        self,
        *,
        to: VerificationTo,
        code: str,
        options: RequestOptions | None = None,
    ) -> VerificationCheckResult:
        """Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification id needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`), not an error. A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.

        ```python
        result = client.verify.verifications.check(
            to={"phone_number": "+15551234567"}, code="123456"
        )
        print(result.success)
        ```
        """
        body = to_wire(
            VerificationCheckRequest,
            {
                "to": to,
                "code": code,
            },
        )
        return self._write(
            "POST",
            "/v1/verify/verifications/check",
            body,
            VerificationCheckResult,
            options,
        )


class AsyncVerifyVerifications(AsyncResource):
    async def create(
        self,
        *,
        to: VerificationTo,
        options_: VerificationOptions | None = None,
        metadata: Mapping[str, Any] | None = None,
        options: RequestOptions | None = None,
    ) -> Verification:
        """Start a verification: generate a one-time passcode and send it to the recipient in `to` (a phone number over SMS, an email address over email, or both; with both, it is sent over one channel and fails over to the other, not to both at once). Calling again for the same recipient reuses the in-progress verification and sends a fresh code after the resend cooldown; it does not start a second one, so use this both to send and to resend. The passcode is never returned; submit what the recipient enters with verify_verifications_check. SMS delivery draws on the workspace's SMS balance.

        ```python
        verification = await client.verify.verifications.create(to={"phone_number": "+15551234567"})
        print(verification.id, verification.status)
        ```
        """
        body = to_wire(
            VerificationCreateRequest,
            {
                "to": to,
                "options": options_,
                "metadata": metadata,
            },
        )
        return await self._write(
            "POST",
            "/v1/verify/verifications",
            body,
            Verification,
            options,
        )

    async def check(
        self,
        *,
        to: VerificationTo,
        code: str,
        options: RequestOptions | None = None,
    ) -> VerificationCheckResult:
        """Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification id needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`), not an error. A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.

        ```python
        result = await client.verify.verifications.check(
            to={"phone_number": "+15551234567"}, code="123456"
        )
        print(result.success)
        ```
        """
        body = to_wire(
            VerificationCheckRequest,
            {
                "to": to,
                "code": code,
            },
        )
        return await self._write(
            "POST",
            "/v1/verify/verifications/check",
            body,
            VerificationCheckResult,
            options,
        )
