# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    VoiceTrunk,
    VoiceTrunkCreate,
    VoiceTrunkUpdate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class _VoiceTrunkIPACLCreateRequired(TypedDict):
    cidr: str


class VoiceTrunkIPACLCreate(_VoiceTrunkIPACLCreateRequired, total=False):
    description: str


class VoiceTrunksListParams(TypedDict, total=False):
    """Query params for ``client.voice.trunks.list``. Every key is optional."""

    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str


class _VoiceTrunksCreateRequired(TypedDict):
    name: str


class VoiceTrunksCreateParams(_VoiceTrunksCreateRequired, total=False):
    """Params for ``client.voice.trunks.create``. ``name`` is required."""

    outbound_enabled: bool
    inbound_enabled: bool
    media_bypass: bool
    digest_algorithms: Sequence[str]
    session_credentials_enabled: bool


class VoiceTrunksUpdateParams(TypedDict, total=False):
    """Params for ``client.voice.trunks.update``. Every key is optional."""

    name: str
    outbound_enabled: bool
    inbound_enabled: bool
    media_bypass: bool
    ip_acls: Sequence[VoiceTrunkIPACLCreate]
    allowed_api_key_ids: Sequence[str]
    digest_algorithms: Sequence[str]
    session_credentials_enabled: bool


class VoiceTrunksBase(Resource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[VoiceTrunk]:
        """List the workspace's SIP trunks as a cursor page. Each carries the Bird-assigned `domain` the customer's equipment sends calls to. The `ip_acls` and `allowed_api_key_ids` fields control which calls are admitted; a trunk with both empty admits nothing when `session_credentials_enabled` is false. Keys listed in `ineligible_api_key_ids` cannot authenticate even though they remain bound to the trunk.

        ```python
        for trunk in client.voice.trunks.list():
            # A trunk with no allow list and no session credentials admits nothing.
            print(trunk.id, trunk.domain, trunk.inbound_enabled)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/voice/trunks", query, VoiceTrunk, options)

    def get(
        self,
        trunk_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Fetch one SIP trunk by ID: its `domain`, `ip_acls`, and `allowed_api_key_ids`. Use `voice.trunks.list` to find the ID.

        ```python
        trunk = client.voice.trunks.get("trunk-id")
        print(trunk.name, trunk.inbound_enabled, trunk.outbound_enabled)
        ```
        """
        return self._get(
            f"/v1/voice/trunks/{quote(trunk_id, safe='')}",
            {},
            VoiceTrunk,
            options,
        )

    def create(
        self,
        *,
        name: str,
        outbound_enabled: bool | None = None,
        inbound_enabled: bool | None = None,
        media_bypass: bool | None = None,
        digest_algorithms: Sequence[str] | None = None,
        session_credentials_enabled: bool | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Create a new SIP trunk for the workspace. Returns the Bird-assigned domain to configure in the customer's PBX or SIP client.

        ```python
        trunk = client.voice.trunks.create(
            name="Lisbon office", outbound_enabled=True, inbound_enabled=True
        )
        print(trunk.id, trunk.domain)
        ```
        """
        body = to_wire(
            VoiceTrunkCreate,
            {
                "name": name,
                "outbound_enabled": outbound_enabled,
                "inbound_enabled": inbound_enabled,
                "media_bypass": media_bypass,
                "digest_algorithms": digest_algorithms,
                "session_credentials_enabled": session_credentials_enabled,
            },
        )
        return self._write(
            "POST",
            "/v1/voice/trunks",
            body,
            VoiceTrunk,
            options,
        )

    def update(
        self,
        trunk_id: str,
        *,
        name: str | None = None,
        outbound_enabled: bool | None = None,
        inbound_enabled: bool | None = None,
        media_bypass: bool | None = None,
        ip_acls: Sequence[VoiceTrunkIPACLCreate] | None = None,
        allowed_api_key_ids: Sequence[str] | None = None,
        digest_algorithms: Sequence[str] | None = None,
        session_credentials_enabled: bool | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Change a SIP trunk's directions, name, access control and Digest offer. A direction has to be enabled before its settings can be set, and one update can do both, so this is the operation that clears `VoiceTrunkOutboundNotEnabled` and `VoiceTrunkInboundNotEnabled`. The `ip_acls`, `allowed_api_key_ids` and `digest_algorithms` fields each REPLACE their whole list, so read `voice.trunks.get` first and send the list you want to end up with. An empty array clears an allow list; an empty `digest_algorithms` array restores the default offer. Turning `inbound_enabled` off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes, so confirm that change with the user first.

        ```python
        trunk = client.voice.trunks.update(
            "spt_01krdgeqcxet5s7t44vh8rt9mg",
            # Each list replaces the previous one, so send what you want to end up with.
            ip_acls=[{"cidr": "203.0.113.0/24", "description": "Amsterdam PBX"}],
        )
        print(trunk.ip_acls)
        ```
        """
        body = to_wire(
            VoiceTrunkUpdate,
            {
                "name": name,
                "outbound_enabled": outbound_enabled,
                "inbound_enabled": inbound_enabled,
                "media_bypass": media_bypass,
                "ip_acls": ip_acls,
                "allowed_api_key_ids": allowed_api_key_ids,
                "digest_algorithms": digest_algorithms,
                "session_credentials_enabled": session_credentials_enabled,
            },
        )
        return self._write(
            "PATCH",
            f"/v1/voice/trunks/{quote(trunk_id, safe='')}",
            body,
            VoiceTrunk,
            options,
        )

    def delete(
        self,
        trunk_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a SIP trunk by ID. Calls in progress are not affected; new calls cannot use the trunk. Its generated domain is not reused.

        ```python
        client.voice.trunks.delete("trunk-id")
        ```
        """
        self._delete(f"/v1/voice/trunks/{quote(trunk_id, safe='')}", options)


class AsyncVoiceTrunksBase(AsyncResource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[VoiceTrunk]:
        """List the workspace's SIP trunks as a cursor page. Each carries the Bird-assigned `domain` the customer's equipment sends calls to. The `ip_acls` and `allowed_api_key_ids` fields control which calls are admitted; a trunk with both empty admits nothing when `session_credentials_enabled` is false. Keys listed in `ineligible_api_key_ids` cannot authenticate even though they remain bound to the trunk.

        ```python
        async for trunk in client.voice.trunks.list():
            # A trunk with no allow list and no session credentials admits nothing.
            print(trunk.id, trunk.domain, trunk.inbound_enabled)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/voice/trunks", query, VoiceTrunk, options)

    async def get(
        self,
        trunk_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Fetch one SIP trunk by ID: its `domain`, `ip_acls`, and `allowed_api_key_ids`. Use `voice.trunks.list` to find the ID.

        ```python
        trunk = await client.voice.trunks.get("trunk-id")
        print(trunk.name, trunk.inbound_enabled, trunk.outbound_enabled)
        ```
        """
        return await self._get(
            f"/v1/voice/trunks/{quote(trunk_id, safe='')}",
            {},
            VoiceTrunk,
            options,
        )

    async def create(
        self,
        *,
        name: str,
        outbound_enabled: bool | None = None,
        inbound_enabled: bool | None = None,
        media_bypass: bool | None = None,
        digest_algorithms: Sequence[str] | None = None,
        session_credentials_enabled: bool | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Create a new SIP trunk for the workspace. Returns the Bird-assigned domain to configure in the customer's PBX or SIP client.

        ```python
        trunk = await client.voice.trunks.create(
            name="Lisbon office", outbound_enabled=True, inbound_enabled=True
        )
        print(trunk.id, trunk.domain)
        ```
        """
        body = to_wire(
            VoiceTrunkCreate,
            {
                "name": name,
                "outbound_enabled": outbound_enabled,
                "inbound_enabled": inbound_enabled,
                "media_bypass": media_bypass,
                "digest_algorithms": digest_algorithms,
                "session_credentials_enabled": session_credentials_enabled,
            },
        )
        return await self._write(
            "POST",
            "/v1/voice/trunks",
            body,
            VoiceTrunk,
            options,
        )

    async def update(
        self,
        trunk_id: str,
        *,
        name: str | None = None,
        outbound_enabled: bool | None = None,
        inbound_enabled: bool | None = None,
        media_bypass: bool | None = None,
        ip_acls: Sequence[VoiceTrunkIPACLCreate] | None = None,
        allowed_api_key_ids: Sequence[str] | None = None,
        digest_algorithms: Sequence[str] | None = None,
        session_credentials_enabled: bool | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceTrunk:
        """Change a SIP trunk's directions, name, access control and Digest offer. A direction has to be enabled before its settings can be set, and one update can do both, so this is the operation that clears `VoiceTrunkOutboundNotEnabled` and `VoiceTrunkInboundNotEnabled`. The `ip_acls`, `allowed_api_key_ids` and `digest_algorithms` fields each REPLACE their whole list, so read `voice.trunks.get` first and send the list you want to end up with. An empty array clears an allow list; an empty `digest_algorithms` array restores the default offer. Turning `inbound_enabled` off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes, so confirm that change with the user first.

        ```python
        trunk = await client.voice.trunks.update(
            "spt_01krdgeqcxet5s7t44vh8rt9mg",
            # Each list replaces the previous one, so send what you want to end up with.
            ip_acls=[{"cidr": "203.0.113.0/24", "description": "Amsterdam PBX"}],
        )
        print(trunk.ip_acls)
        ```
        """
        body = to_wire(
            VoiceTrunkUpdate,
            {
                "name": name,
                "outbound_enabled": outbound_enabled,
                "inbound_enabled": inbound_enabled,
                "media_bypass": media_bypass,
                "ip_acls": ip_acls,
                "allowed_api_key_ids": allowed_api_key_ids,
                "digest_algorithms": digest_algorithms,
                "session_credentials_enabled": session_credentials_enabled,
            },
        )
        return await self._write(
            "PATCH",
            f"/v1/voice/trunks/{quote(trunk_id, safe='')}",
            body,
            VoiceTrunk,
            options,
        )

    async def delete(
        self,
        trunk_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Delete a SIP trunk by ID. Calls in progress are not affected; new calls cannot use the trunk. Its generated domain is not reused.

        ```python
        await client.voice.trunks.delete("trunk-id")
        ```
        """
        await self._delete(f"/v1/voice/trunks/{quote(trunk_id, safe='')}", options)
