# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import Any, TypedDict
from urllib.parse import quote

from bird._generated import (
    VoiceInboundConfigurationPut,
    VoiceNumber,
    VoiceNumberUpdate,
)
from bird._models import to_wire_exclude_unset
from bird._resource import AsyncResource, Resource
from bird._types import Omit, RequestOptions, omit
from bird.pagination import AsyncPage, SyncPage


class VoiceNumbersListParams(TypedDict, total=False):
    """Query params for ``client.voice.numbers.list``. Every key is optional."""

    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str


class VoiceNumbersUpdateParams(TypedDict, total=False):
    """Params for ``client.voice.numbers.update``. Every key is optional."""

    name: str | None
    inbound_configuration: VoiceInboundConfigurationPut


class VoiceNumbers(Resource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[VoiceNumber]:
        """List every phone number the workspace can use for voice, as a cursor page ordered by number. Each entry is one phone number, with where its calls go and whether it may be presented on an outbound call.

        ```python
        for number in client.voice.numbers.list():
            print(number.id, number.phone_number, number.country_code)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/voice/numbers", query, VoiceNumber, options)

    def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> VoiceNumber:
        """Fetch one phone number the workspace can use for voice by id: where its calls go, whether it may be presented on an outbound call, and where it came from. Use `voice.numbers.list` to find the id.

        ```python
        number = client.voice.numbers.get("number-id")
        print(number.phone_number, number.directions)
        ```
        """
        return self._get(
            f"/v1/voice/numbers/{quote(number_id, safe='')}",
            {},
            VoiceNumber,
            options,
        )

    def update(
        self,
        number_id: str,
        *,
        name: str | None | Omit = omit,
        inbound_configuration: VoiceInboundConfigurationPut | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceNumber:
        """Change what happens to calls arriving for one number, or the workspace's own label for it. Set the route to `reject` to stop it answering, to `trunk` with a trunk_id to deliver to one of your SIP trunks, or to `forward` with a forward_to and a forward_as to place a call to one of your verified caller IDs. The route replaces whatever was set before, because a number has exactly one answer at a time, and `forward_as` must be stated on every forward. Only a number whose calls arrive at Bird can carry a route.

        ```python
        number = client.voice.numbers.update("number-id", name="Support line")
        print(number.id, number.name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["name"] = name
        if inbound_configuration is not None:
            _body["inbound_configuration"] = inbound_configuration
        body = to_wire_exclude_unset(VoiceNumberUpdate, _body)
        return self._write(
            "PATCH",
            f"/v1/voice/numbers/{quote(number_id, safe='')}",
            body,
            VoiceNumber,
            options,
        )


class AsyncVoiceNumbers(AsyncResource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[VoiceNumber]:
        """List every phone number the workspace can use for voice, as a cursor page ordered by number. Each entry is one phone number, with where its calls go and whether it may be presented on an outbound call.

        ```python
        async for number in client.voice.numbers.list():
            print(number.id, number.phone_number, number.country_code)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/voice/numbers", query, VoiceNumber, options)

    async def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> VoiceNumber:
        """Fetch one phone number the workspace can use for voice by id: where its calls go, whether it may be presented on an outbound call, and where it came from. Use `voice.numbers.list` to find the id.

        ```python
        number = await client.voice.numbers.get("number-id")
        print(number.phone_number, number.directions)
        ```
        """
        return await self._get(
            f"/v1/voice/numbers/{quote(number_id, safe='')}",
            {},
            VoiceNumber,
            options,
        )

    async def update(
        self,
        number_id: str,
        *,
        name: str | None | Omit = omit,
        inbound_configuration: VoiceInboundConfigurationPut | None = None,
        options: RequestOptions | None = None,
    ) -> VoiceNumber:
        """Change what happens to calls arriving for one number, or the workspace's own label for it. Set the route to `reject` to stop it answering, to `trunk` with a trunk_id to deliver to one of your SIP trunks, or to `forward` with a forward_to and a forward_as to place a call to one of your verified caller IDs. The route replaces whatever was set before, because a number has exactly one answer at a time, and `forward_as` must be stated on every forward. Only a number whose calls arrive at Bird can carry a route.

        ```python
        number = await client.voice.numbers.update("number-id", name="Support line")
        print(number.id, number.name)
        ```
        """
        _body: dict[str, Any] = {}
        if not isinstance(name, Omit):  # None clears (JSON null); omit leaves it unchanged
            _body["name"] = name
        if inbound_configuration is not None:
            _body["inbound_configuration"] = inbound_configuration
        body = to_wire_exclude_unset(VoiceNumberUpdate, _body)
        return await self._write(
            "PATCH",
            f"/v1/voice/numbers/{quote(number_id, safe='')}",
            body,
            VoiceNumber,
            options,
        )
