# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    WebhookAttemptList,
    WebhookEndpoint,
    WebhookEndpointCreate,
    WebhookEndpointCreated,
    WebhookEndpointUpdate,
    WebhookRotateSecretResponse,
    WebhookTestRequest,
    WebhookTestResponse,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class WebhooksListParams(TypedDict, total=False):
    """Query params for ``client.webhooks.list``. Every key is optional."""

    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str
    include_total: bool


class _WebhooksCreateRequired(TypedDict):
    url: str
    events: Sequence[str]


class WebhooksCreateParams(_WebhooksCreateRequired, total=False):
    """Params for ``client.webhooks.create``. ``url`` and ``events`` are required."""

    description: str


class WebhooksTestParams(TypedDict, total=False):
    """Params for ``client.webhooks.test``. Every key is optional."""

    event_type: str


class WebhooksAttemptsParams(TypedDict, total=False):
    """Query params for ``client.webhooks.attempts``. Every key is optional."""

    limit: int
    before: str
    after: str


class WebhooksUpdateParams(TypedDict, total=False):
    """Params for ``client.webhooks.update``. Every key is optional."""

    url: str
    description: str
    events: Sequence[str]
    status: str


class WebhooksBase(Resource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[WebhookEndpoint]:
        """List the workspace's webhook endpoints (URL, subscribed events, status) as a cursor page.

        ```python
        for endpoint in client.webhooks.list():
            print(endpoint.id, endpoint.url, endpoint.status)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return SyncPage(self._client, "/v1/webhooks", query, WebhookEndpoint, options)

    def get(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WebhookEndpoint:
        """Read one endpoint's URL, subscribed event types, and current delivery status. The signing secret is never included, and can only be rotated rather than retrieved.

        ```python
        endpoint = client.webhooks.get("whk_01krdgeqcxet5s7t44vh8rt9mg")
        print(endpoint.url, endpoint.events)
        ```
        """
        return self._get(
            f"/v1/webhooks/{quote(webhook_id, safe='')}",
            {},
            WebhookEndpoint,
            options,
        )

    def create(
        self,
        *,
        url: str,
        events: Sequence[str],
        description: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookEndpointCreated:
        """Register an HTTPS endpoint to receive this workspace's events, subscribed to the event types in `events` and active immediately. The response is the only place the signing secret appears, and it can never be read back afterward, only rotated.

        ```python
        created = client.webhooks.create(
            url="https://acme.com/hooks/bird",
            events=["email.delivered", "email.bounced"],
            description="Delivery pipeline",
        )
        print(created.id, created.secret)
        ```
        """
        body = to_wire(
            WebhookEndpointCreate,
            {
                "url": url,
                "events": events,
                "description": description,
            },
        )
        return self._write(
            "POST",
            "/v1/webhooks",
            body,
            WebhookEndpointCreated,
            options,
        )

    def test(
        self,
        webhook_id: str,
        *,
        event_type: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookTestResponse:
        """Send a signed synthetic event and get the outcome synchronously: whether the endpoint accepted, the HTTP status it returned, and the round-trip latency. An unreachable endpoint comes back as a failed status in the body rather than a request error. The receiver has 10 seconds, the body is a minimal stub carrying only the event type, and a test reaches even a paused endpoint without being recorded in the delivery attempts.

        ```python
        result = client.webhooks.test(
            "whk_01krdgeqcxet5s7t44vh8rt9mg",
            event_type="email.delivered",
        )
        print(result.status)
        ```
        """
        body = to_wire(
            WebhookTestRequest,
            {
                "event_type": event_type,
            },
        )
        return self._write(
            "POST",
            f"/v1/webhooks/{quote(webhook_id, safe='')}/test",
            body,
            WebhookTestResponse,
            options,
        )

    def delete(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently remove an endpoint and stop every delivery to it, including retries of earlier failures. Recreating it later mints a new ID and signing secret; to stop deliveries temporarily instead, set its status to `paused`.

        ```python
        client.webhooks.delete("whk_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        self._delete(f"/v1/webhooks/{quote(webhook_id, safe='')}", options)

    def attempts(
        self,
        webhook_id: str,
        *,
        limit: int | None = None,
        before: str | None = None,
        after: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookAttemptList:
        """List an endpoint's recent delivery attempts, newest first. Each entry is one HTTP request, so a retried event appears once per try. Pagination uses the `before`/`after` timestamps; page further back by passing the oldest `attempted_at` you received as `before`.

        ```python
        attempts = client.webhooks.attempts("whk_01krdgeqcxet5s7t44vh8rt9mg")
        for attempt in attempts.data:
            print(attempt.status, attempt.response_status_code)
        ```
        """
        return self._get(
            f"/v1/webhooks/{quote(webhook_id, safe='')}/attempts",
            {
                "limit": limit,
                "before": before,
                "after": after,
            },
            WebhookAttemptList,
            options,
        )

    def rotate_secret(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WebhookRotateSecretResponse:
        """Mint a new signing secret and return it exactly once; it cannot be retrieved afterward. Both the old and new secrets sign every delivery for 24 hours, after which the old one stops signing. An endpoint holds at most 5 valid secrets, so rotating repeatedly inside that window fails.

        ```python
        rotated = client.webhooks.rotate_secret("whk_01krdgeqcxet5s7t44vh8rt9mg")
        print(rotated.secret)
        ```
        """
        return self._action(
            "POST",
            f"/v1/webhooks/{quote(webhook_id, safe='')}/rotate-secret",
            WebhookRotateSecretResponse,
            options,
        )

    def update(
        self,
        webhook_id: str,
        *,
        url: str | None = None,
        description: str | None = None,
        events: Sequence[str] | None = None,
        status: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookEndpoint:
        """Change an endpoint's URL, description, subscribed event types, or delivery status. Only the fields sent change: `events` replaces the whole subscription set, and `status` pauses or re-enables delivery. Events fired while paused are not delivered.

        ```python
        endpoint = client.webhooks.update(
            "whk_01krdgeqcxet5s7t44vh8rt9mg",
            events=["email.delivered"],
        )
        print(endpoint.events)
        ```
        """
        body = to_wire(
            WebhookEndpointUpdate,
            {
                "url": url,
                "description": description,
                "events": events,
                "status": status,
            },
        )
        return self._write(
            "PATCH",
            f"/v1/webhooks/{quote(webhook_id, safe='')}",
            body,
            WebhookEndpoint,
            options,
        )


class AsyncWebhooksBase(AsyncResource):
    def list(
        self,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        include_total: bool | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[WebhookEndpoint]:
        """List the workspace's webhook endpoints (URL, subscribed events, status) as a cursor page.

        ```python
        async for endpoint in client.webhooks.list():
            print(endpoint.id, endpoint.url, endpoint.status)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
            "include_total": include_total,
        }
        return AsyncPage(self._client, "/v1/webhooks", query, WebhookEndpoint, options)

    async def get(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WebhookEndpoint:
        """Read one endpoint's URL, subscribed event types, and current delivery status. The signing secret is never included, and can only be rotated rather than retrieved.

        ```python
        endpoint = await client.webhooks.get("whk_01krdgeqcxet5s7t44vh8rt9mg")
        print(endpoint.url, endpoint.events)
        ```
        """
        return await self._get(
            f"/v1/webhooks/{quote(webhook_id, safe='')}",
            {},
            WebhookEndpoint,
            options,
        )

    async def create(
        self,
        *,
        url: str,
        events: Sequence[str],
        description: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookEndpointCreated:
        """Register an HTTPS endpoint to receive this workspace's events, subscribed to the event types in `events` and active immediately. The response is the only place the signing secret appears, and it can never be read back afterward, only rotated.

        ```python
        created = await client.webhooks.create(
            url="https://acme.com/hooks/bird",
            events=["email.delivered", "email.bounced"],
            description="Delivery pipeline",
        )
        print(created.id, created.secret)
        ```
        """
        body = to_wire(
            WebhookEndpointCreate,
            {
                "url": url,
                "events": events,
                "description": description,
            },
        )
        return await self._write(
            "POST",
            "/v1/webhooks",
            body,
            WebhookEndpointCreated,
            options,
        )

    async def test(
        self,
        webhook_id: str,
        *,
        event_type: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookTestResponse:
        """Send a signed synthetic event and get the outcome synchronously: whether the endpoint accepted, the HTTP status it returned, and the round-trip latency. An unreachable endpoint comes back as a failed status in the body rather than a request error. The receiver has 10 seconds, the body is a minimal stub carrying only the event type, and a test reaches even a paused endpoint without being recorded in the delivery attempts.

        ```python
        result = await client.webhooks.test(
            "whk_01krdgeqcxet5s7t44vh8rt9mg",
            event_type="email.delivered",
        )
        print(result.status)
        ```
        """
        body = to_wire(
            WebhookTestRequest,
            {
                "event_type": event_type,
            },
        )
        return await self._write(
            "POST",
            f"/v1/webhooks/{quote(webhook_id, safe='')}/test",
            body,
            WebhookTestResponse,
            options,
        )

    async def delete(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> None:
        """Permanently remove an endpoint and stop every delivery to it, including retries of earlier failures. Recreating it later mints a new ID and signing secret; to stop deliveries temporarily instead, set its status to `paused`.

        ```python
        await client.webhooks.delete("whk_01krdgeqcxet5s7t44vh8rt9mg")
        ```
        """
        await self._delete(f"/v1/webhooks/{quote(webhook_id, safe='')}", options)

    async def attempts(
        self,
        webhook_id: str,
        *,
        limit: int | None = None,
        before: str | None = None,
        after: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookAttemptList:
        """List an endpoint's recent delivery attempts, newest first. Each entry is one HTTP request, so a retried event appears once per try. Pagination uses the `before`/`after` timestamps; page further back by passing the oldest `attempted_at` you received as `before`.

        ```python
        attempts = await client.webhooks.attempts("whk_01krdgeqcxet5s7t44vh8rt9mg")
        for attempt in attempts.data:
            print(attempt.status, attempt.response_status_code)
        ```
        """
        return await self._get(
            f"/v1/webhooks/{quote(webhook_id, safe='')}/attempts",
            {
                "limit": limit,
                "before": before,
                "after": after,
            },
            WebhookAttemptList,
            options,
        )

    async def rotate_secret(
        self,
        webhook_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WebhookRotateSecretResponse:
        """Mint a new signing secret and return it exactly once; it cannot be retrieved afterward. Both the old and new secrets sign every delivery for 24 hours, after which the old one stops signing. An endpoint holds at most 5 valid secrets, so rotating repeatedly inside that window fails.

        ```python
        rotated = await client.webhooks.rotate_secret("whk_01krdgeqcxet5s7t44vh8rt9mg")
        print(rotated.secret)
        ```
        """
        return await self._action(
            "POST",
            f"/v1/webhooks/{quote(webhook_id, safe='')}/rotate-secret",
            WebhookRotateSecretResponse,
            options,
        )

    async def update(
        self,
        webhook_id: str,
        *,
        url: str | None = None,
        description: str | None = None,
        events: Sequence[str] | None = None,
        status: str | None = None,
        options: RequestOptions | None = None,
    ) -> WebhookEndpoint:
        """Change an endpoint's URL, description, subscribed event types, or delivery status. Only the fields sent change: `events` replaces the whole subscription set, and `status` pauses or re-enables delivery. Events fired while paused are not delivered.

        ```python
        endpoint = await client.webhooks.update(
            "whk_01krdgeqcxet5s7t44vh8rt9mg",
            events=["email.delivered"],
        )
        print(endpoint.events)
        ```
        """
        body = to_wire(
            WebhookEndpointUpdate,
            {
                "url": url,
                "description": description,
                "events": events,
                "status": status,
            },
        )
        return await self._write(
            "PATCH",
            f"/v1/webhooks/{quote(webhook_id, safe='')}",
            body,
            WebhookEndpoint,
            options,
        )
