# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    WhatsAppNumber,
    WhatsAppNumberEvent,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class WhatsappNumbersListParams(TypedDict, total=False):
    """Query params for ``client.whatsapp.numbers.list``. Every key is optional."""

    waba: str
    phone_number: str
    status: Sequence[str]
    scope: str
    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str


class WhatsappNumbersListEventsParams(TypedDict, total=False):
    """Query params for ``client.whatsapp.numbers.list_events``. Every key is optional."""

    sort: str
    order: str
    limit: int
    starting_after: str
    ending_before: str


class WhatsappNumbersBase(Resource):
    def list(
        self,
        *,
        waba: str | None = None,
        phone_number: str | None = None,
        status: Sequence[str] | None = None,
        scope: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[WhatsAppNumber]:
        """List the WhatsApp numbers the workspace can send from as a cursor page, with each number's WhatsApp state, quality rating, messaging limit, throughput, and Official Business Account status.

        ```python
        for number in client.whatsapp.numbers.list(status=["connected"]):
            print(number.id, number.phone_number, number.status)
        ```
        """
        query = {
            "waba": waba,
            "phone_number": phone_number,
            "status": status,
            "scope": scope,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, "/v1/whatsapp/numbers", query, WhatsAppNumber, options)

    def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppNumber:
        """Read a WhatsApp number and the state WhatsApp reports for it. `next` says what to do about that state, including the browser step that finishes a connection while `status` is `awaiting_signup`.

        ```python
        number = client.whatsapp.numbers.get("wan_01krdgeqcxet5s7t44vh8rt9mg")
        print(number.status, number.quality_rating, number.messaging_limit)
        ```
        """
        return self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}",
            {},
            WhatsAppNumber,
            options,
        )

    def list_events(
        self,
        number_id: str,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[WhatsAppNumberEvent]:
        """The activity history of one WhatsApp number as a cursor page, newest first: when it was added, every change of its status, its messaging-limit and quality-rating changes, and each display-name review decision. This is the read that answers "why did this number's status, limit, or name change"; `whatsapp.numbers.get` gives only the current values. An unknown number ID returns `404`.

        ```python
        for event in client.whatsapp.numbers.list_events("wan_01krdgeqcxet5s7t44vh8rt9mg"):
            print(event.created_at, event.type, event.summary)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/events", query, WhatsAppNumberEvent, options)


class AsyncWhatsappNumbersBase(AsyncResource):
    def list(
        self,
        *,
        waba: str | None = None,
        phone_number: str | None = None,
        status: Sequence[str] | None = None,
        scope: str | None = None,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[WhatsAppNumber]:
        """List the WhatsApp numbers the workspace can send from as a cursor page, with each number's WhatsApp state, quality rating, messaging limit, throughput, and Official Business Account status.

        ```python
        async for number in client.whatsapp.numbers.list(status=["connected"]):
            print(number.id, number.phone_number, number.status)
        ```
        """
        query = {
            "waba": waba,
            "phone_number": phone_number,
            "status": status,
            "scope": scope,
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, "/v1/whatsapp/numbers", query, WhatsAppNumber, options)

    async def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppNumber:
        """Read a WhatsApp number and the state WhatsApp reports for it. `next` says what to do about that state, including the browser step that finishes a connection while `status` is `awaiting_signup`.

        ```python
        number = await client.whatsapp.numbers.get("wan_01krdgeqcxet5s7t44vh8rt9mg")
        print(number.status, number.quality_rating, number.messaging_limit)
        ```
        """
        return await self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}",
            {},
            WhatsAppNumber,
            options,
        )

    def list_events(
        self,
        number_id: str,
        *,
        sort: str | None = None,
        order: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[WhatsAppNumberEvent]:
        """The activity history of one WhatsApp number as a cursor page, newest first: when it was added, every change of its status, its messaging-limit and quality-rating changes, and each display-name review decision. This is the read that answers "why did this number's status, limit, or name change"; `whatsapp.numbers.get` gives only the current values. An unknown number ID returns `404`.

        ```python
        async for event in client.whatsapp.numbers.list_events("wan_01krdgeqcxet5s7t44vh8rt9mg"):
            print(event.created_at, event.type, event.summary)
        ```
        """
        query = {
            "sort": sort,
            "order": order,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/events", query, WhatsAppNumberEvent, options)
