# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from urllib.parse import quote

from bird._generated import (
    WhatsAppGroup,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class WhatsappGroupsParticipants(Resource):
    def remove(
        self,
        group_id: str,
        participant_ref: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppGroup:
        """Remove one person from a group, named by their business-scoped user ID or their phone number. IRREVERSIBLE: WhatsApp blocks a removed person from rejoining by invite link at all, and there is no add operation, so nothing puts them back in this group. Rotating the link does not lift it, and reaching that person again means a new group.

        ```python
        group = client.whatsapp.groups.participants.remove(
            "wag_01krdgeqcxet5s7t44vh8rt9mg",
            "BR.1566655121691972",
        )
        print(len(group.participants or []))
        ```
        """
        return self._delete_model(f"/v1/whatsapp/groups/{quote(group_id, safe='')}/participants/{quote(participant_ref, safe='')}", WhatsAppGroup, options)


class AsyncWhatsappGroupsParticipants(AsyncResource):
    async def remove(
        self,
        group_id: str,
        participant_ref: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppGroup:
        """Remove one person from a group, named by their business-scoped user ID or their phone number. IRREVERSIBLE: WhatsApp blocks a removed person from rejoining by invite link at all, and there is no add operation, so nothing puts them back in this group. Rotating the link does not lift it, and reaching that person again means a new group.

        ```python
        group = await client.whatsapp.groups.participants.remove(
            "wag_01krdgeqcxet5s7t44vh8rt9mg",
            "BR.1566655121691972",
        )
        print(len(group.participants or []))
        ```
        """
        return await self._delete_model(f"/v1/whatsapp/groups/{quote(group_id, safe='')}/participants/{quote(participant_ref, safe='')}", WhatsAppGroup, options)
