# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from urllib.parse import quote

from bird._generated import (
    WhatsAppNumberProfile,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class WhatsappNumbersProfile(Resource):
    def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppNumberProfile:
        """Read the business profile WhatsApp shows to people a connected number messages.

        ```python
        profile = client.whatsapp.numbers.profile.get("wan_01krdgeqcxet5s7t44vh8rt9mg")
        print(profile.display_name, profile.description)
        ```
        """
        return self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/profile",
            {},
            WhatsAppNumberProfile,
            options,
        )


class AsyncWhatsappNumbersProfile(AsyncResource):
    async def get(
        self,
        number_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppNumberProfile:
        """Read the business profile WhatsApp shows to people a connected number messages.

        ```python
        profile = await client.whatsapp.numbers.profile.get("wan_01krdgeqcxet5s7t44vh8rt9mg")
        print(profile.display_name, profile.description)
        ```
        """
        return await self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/profile",
            {},
            WhatsAppNumberProfile,
            options,
        )
