# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict
from urllib.parse import quote

from bird._generated import (
    WhatsAppAgentNotification,
    WhatsAppAgentNotificationCreate,
)
from bird._models import to_wire
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions
from bird.pagination import AsyncPage, SyncPage


class WhatsappAgentsNotificationsListParams(TypedDict, total=False):
    """Query params for ``client.whatsapp.agents.notifications.list``. Every key is optional."""

    status: str
    to: str
    limit: int
    starting_after: str
    ending_before: str


class _WhatsappAgentsNotificationsCreateRequired(TypedDict):
    to: str
    name: str
    description: str
    payload: str


class WhatsappAgentsNotificationsCreateParams(_WhatsappAgentsNotificationsCreateRequired, total=False):
    """Params for ``client.whatsapp.agents.notifications.create``. ``to``, ``name``, ``description``, and ``payload`` are required."""


class WhatsappAgentsNotifications(Resource):
    def list(
        self,
        number_id: str,
        *,
        status: str | None = None,
        to: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> SyncPage[WhatsAppAgentNotification]:
        """List the notifications sent to the agent on this WhatsApp number, newest first, each with what came of it, as a cursor page.

        ```python
        notifications = client.whatsapp.agents.notifications.list("wan_01krdgeqcxet5s7t44vh8rt9mg", status="skipped")
        for notification in notifications.data or []:
            print(notification.name, notification.skipped_reason)
        ```
        """
        query = {
            "status": status,
            "to": to,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return SyncPage(self._client, f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications", query, WhatsAppAgentNotification, options)

    def create(
        self,
        number_id: str,
        *,
        to: str,
        name: str,
        description: str,
        payload: str,
        options: RequestOptions | None = None,
    ) -> WhatsAppAgentNotification:
        """Tell the agent on this WhatsApp number that something happened in your systems for one contact, such as a payment landing or an order shipping, so it can write to them about it. The notification is handed to WhatsApp in the background; read it back with `whatsapp.agents.notifications.get` to see whether the agent acted on it.

        ```python
        # The agent decides whether and how to tell the contact. The answer reads
        # accepted; read it back to see whether the agent acted on it.
        notification = client.whatsapp.agents.notifications.create(
            "wan_01krdgeqcxet5s7t44vh8rt9mg",
            to="+14155551234",
            name="order_shipped",
            description="Order 88213 left the warehouse and arrives on Thursday.",
            payload='{"order_id":"88213","carrier":"ACME Courier"}',
        )
        print(notification.id, notification.status)
        ```
        """
        body = to_wire(
            WhatsAppAgentNotificationCreate,
            {
                "to": to,
                "name": name,
                "description": description,
                "payload": payload,
            },
        )
        return self._write(
            "POST",
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications",
            body,
            WhatsAppAgentNotification,
            options,
        )

    def get(
        self,
        number_id: str,
        notification_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppAgentNotification:
        """Read one notification sent to the agent on this WhatsApp number, with what came of it.

        ```python
        # A notification still on its way to WhatsApp is not readable yet, so a read
        # straight after create can raise a not-found error.
        notification = client.whatsapp.agents.notifications.get(
            "wan_01krdgeqcxet5s7t44vh8rt9mg",
            "waan_01krdgeqcxet5s7t44vh8rt9m7",
        )
        print(notification.status, notification.skipped_reason or notification.error)
        ```
        """
        return self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications/{quote(notification_id, safe='')}",
            {},
            WhatsAppAgentNotification,
            options,
        )


class AsyncWhatsappAgentsNotifications(AsyncResource):
    def list(
        self,
        number_id: str,
        *,
        status: str | None = None,
        to: str | None = None,
        limit: int | None = None,
        starting_after: str | None = None,
        ending_before: str | None = None,
        options: RequestOptions | None = None,
    ) -> AsyncPage[WhatsAppAgentNotification]:
        """List the notifications sent to the agent on this WhatsApp number, newest first, each with what came of it, as a cursor page.

        ```python
        notifications = await client.whatsapp.agents.notifications.list("wan_01krdgeqcxet5s7t44vh8rt9mg", status="skipped")
        for notification in notifications.data or []:
            print(notification.name, notification.skipped_reason)
        ```
        """
        query = {
            "status": status,
            "to": to,
            "limit": limit,
            "starting_after": starting_after,
            "ending_before": ending_before,
        }
        return AsyncPage(self._client, f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications", query, WhatsAppAgentNotification, options)

    async def create(
        self,
        number_id: str,
        *,
        to: str,
        name: str,
        description: str,
        payload: str,
        options: RequestOptions | None = None,
    ) -> WhatsAppAgentNotification:
        """Tell the agent on this WhatsApp number that something happened in your systems for one contact, such as a payment landing or an order shipping, so it can write to them about it. The notification is handed to WhatsApp in the background; read it back with `whatsapp.agents.notifications.get` to see whether the agent acted on it.

        ```python
        # The agent decides whether and how to tell the contact. The answer reads
        # accepted; read it back to see whether the agent acted on it.
        notification = await client.whatsapp.agents.notifications.create(
            "wan_01krdgeqcxet5s7t44vh8rt9mg",
            to="+14155551234",
            name="order_shipped",
            description="Order 88213 left the warehouse and arrives on Thursday.",
            payload='{"order_id":"88213","carrier":"ACME Courier"}',
        )
        print(notification.id, notification.status)
        ```
        """
        body = to_wire(
            WhatsAppAgentNotificationCreate,
            {
                "to": to,
                "name": name,
                "description": description,
                "payload": payload,
            },
        )
        return await self._write(
            "POST",
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications",
            body,
            WhatsAppAgentNotification,
            options,
        )

    async def get(
        self,
        number_id: str,
        notification_id: str,
        *,
        options: RequestOptions | None = None,
    ) -> WhatsAppAgentNotification:
        """Read one notification sent to the agent on this WhatsApp number, with what came of it.

        ```python
        # A notification still on its way to WhatsApp is not readable yet, so a read
        # straight after create can raise a not-found error.
        notification = await client.whatsapp.agents.notifications.get(
            "wan_01krdgeqcxet5s7t44vh8rt9mg",
            "waan_01krdgeqcxet5s7t44vh8rt9m7",
        )
        print(notification.status, notification.skipped_reason or notification.error)
        ```
        """
        return await self._get(
            f"/v1/whatsapp/numbers/{quote(number_id, safe='')}/agent/notifications/{quote(notification_id, safe='')}",
            {},
            WhatsAppAgentNotification,
            options,
        )
