# Code generated by surface-gen; DO NOT EDIT.

from __future__ import annotations

from bird._generated import (
    Workspace,
)
from bird._resource import AsyncResource, Resource
from bird._types import RequestOptions


class WorkspaceResource(Resource):
    def get(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> Workspace:
        """Fetch the current workspace's ID, name, and the ID of the organization owning it. This is the workspace the current credentials are scoped to.

        ```python
        workspace = client.workspace.get()
        print(workspace.id, workspace.name)
        ```
        """
        return self._get(
            "/v1/workspace",
            {},
            Workspace,
            options,
        )


class AsyncWorkspaceResource(AsyncResource):
    async def get(
        self,
        *,
        options: RequestOptions | None = None,
    ) -> Workspace:
        """Fetch the current workspace's ID, name, and the ID of the organization owning it. This is the workspace the current credentials are scoped to.

        ```python
        workspace = await client.workspace.get()
        print(workspace.id, workspace.name)
        ```
        """
        return await self._get(
            "/v1/workspace",
            {},
            Workspace,
            options,
        )
