# Code generated by surface-gen; DO NOT EDIT.
# Operations the sdk surface exposes, KEEP-shaped (path -> methods),
# generated from backend/openapi/surfaces.yaml.
KEEP: dict[str, set[str]] = {
    "/v1/email/messages": {"get", "post"},
    "/v1/email/messages/{message_id}": {"get"},
}
